# Generated by Django 5.2.7 on 2025-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyhierarchy',
            name='focus_area',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='strategyhierarchy',
            name='formula',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='strategyhierarchy',
            name='kpi',
            field=models.CharField(max_length=200, verbose_name='Key Performance Indicator'),
        ),
        migrations.AlterField(
            model_name='strategyhierarchy',
            name='objective',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='strategyhierarchy',
            name='strategic_perspective',
            field=models.CharField(max_length=200),
        ),
    ]
