DEFAULT_SWOT = {
    "Strength": {
        "Operational Excellence": [
            "Streamlined workflows for efficiency",
            "High process reliability",
            "Rapid problem identification",
            "Low operational downtime",
            "Optimized resource utilization",
            "Strong SOP adherence",
            "Effective cross-functional coordination",
            "Automation of routine tasks",
            "Continuous process monitoring",
            "High on-time delivery rate",
            "Lean operations culture",
            "Effective cost management"
        ],
        "Quality Management": [
            "Consistent product/service quality",
            "High regulatory compliance",
            "Advanced QA/QC procedures",
            "Effective supplier quality management",
            "Low defect rates",
            "Continuous improvement culture",
            "Comprehensive quality audits",
            "High customer satisfaction",
            "Strong corrective/preventive actions",
            "ISO/industry certifications achieved",
            "Rapid quality issue response",
            "Integration of quality into strategy"
        ],
        "Risk & Compliance Management": [
            "Proactive risk identification",
            "Effective internal controls",
            "High regulatory compliance adherence",
            "Robust crisis management procedures",
            "Low legal exposure",
            "Comprehensive risk assessment",
            "Regular compliance training",
            "Strong fraud prevention mechanisms",
            "Rapid mitigation of emerging risks",
            "Continuous monitoring of risk KPIs",
            "Accountability culture",
            "Risk integrated into strategy"
        ],
        "Data & Information Management": [
            "Accurate and timely data availability",
            "Centralized data repositories",
            "Strong data governance policies",
            "High data security standards",
            "Effective data analytics capabilities",
            "Reliable reporting mechanisms",
            "Integration of systems and platforms",
            "Data-driven decision making culture",
            "High data quality and integrity",
            "Compliance with data privacy regulations",
            "Advanced BI and dashboard capabilities",
            "Automated data collection and processing"
        ],
        "Innovation Development": [
            "Strong culture of creativity",
            "High number of new initiatives",
            "Effective ideation and brainstorming processes",
            "Cross-functional collaboration in innovation",
            "Rapid prototyping capabilities",
            "High rate of product/service innovation",
            "Robust innovation pipeline",
            "Integration of customer feedback into development",
            "Recognition and reward for innovative ideas",
            "Advanced R&D partnerships",
            "Use of emerging technologies",
            "Continuous innovation monitoring"
        ],
        "Research & Development": [
            "Advanced R&D facilities",
            "Skilled research teams",
            "High IP creation rate",
            "Collaborations with universities",
            "Efficient technology transfer",
            "Rapid prototyping and testing",
            "Strong patent portfolio",
            "R&D aligned with market needs",
            "High R&D investment efficiency",
            "Structured project management in R&D",
            "Innovation-focused culture",
            "Continuous monitoring of R&D outcomes"
        ],
        "Supply Chain & Logistics": [
            "Optimized supply chain networks",
            "High supplier reliability",
            "Efficient logistics and transport",
            "Advanced inventory management",
            "Low stockout rates",
            "Strong vendor relationships",
            "Cost-efficient procurement",
            "Sustainability in supply chain",
            "Real-time tracking of shipments",
            "Effective demand forecasting",
            "Robust distribution planning",
            "High supply chain responsiveness"
        ],
        "Project & Program Management": [
            "Timely project delivery",
            "Effective project planning",
            "Strong risk management in projects",
            "High stakeholder satisfaction",
            "Efficient resource allocation",
            "Clear project governance structures",
            "Robust performance monitoring",
            "Effective issue resolution",
            "Strong cross-functional coordination",
            "High-quality project outcomes",
            "Adherence to budgets",
            "Continuous project improvement culture"
        ],
        "Customer Management Process": [
            "High customer satisfaction",
            "Strong customer retention rates",
            "Effective customer feedback systems",
            "Responsive service delivery",
            "Tailored solutions for customers",
            "Integrated CRM systems",
            "High customer engagement",
            "Proactive problem resolution",
            "Strong account management processes",
            "Data-driven customer insights",
            "High loyalty and repeat business",
            "Customer-centric decision making"
        ],
        "Internal Audit Control": [
            "Comprehensive audit frameworks",
            "High audit coverage across processes",
            "Strong internal control environment",
            "Timely audit reporting",
            "Effective risk-based audit planning",
            "Identification of process gaps",
            "Actionable audit recommendations",
            "Continuous monitoring of controls",
            "Regulatory compliance assurance",
            "Independent and unbiased audits",
            "Integration with risk management",
            "Audit findings tracked to closure"
        ],
        "Health & Safety Environment": [
            "Strong workplace safety programs",
            "Low accident and incident rates",
            "Regular health and safety training",
            "Compliance with regulations",
            "Proactive hazard identification",
            "Effective emergency response plans",
            "High employee safety awareness",
            "Integration of HSE in operations",
            "Continuous monitoring of safety KPIs",
            "Health promotion initiatives",
            "Sustainable safety culture",
            "Regular safety audits and inspections"
        ],
        "Business Continuity & Disaster Recovery": [
            "Comprehensive continuity planning",
            "High disaster preparedness",
            "Redundant systems and backups",
            "Rapid recovery procedures",
            "Regular testing of continuity plans",
            "Cross-functional disaster coordination",
            "Minimal service disruption",
            "High resilience to external shocks",
            "Clear recovery roles and responsibilities",
            "Integration with risk management",
            "Continuous improvement in contingency plans",
            "Robust communication during crises"
        ],
        "Asset & Resource Management": [
            "Efficient asset utilization",
            "High resource productivity",
            "Regular maintenance schedules",
            "Low asset downtime",
            "Optimal inventory levels",
            "Advanced asset tracking systems",
            "Sustainable resource management",
            "Cost-effective resource allocation",
            "Asset lifecycle management",
            "Integration with operational planning",
            "High return on asset investment",
            "Rapid response to asset failures"
        ],
        "Stakeholder Communication & Collaboration": [
            "Effective internal communication channels",
            "High stakeholder engagement",
            "Transparent reporting practices",
            "Strong collaboration culture",
            "Rapid information sharing",
            "Proactive stakeholder management",
            "Feedback loops incorporated",
            "Integrated communication platforms",
            "High participation in decision making",
            "Trust and credibility with stakeholders",
            "Conflict resolution mechanisms",
            "Alignment of stakeholder interests"
        ],
        "Finance Management": [
            "Strong budgeting and forecasting",
            "High liquidity and cash flow",
            "Optimal capital structure",
            "Cost control and efficiency",
            "Financial compliance adherence",
            "Effective investment management",
            "Robust financial reporting",
            "Integration with strategy planning",
            "High return on investments",
            "Rapid financial decision-making",
            "Strong financial risk management",
            "Accurate performance tracking"
        ],
        "Fund Management": [
            "Effective allocation of funds",
            "High investment returns",
            "Low fund mismanagement risks",
            "Transparent reporting of fund use",
            "Compliance with funding policies",
            "Risk-adjusted investment strategies",
            "Rapid fund mobilization",
            "Accurate financial monitoring",
            "Diversified funding sources",
            "Efficient capital deployment",
            "Strong fund governance",
            "Alignment with organizational goals"
        ],
        "Inventory & Materials Management": [
            "Accurate inventory tracking",
            "Optimized stock levels",
            "Reduced wastage and obsolescence",
            "High turnover efficiency",
            "Strong material forecasting",
            "Seamless warehouse operations",
            "Effective material handling",
            "Integration with procurement and production",
            "Cost-effective inventory management",
            "Rapid replenishment cycles",
            "Reliable supplier coordination",
            "Advanced inventory analytics"
        ],
        "Procurement & Vendor Management": [
            "Strategic supplier partnerships",
            "Efficient procurement processes",
            "Cost savings and value optimization",
            "Strong contract management",
            "High supplier performance",
            "Compliance with procurement policies",
            "Risk assessment of vendors",
            "Diversified supplier base",
            "Timely procurement cycles",
            "Integration with supply chain planning",
            "Continuous supplier evaluation",
            "Transparent procurement reporting"
        ],
        "Policy & Governance": [
            "Clear policies and guidelines",
            "High compliance adherence",
            "Strong corporate governance",
            "Transparent decision-making",
            "Effective risk and control frameworks",
            "Regular policy updates",
            "Strong accountability culture",
            "Integration with strategy and operations",
            "Rapid enforcement of policies",
            "Effective oversight and monitoring",
            "Stakeholder engagement in governance",
            "Ethical and legal adherence"
        ],
        "Planning & Strategic Management": [
            "Effective strategic planning",
            "Clear objectives and KPIs",
            "Alignment across business units",
            "Regular performance review",
            "Data-driven decision-making",
            "Risk-informed strategy adjustments",
            "Cross-functional collaboration",
            "Agility in strategy execution",
            "Effective resource allocation",
            "Integration with operational plans",
            "Long-term vision and goals clarity",
            "Continuous monitoring of outcomes"
        ],
        "Human Resource Management": [
            "Attraction of top talent",
            "High employee engagement",
            "Effective training programs",
            "Low turnover and attrition",
            "Succession planning in place",
            "Performance management excellence",
            "Inclusive and diverse workplace",
            "Clear HR policies and governance",
            "Efficient payroll and benefits management",
            "Alignment of HR with strategy",
            "Talent retention initiatives",
            "Strong employer branding"
        ],
        "Technology & Digital Transformation": [
            "Advanced IT infrastructure",
            "High system reliability and uptime",
            "Integration of digital tools",
            "Automation of key processes",
            "Cybersecurity adherence",
            "Rapid adoption of emerging tech",
            "Data-driven insights enabled",
            "Digital innovation culture",
            "Cloud adoption and scalability",
            "Mobile and remote work enablement",
            "Business process digitalization",
            "Continuous tech monitoring and upgrades"
        ],
        "Process Improvement & Lean Management": [
            "Continuous process improvement",
            "Lean methodology adoption",
            "Waste reduction and efficiency",
            "High process standardization",
            "Cross-functional improvement teams",
            "Regular KPI monitoring",
            "Quick implementation of improvements",
            "High employee participation",
            "Integration with operations strategy",
            "Rapid problem-solving culture",
            "Data-driven decision making",
            "Strong feedback loops"
        ],
        "Knowledge Management & Organizational Learning": [
            "Comprehensive knowledge repositories",
            "High organizational learning culture",
            "Cross-functional knowledge sharing",
            "Effective documentation practices",
            "Training aligned with knowledge gaps",
            "Mentorship and coaching programs",
            "Rapid onboarding of new employees",
            "Integration of lessons learned",
            "Knowledge retention strategies",
            "Use of digital knowledge platforms",
            "Continuous improvement based on insights",
            "Collaborative learning environments"
        ],
        "Performance Measurement & Reporting": [
            "Clear KPIs and metrics",
            "Timely performance reporting",
            "High accuracy of data",
            "Benchmarking against best practices",
            "Integrated dashboards and analytics",
            "Alignment with strategic objectives",
            "Regular review and action plans",
            "Continuous performance monitoring",
            "Cross-functional accountability",
            "Employee performance tracking",
            "High transparency of results",
            "Rapid identification of performance gaps"
        ],
        "Legal & Regulatory Affairs": [
            "Strong legal compliance framework",
            "Low litigation exposure",
            "Effective contract management",
            "High regulatory adherence",
            "Rapid response to legal risks",
            "Proactive policy and law monitoring",
            "Strong intellectual property protection",
            "Integration with risk management",
            "Clear legal governance policies",
            "High stakeholder trust in compliance",
            "Efficient handling of legal disputes",
            "Training programs for regulatory awareness"
        ],
        "Change & Transformation Management": [
            "Successful change adoption",
            "High employee adaptability",
            "Clear communication during transformations",
            "Effective change leadership",
            "Strong stakeholder engagement",
            "Integration with strategy and operations",
            "Continuous evaluation of change outcomes",
            "Rapid response to resistance",
            "Structured change management methodology",
            "Culture supportive of transformation",
            "Tracking of change KPIs",
            "Learning from past change initiatives"
        ]
    },
    "Weakness": {
        # Weaknesses mirror each area with 12 challenges
        "Operational Excellence": [
            "Inefficient workflows",
            "Process bottlenecks",
            "Slow problem resolution",
            "High operational downtime",
            "Underutilized resources",
            "Weak SOP adherence",
            "Poor cross-functional collaboration",
            "Manual processes prone to errors",
            "Limited process monitoring",
            "Missed deadlines",
            "High operational costs",
            "Difficulty implementing improvements"
        ],
        "Quality Management": [
            "Inconsistent quality standards",
            "Low compliance with regulations",
            "High defect rates",
            "Weak supplier quality oversight",
            "Poor corrective action implementation",
            "Lack of continuous improvement culture",
            "Insufficient quality audits",
            "Low customer satisfaction",
            "Delayed quality issue resolution",
            "Limited quality training",
            "Integration with operations weak",
            "Poor documentation of quality processes"
        ],
        "Risk & Compliance Management": [
            "Reactive risk management",
            "Weak internal controls",
            "Low compliance adherence",
            "High legal exposure",
            "Limited crisis management capability",
            "Ineffective risk assessment",
            "Poor staff awareness of regulations",
            "Delayed response to emerging risks",
            "Low monitoring of risk KPIs",
            "Inconsistent enforcement of policies",
            "Weak fraud prevention",
            "Limited integration of risk into strategy"
        ],
        "Data & Information Management": [
            "Incomplete or inconsistent data",
            "Low data quality and integrity",
            "Dispersed or siloed data systems",
            "Limited data analytics capability",
            "Slow reporting processes",
            "Weak data governance policies",
            "Poor integration across systems",
            "Manual data collection errors",
            "Low adoption of BI tools",
            "Data security vulnerabilities",
            "Non-compliance with privacy regulations",
            "Limited data-driven decision making"
        ],
        "Innovation Development": [
            "Resistance to new ideas",
            "Low rate of innovation adoption",
            "Insufficient R&D resources",
            "Weak ideation processes",
            "Limited cross-functional collaboration",
            "Slow prototyping",
            "Lack of market-aligned innovation",
            "Weak recognition for innovative efforts",
            "Low use of emerging technologies",
            "Limited tracking of innovation outcomes",
            "Poor integration with strategy",
            "Innovation pipeline gaps"
        ],
        "Research & Development": [
            "Insufficient R&D funding",
            "Slow research cycle",
            "Limited collaboration with external partners",
            "Low patent output",
            "Misalignment with market needs",
            "Weak project management in R&D",
            "Underutilized expertise",
            "Limited technology transfer",
            "Low ROI from R&D investments",
            "Gaps in knowledge capture",
            "Slow adoption of research findings",
            "High dependency on external R&D"
        ],
        "Supply Chain & Logistics": [
            "Poor supplier reliability",
            "High inventory carrying costs",
            "Frequent stockouts or overstock",
            "Inefficient logistics operations",
            "Limited supply chain visibility",
            "Slow response to disruptions",
            "Weak vendor relationships",
            "High transportation costs",
            "Lack of sustainability practices",
            "Poor demand forecasting",
            "Limited integration with procurement",
            "Low responsiveness to customer needs"
        ],
        "Project & Program Management": [
            "Missed deadlines",
            "Poor resource allocation",
            "Low stakeholder engagement",
            "Weak risk management",
            "Poorly defined project scope",
            "Low quality project outcomes",
            "High project costs",
            "Weak issue resolution mechanisms",
            "Inconsistent governance",
            "Limited cross-functional coordination",
            "Poor performance tracking",
            "Low project success rates"
        ],
        "Customer Management Process": [
            "Low customer satisfaction",
            "High customer churn",
            "Limited feedback collection",
            "Slow response to complaints",
            "Weak CRM system usage",
            "Poor customer engagement",
            "Lack of tailored solutions",
            "Low account management efficiency",
            "Data-driven insights not used",
            "Poor integration with operations",
            "Limited loyalty programs",
            "Reactive rather than proactive approach"
        ],
        "Internal Audit Control": [
            "Limited audit coverage",
            "Delayed audit reporting",
            "Weak control environment",
            "Inconsistent audit quality",
            "Insufficient risk-based planning",
            "Poor follow-up on audit findings",
            "Weak integration with risk management",
            "Lack of independence in audits",
            "Low accountability culture",
            "Ineffective internal audit communication",
            "Limited audit training",
            "Delayed corrective actions"
        ],
        "Health & Safety Environment": [
            "Frequent accidents or incidents",
            "Poor adherence to safety protocols",
            "Limited safety training",
            "Weak emergency preparedness",
            "Low employee awareness",
            "Inadequate monitoring of safety KPIs",
            "Non-compliance with regulations",
            "Insufficient resources for safety programs",
            "Reactive rather than proactive measures",
            "Limited safety culture",
            "Weak reporting of hazards",
            "Inconsistent safety audits"
        ],
        "Business Continuity & Disaster Recovery": [
            "Incomplete continuity plans",
            "Slow disaster response",
            "Insufficient backup systems",
            "Low testing frequency",
            "Weak cross-functional coordination",
            "High vulnerability to external shocks",
            "Unclear recovery roles",
            "Limited integration with risk management",
            "Delayed communication in crises",
            "Low resilience culture",
            "Resource constraints during disruption",
            "Weak monitoring of continuity KPIs"
        ],
        "Asset & Resource Management": [
            "Poor asset utilization",
            "High downtime or failures",
            "Inefficient resource allocation",
            "Inadequate maintenance schedules",
            "Limited tracking of assets",
            "High inventory wastage",
            "Weak integration with operations",
            "Low ROI on asset investment",
            "Slow response to asset issues",
            "Resource planning gaps",
            "Manual asset management",
            "Insufficient sustainability measures"
        ],
        "Stakeholder Communication & Collaboration": [
            "Poor internal communication",
            "Low stakeholder engagement",
            "Delayed information sharing",
            "Ineffective collaboration tools",
            "Weak feedback mechanisms",
            "Limited participation in decision making",
            "Conflict among stakeholders",
            "Lack of transparency",
            "Poor alignment of interests",
            "Slow issue resolution",
            "Low trust and credibility",
            "Fragmented collaboration culture"
        ],
        "Finance Management": [
            "Poor budgeting and forecasting",
            "Low liquidity management",
            "High operational costs",
            "Weak investment decision-making",
            "Delayed financial reporting",
            "Non-compliance with regulations",
            "Limited integration with strategy",
            "Inefficient cost control",
            "Low ROI on investments",
            "Weak financial risk management",
            "Slow decision-making processes",
            "Fragmented financial data"
        ],
        "Fund Management": [
            "Misallocation of funds",
            "Low return on investments",
            "High fund management risk",
            "Delayed reporting on fund usage",
            "Poor compliance with funding policies",
            "Inefficient fund mobilization",
            "Limited monitoring of fund performance",
            "High dependency on limited sources",
            "Weak governance on fund usage",
            "Slow decision-making in fund allocation",
            "Insufficient risk assessment",
            "Misalignment with organizational goals"
        ],
        "Inventory & Materials Management": [
            "Stock discrepancies",
            "Overstock or stockouts",
            "Poor material forecasting",
            "Slow replenishment cycles",
            "Inefficient warehouse operations",
            "Manual tracking errors",
            "High storage costs",
            "Low supplier coordination",
            "Integration gaps with procurement",
            "Limited analytics usage",
            "Material wastage",
            "Delayed inventory reporting"
        ],
        "Procurement & Vendor Management": [
            "Poor supplier performance",
            "Inefficient procurement processes",
            "High procurement costs",
            "Weak contract management",
            "Non-compliance with procurement policies",
            "Limited risk assessment of vendors",
            "Delayed supplier evaluation",
            "Dependency on few vendors",
            "Slow procurement cycles",
            "Fragmented vendor communication",
            "Lack of transparency in procurement",
            "Weak integration with supply chain"
        ],
        "Policy & Governance": [
            "Unclear policies or guidelines",
            "Low adherence to governance standards",
            "Weak decision-making processes",
            "Delayed policy updates",
            "Insufficient oversight",
            "Weak accountability culture",
            "Poor integration with operations",
            "Inconsistent policy enforcement",
            "Low stakeholder engagement",
            "Limited ethical compliance",
            "Slow response to governance issues",
            "Fragmented policy communication"
        ],
        "Planning & Strategic Management": [
            "Unclear strategic objectives",
            "Poor alignment across units",
            "Limited data-driven planning",
            "Slow adaptation to changes",
            "Weak risk-informed strategy",
            "Inadequate resource allocation",
            "Poor cross-functional coordination",
            "Delayed performance reviews",
            "Weak integration with operations",
            "Limited monitoring of KPIs",
            "Reactive rather than proactive approach",
            "Short-term focus over long-term vision"
        ],
        "Human Resource Management": [
            "High employee turnover",
            "Low engagement levels",
            "Limited training and development",
            "Ineffective performance management",
            "Weak succession planning",
            "Unclear HR policies",
            "Poor alignment with strategy",
            "Limited diversity and inclusion",
            "Inefficient payroll or benefits",
            "Low talent acquisition capability",
            "Insufficient career development",
            "Reactive HR problem-solving"
        ],
        "Technology & Digital Transformation": [
            "Outdated IT infrastructure",
            "Frequent system downtime",
            "Low digital adoption",
            "Manual processes remain",
            "Weak cybersecurity measures",
            "Slow adoption of emerging tech",
            "Limited data-driven insights",
            "Poor integration of digital tools",
            "Low cloud and remote capabilities",
            "Fragmented digital initiatives",
            "Limited process digitalization",
            "Inconsistent tech upgrade planning"
        ],
        "Process Improvement & Lean Management": [
            "Limited continuous improvement culture",
            "Resistance to change",
            "Inefficient waste reduction",
            "Poor standardization of processes",
            "Weak KPI monitoring",
            "Slow implementation of improvements",
            "Low employee engagement in process change",
            "Limited cross-functional teams",
            "Poor integration with operations strategy",
            "Reactive problem-solving culture",
            "Data not used in decisions",
            "Weak feedback loops"
        ],
        "Knowledge Management & Organizational Learning": [
            "Limited knowledge repositories",
            "Weak learning culture",
            "Poor knowledge sharing",
            "Inadequate documentation",
            "Insufficient training programs",
            "Low mentorship opportunities",
            "Slow onboarding",
            "Lessons learned not applied",
            "Knowledge retention issues",
            "Limited use of digital platforms",
            "Fragmented learning processes",
            "Poor collaboration for learning"
        ],
        "Performance Measurement & Reporting": [
            "Unclear KPIs",
            "Delayed performance reporting",
            "Low data accuracy",
            "Weak benchmarking practices",
            "Poor dashboard usage",
            "Misalignment with strategy",
            "Limited review and follow-up",
            "Fragmented accountability",
            "Low transparency of results",
            "Performance gaps not addressed",
            "Slow corrective actions",
            "Inconsistent monitoring practices"
        ],
        "Legal & Regulatory Affairs": [
            "High exposure to legal risks",
            "Non-compliance with regulations",
            "Slow contract review processes",
            "Weak intellectual property protection",
            "Limited monitoring of laws",
            "Poor integration with risk management",
            "Weak dispute resolution mechanisms",
            "Low stakeholder trust in compliance",
            "Limited regulatory awareness",
            "Slow response to legal changes",
            "Fragmented legal governance",
            "Ineffective training for staff"
        ],
        "Change & Transformation Management": [
            "Resistance to change",
            "Low employee adaptability",
            "Poor communication of changes",
            "Weak change leadership",
            "Limited stakeholder engagement",
            "Low integration with strategy",
            "Poor evaluation of change outcomes",
            "Slow response to resistance",
            "Weak methodology adoption",
            "Culture not supportive of transformation",
            "Low tracking of change KPIs",
            "Lessons from past initiatives not applied"
        ],

    },

    # =====================================================
    # OPPORTUNITIES — External Positive Factors
    # =====================================================
    "Opportunity": {
        "Market Expansion & Growth": [
            "Entry into emerging markets",
            "Expansion into adjacent markets",
            "Growing demand in existing segments",
            "Digital marketplaces and e-commerce growth",
            "Globalization and international trade agreements",
            "Rising disposable incomes in target markets",
            "Demographic shifts creating new customer segments",
            "Urbanization trends increasing market density",
            "Market consolidation and acquisition opportunities",
            "New distribution channel development",
            "Cross-border partnerships and joint ventures",
            "Emerging middle-class consumer segments",
            "Service diversification for untapped needs",
            "Expansion of subscription or recurring revenue models",
            "International franchise and licensing opportunities",
            "Expansion via mergers and acquisitions"
        ],
        "Technological Advancements": [
            "Artificial intelligence and machine learning adoption",
            "Internet of Things (IoT) and connected devices",
            "Cloud computing and SaaS adoption",
            "5G and advanced telecommunications infrastructure",
            "Blockchain and distributed ledger applications",
            "Advanced robotics and automation in industry",
            "Big data analytics and predictive modeling",
            "Augmented and virtual reality solutions",
            "Quantum computing emerging applications",
            "Edge computing and decentralized architectures",
            "Digital twin and simulation technologies",
            "Smart sensors and real-time monitoring tools",
            "Cybersecurity technology improvements",
            "Open-source software innovations",
            "Integration with emerging digital ecosystems"
        ],
        "Regulatory & Policy Changes": [
            "Favorable regulatory reforms",
            "Government incentives and tax benefits",
            "Trade agreements and tariff reductions",
            "Environmental and sustainability regulations",
            "Intellectual property protection enhancements",
            "Industry standards and certification requirements",
            "Export promotion and international trade support",
            "R&D tax credits and funding programs",
            "Infrastructure investment programs",
            "Sector-specific stimulus packages",
            "Public policy promoting digital adoption",
            "Labor market and skills development incentives",
            "Subsidies and grants for innovation",
            "Environmental protection incentives",
            "Consumer protection and market transparency regulations"
        ],
        "Customer & Market Trends": [
            "Growing demand for digital and mobile services",
            "Health and wellness focus driving market change",
            "Sustainability and eco-conscious consumer trends",
            "Personalization expectations from consumers",
            "Remote work and digital nomad trends",
            "Experience economy and service expectations",
            "Social media and influencer-driven opportunities",
            "Changing consumer lifestyles",
            "Aging population and silver economy opportunities",
            "Conscious consumerism and ethical purchasing",
            "Community-driven adoption of products/services",
            "Multi-generational and demographic market shifts",
            "Urban-rural migration influencing demand patterns",
            "Cultural trends and lifestyle changes",
            "New consumer expectations from transparency and traceability"
        ],
        "Financial & Capital Opportunities": [
            "Favorable interest rate environment",
            "Venture capital and private equity funding",
            "IPO and public listing opportunities",
            "Debt refinancing at lower rates",
            "Asset sales and portfolio optimization opportunities",
            "Tax incentives for specific sectors",
            "Currency exchange rate advantages",
            "Investment in undervalued external assets",
            "Strategic divestitures and spin-offs in the market",
            "Capital market trends favorable to the sector",
            "Green bonds and sustainable financing initiatives",
            "Alternative and crowd-based funding sources",
            "Government-backed loan programs",
            "Corporate venture funds",
            "Access to international financial markets"
        ],
        "Industry & Competitive Shifts": [
            "Competitor weaknesses and market exits",
            "Industry consolidation opportunities",
            "Technology disruption impacting traditional players",
            "Changing competitive alliances",
            "Reduction in market entry barriers",
            "Emerging new entrants leveraging technology",
            "Industry standard updates creating advantages",
            "Platform and ecosystem shifts in the sector",
            "Emerging consumer segments altering competition",
            "Global market liberalization opportunities",
            "Outsourcing and offshoring trends",
            "Collaborative industry initiatives",
            "Disruptive business models creating new opportunities",
            "Convergence of industries enabling cross-sector growth",
            "Licensing and franchising expansion possibilities"
        ],
        "Environmental & Sustainability Trends": [
            "Growing demand for sustainable products and services",
            "Carbon reduction initiatives and regulations",
            "Circular economy opportunities",
            "Green energy adoption and renewable incentives",
            "ESG investing and sustainability finance trends",
            "Environmental certification and labeling requirements",
            "Climate adaptation and resilience initiatives",
            "Biodiversity and ecosystem protection regulations",
            "Waste reduction and recycling regulations",
            "Public sustainability awareness driving demand",
            "Carbon credit and offset market growth",
            "Natural resource management programs",
            "Corporate sustainability reporting mandates",
            "Eco-friendly consumer product trends",
            "Energy efficiency and carbon footprint reduction incentives"
        ],
        "Geopolitical & Global Trends": [
            "Peace treaties and regional stability",
            "International cooperation and alliances",
            "Global economic integration",
            "Cross-border trade facilitation",
            "Visa and labor mobility agreements",
            "Emerging regional markets",
            "Global sustainability initiatives",
            "Multilateral development programs",
            "International funding and grants",
            "Global standards harmonization",
            "Participation in global summits and forums",
            "Foreign investment incentives",
            "Global infrastructure and development programs",
            "International partnerships for technology transfer",
            "International conflict resolution mechanisms"
        ]
    },

    # =====================================================
    # THREATS — External Negative Factors
    # =====================================================
    "Threat": {
        "Economic & Market Risks": [
            "Global economic recessions and downturns",
            "Inflation and interest rate volatility",
            "Currency fluctuations and exchange rate risks",
            "Stock market volatility affecting funding",
            "Commodity price fluctuations",
            "Trade wars and protectionist policies",
            "Economic sanctions and geopolitical tensions",
            "Reduced consumer confidence",
            "Real estate and property market corrections",
            "Rapidly changing market demand",
            "Market saturation and overcapacity",
            "Global supply-demand imbalances",
            "Unexpected foreign investment withdrawals",
            "Sector-specific economic downturns",
            "Recessionary pressures on purchasing power"
        ],
        "Competitive Pressures": [
            "New market entrants and disruptive competitors",
            "Aggressive pricing and price wars",
            "Product or service imitation",
            "Competitor mergers and acquisitions",
            "Foreign competition and global players",
            "Technology disruption by competitors",
            "Loss of market differentiation",
            "Competitor alliances affecting market share",
            "Competitor marketing and branding campaigns",
            "Emerging platform and ecosystem competitors",
            "Low-cost foreign competitors",
            "Rapid innovation by competitors",
            "Unfair competitive practices in market",
            "Market consolidation affecting positioning",
            "Competitor IP or patent challenges"
        ],
        "Technological Disruption": [
            "Rapid technology obsolescence",
            "Cybersecurity threats and data breaches",
            "Infrastructure failures impacting service delivery",
            "Competitors advancing digital transformation faster",
            "Emerging automation and AI impacting market expectations",
            "Vendor or platform dependency risks",
            "Data privacy and regulatory compliance pressures",
            "Technology skill shortages in the external market",
            "System integration and compatibility challenges",
            "Legacy system obsolescence in the market",
            "Platform or software vulnerabilities",
            "Disruptive emerging technologies",
            "Open-source vulnerabilities",
            "Third-party technology dependency",
            "Rapid adoption of disruptive tech by competitors"
        ],
        "Regulatory & Compliance Challenges": [
            "Changing regulations and increased compliance costs",
            "Environmental regulations and carbon pricing",
            "Data protection and privacy laws (GDPR, CCPA, etc.)",
            "Product safety and liability laws",
            "Labor and employment law changes",
            "International trade regulations and tariffs",
            "Industry-specific compliance obligations",
            "Legal disputes or litigation risks",
            "Antitrust and competition law scrutiny",
            "Import/export restrictions or embargoes",
            "Mandatory reporting and disclosure regulations",
            "Tax regulation changes",
            "Government policy instability",
            "Licensing and permit changes",
            "Cross-border regulatory misalignment"
        ],
        "Supply Chain & Operational Risks": [
            "Global supply chain disruptions",
            "Supplier concentration and dependency risks",
            "Raw material shortages and price volatility",
            "Logistics and transportation challenges",
            "Natural disasters and climate events",
            "Political instability in operating regions",
            "Pandemics or public health crises",
            "Energy supply volatility and outages",
            "Infrastructure or transport failures",
            "Third-party vendor or partner risks",
            "Border and customs delays",
            "Port congestion and shipping bottlenecks",
            "Tariffs or trade barriers",
            "Cyberattacks on supply chain",
            "Environmental impacts on production inputs"
        ],
        "Environmental & Climate Risks": [
            "Extreme weather events",
            "Sea level rise and coastal flooding",
            "Water scarcity and resource limitations",
            "Biodiversity loss and ecosystem degradation",
            "Carbon tax or emissions trading costs",
            "Climate regulation and reporting obligations",
            "Physical asset damage due to climate events",
            "Supply chain disruption from environmental factors",
            "Reputation risks from environmental impact",
            "Transition risks to low-carbon economy",
            "Natural resource depletion",
            "Deforestation or soil degradation",
            "Wildfires and forest management risks",
            "Ocean acidification and water pollution",
            "Extreme temperature fluctuations affecting operations"
        ],
        "Geopolitical & Global Threats": [
            "Geopolitical conflicts and trade disputes",
            "Terrorism and security threats",
            "Nationalization or government intervention",
            "Intellectual property theft",
            "Partner or supplier failures externally",
            "Global health crises or pandemics",
            "Political regime changes impacting operations",
            "International sanctions or embargoes",
            "Regional instability affecting market access",
            "Cross-border legal disputes",
            "Civil unrest or insurgencies",
            "Military conflicts in key markets",
            "Diplomatic tensions affecting trade",
            "Expropriation or property seizure risks",
            "Economic nationalism affecting foreign operations"
        ]
    },

}
