from management_project.services.strategy_hierarchy.finance_perspective import GENERIC_FINANCE_PERSPECTIVE
from management_project.services.strategy_hierarchy.customer_perspective import GENERIC_CUSTOMER_PERSPECTIVE

ICT_PERSPECTIVE = {
    "Financial Perspective": {

        **GENERIC_FINANCE_PERSPECTIVE['Financial Perspective'],

          # ==================== 1. Startup & Entrepreneurship Support ====================
        "Startup & Entrepreneurship Support": {

            "Support ICT startups and new ventures": {
                "Startup funding support ($)": "Funding and grants allocated to ICT startups",
                "Number of active startups (#)": "Operational ICT startups",
                "Jobs created by startups (#)": "Employment generated by startups",
                "Spin-off company creation (#)": "New companies spun from research"
            },
            "Strengthen entrepreneurial ecosystem": {
                "Hackathon/innovation challenge participation (#)": "Participants in ICT events",
                "Regional tech cluster growth (#)": "Number of ICT clusters established",
                "Innovation awards won (#)": "Awards for innovative solutions",
                "Partnership agreements (#)": "Public-private partnerships signed"
            },
            "Support digital entrepreneurship education": {
                "ICT entrepreneurship courses offered (#)": "Number of courses provided",
                "Enrollment in entrepreneurship programs (#)": "Participants enrolled",
                "Completion rate of entrepreneurship programs (%)": "(Completed / Enrolled) * 100",
                "Entrepreneurship skill assessment improvement (%)": "((Post-pre)/Pre)*100"
            },
            "Promote startup incubators and accelerators": {
                "Incubator programs (#)": "Number of incubator programs established",
                "Accelerator programs (#)": "Number of accelerator programs running",
                "Startups supported (#)": "Startups receiving support",
                "Startup graduation rate (%)": "(Graduated / Total startups) * 100"
            },
            "Enhance mentorship and advisory services": {
                "Mentorship programs (#)": "Number of mentorship initiatives",
                "Startups with mentors (#)": "Startups assigned mentors",
                "Mentorship satisfaction score (1–5)": "Average rating",
                "Advisor engagement rate (%)": "(Active advisors / Total mentors) * 100"
            },
            "Foster networking and knowledge sharing": {
                "Networking events (#)": "ICT networking events conducted",
                "Participants in networking events (#)": "Total participants",
                "Collaborative projects initiated (#)": "Projects started via networking",
                "Knowledge exchange satisfaction (1–5)": "Average participant rating"
            },
            "Support regulatory and policy guidance": {
                "Policy workshops conducted (#)": "Number of workshops for startups",
                "Startups compliant with regulations (%)": "Compliant startups / Total startups * 100",
                "Regulatory guidance materials (#)": "Guides, toolkits, manuals provided",
                "Policy feedback adoption rate (%)": "(Implemented feedback / Total feedback) * 100"
            },
            "Promote gender and social inclusion in startups": {
                "Women-led startups (#)": "Number of women-led startups",
                "Startups supporting underrepresented groups (#)": "Number of inclusive startups",
                "Inclusive training sessions (#)": "Number of targeted training sessions",
                "Inclusion participation rate (%)": "(Participants from underrepresented groups / Total participants) * 100"
            },
        },

        # ==================== 2. ICT Economy Growth ====================
        "ICT Economy Growth": {

            "Promote innovation commercialization": {
                "Innovation commercialization revenue ($)": "Revenue from commercialized innovations",
                "New technology patent registrations (#)": "Number of patents filed",
                "Product prototype development (#)": "Number of prototypes developed",
                "Startup mentorship participation (#)": "Number of startups in mentoring programs"
            },
            "Encourage venture capital and investments": {
                "Venture capital investment ($)": "Capital invested in ICT ventures",
                "Incubator/accelerator program revenue ($)": "Revenue from support programs",
                "Number of investment rounds (#)": "Funding rounds completed by startups",
                "Investor participation rate (%)": "(Active investors / Total potential investors) * 100"
            },
            "Foster R&D for startups": {
                "R&D projects initiated (#)": "Number of ICT R&D projects",
                "R&D funding support ($)": "Funds allocated to R&D initiatives",
                "Patents filed from R&D (#)": "Number of patents generated from R&D",
                "Prototype commercialization rate (%)": "(Prototypes commercialized / Total prototypes) * 100"
            },
            "Promote collaborative innovation": {
                "Public-private co-innovation projects (#)": "Number of joint innovation projects",
                "Industry-academia partnerships (#)": "Number of collaboration agreements",
                "Open innovation platform usage (#)": "Number of users submitting ideas",
                "Co-created solutions deployed (#)": "Number of solutions implemented"
            },
            "Scale successful startups": {
                "Revenue growth (%)": "((Current - Previous)/Previous) * 100",
                "Jobs created by scaling startups (#)": "Employment from scaled startups",
                "Market expansion initiatives (#)": "New markets entered by startups",
                "Export revenue ($)": "Revenue from international markets"
            },
            "Promote digital product adoption": {
                "New user acquisition (#)": "Users adopting new digital solutions",
                "Usage frequency per user": "Average logins per user",
                "Retention rate (%)": "(Users retained / Total new users) * 100",
                "Customer satisfaction with products (%)": "Average rating"
            },
            "Support ICT service commercialization": {
                "ICT service revenue ($)": "Revenue from ICT services",
                "Number of service clients (#)": "Clients using commercial services",
                "Contract renewal rate (%)": "(Renewed contracts / Total contracts) * 100",
                "Service quality score (1–5)": "Average rating"
            },
            "Encourage ICT entrepreneurship exports": {
                "Export revenue ($)": "Revenue from exported ICT products/services",
                "Export-oriented startups (#)": "Startups targeting international markets",
                "International partnerships (#)": "Cross-border partnerships signed",
                "Market penetration (%)": "(Users acquired internationally / Target users) * 100"
            },
        },

        # ==================== 3. ICT Economic Development ====================
        "ICT Economic Development": {

            "Measure and scale startup impact": {
                "Revenue growth of startups (%)": "((Current revenue - Previous revenue)/Previous revenue) * 100",
                "Jobs created by scaled startups (#)": "Total employment from scaling startups",
                "Export revenue from ICT startups ($)": "Revenue generated from international markets",
                "Market expansion initiatives (#)": "New markets entered by startups"
            },
            "Promote Digital Inclusion": {
                "Broadband access expansion ($)": "Investment in broadband networks and infrastructure",
                "Mobile network coverage (%)": "Population covered by mobile networks",
                "Rural connectivity revenue ($)": "Revenue from rural connectivity initiatives",
                "Internet penetration rate (%)": "(Internet users / Total population) * 100"
            },
            "Improve digital literacy": {
                "Digital literacy program funding ($)": "Funding allocated to digital literacy programs",
                "ICT literacy training completion (%)": "Participants completing ICT literacy programs",
                "Public digital training sessions (#)": "Number of training sessions conducted",
                "Gender digital inclusion ratio (%)": "(Female ICT users / Total users) * 100"
            },
            "Increase access to affordable devices": {
                "Affordable device program funding ($)": "Funding for low-cost devices distribution",
                "Number of devices distributed (#)": "Total devices distributed to users",
                "Device adoption rate (%)": "Users actively using distributed devices",
                "Device functionality uptime (%)": "Average functionality of distributed devices"
            },
            "Foster ICT employment and GDP growth": {
                "ICT sector employment (#)": "Number of jobs in ICT sector",
                "ICT contribution to GDP (%)": "ICT sector value / Total GDP * 100",
                "Startup-driven GDP contribution (%)": "Revenue contribution from startups / Total GDP * 100",
                "Job creation rate (%)": "((Current jobs - Previous jobs)/Previous jobs) * 100"
            },
            "Encourage regional ICT hubs": {
                "Number of ICT hubs (#)": "Regional technology hubs established",
                "Startup density per hub (#)": "Startups located per hub",
                "Hub revenue ($)": "Revenue generated by regional hubs",
                "Hub job creation (#)": "Jobs generated in ICT hubs"
            },
            "Promote ICT exports and trade": {
                "Export revenue ($)": "Revenue from exported ICT products/services",
                "Number of exporting startups (#)": "Startups selling internationally",
                "Market penetration (%)": "International users / Total target users * 100",
                "Trade partnerships (#)": "Number of international agreements signed"
            },
            "Support sustainable ICT investment": {
                "Total ICT investment ($)": "Capital invested in ICT infrastructure and startups",
                "Private sector ICT investment ($)": "Private contributions to ICT",
                "Public ICT investment ($)": "Government spending on ICT development",
                "ROI of ICT investments (%)": "(Benefits / Costs) * 100"
            },
        },

        # ==================== 2. ICT Infrastructure & Asset Finance ====================
        "ICT Infrastructure & Asset Finance": {
            "Modernize Data Centers": {
                "Data center modernization investment ($)": "Capital spent on upgrading facilities",
                "Server upgrade ratio (%)": "Upgraded servers / Total servers * 100",
                "Cooling system efficiency (%)": "Energy efficiency of data center cooling",
                "Power usage effectiveness (PUE)": "Total facility energy / IT equipment energy"
            },
            "Upgrade Network Infrastructure": {
                "Network infrastructure investment ($)": "Spending on network devices and cabling",
                "Bandwidth expansion (%)": "Increase in network capacity / Previous capacity * 100",
                "Latency reduction (%)": "Improvement in network response time",
                "Network coverage expansion (%)": "New areas connected / Planned expansion * 100"
            },
            "Enhance Cloud & Virtual Platforms": {
                "Cloud platform upgrade investment ($)": "Capital for cloud systems modernization",
                "Cloud service utilization rate (%)": "Used cloud resources / Total provisioned resources * 100",
                "Cloud migration completion (%)": "Percentage of systems migrated to cloud",
                "Cloud cost efficiency ($/unit)": "Cost per cloud resource unit used"
            },
            "Modernize ICT Equipment & Endpoints": {
                "Workstation and device upgrade ratio (%)": "Upgraded devices / Total devices * 100",
                "IT peripheral replacement investment ($)": "Capital spent on peripherals (printers, monitors, etc.)",
                "Endpoint security compliance (%)": "Devices compliant with security standards",
                "Device lifecycle adherence (%)": "Devices replaced within recommended lifecycle"
            },
            "Optimize ICT Asset Utilization": {
                "Server utilization rate (%)": "Hours used / Available hours * 100",
                "Network equipment uptime (%)": "Operational time / Total time * 100",
                "Cloud resource optimization (%)": "Used vs allocated cloud resources",
                "IT asset ROI ($)": "Revenue or cost savings per IT asset"
            },
            "Enhance ICT Technology Adoption": {
                "Enterprise software ROI (%)": "Benefits from software adoption / Cost * 100",
                "Cybersecurity investment ($)": "Spending on IT security infrastructure",
                "Digital platform adoption (%)": "Users utilizing digital platforms / Total users * 100",
                "Automation implementation rate (%)": "Automated processes / Total processes * 100"
            },
            "Preventive Maintenance & Lifecycle Management": {
                "IT maintenance compliance (%)": "Maintained devices / Total devices * 100",
                "Hardware replacement cycle (years)": "Average lifespan of ICT hardware",
                "Software update compliance (%)": "Systems updated / Total systems * 100",
                "Maintenance cost per asset ($)": "Total maintenance spend / Number of assets"
            },
            "Improve ICT Operational Efficiency": {
                "Cost per IT service ($)": "Total IT costs / Number of services provided",
                "IT support resolution time (hrs)": "Average time to resolve support tickets",
                "Process automation efficiency (%)": "Tasks automated / Total tasks * 100",
                "Service downtime reduction (%)": "Decrease in downtime vs previous period"
            },
            "Manage ICT Risk & Compliance": {
                "Data privacy compliance (%)": "Systems compliant with regulations",
                "IT security incident rate": "Number of incidents / Total systems",
                "Business continuity readiness (%)": "Preparedness for operational disruptions",
                "Regulatory audit success (%)": "Passed audits / Total audits * 100"
            },
            "Long-term ICT Sustainability & Investment": {
                "ICT strategic investment ROI (%)": "Return on long-term ICT investments",
                "Emerging technology adoption (%)": "New technologies implemented / Planned",
                "ICT operational sustainability ($)": "Cost savings from sustainable IT practices",
                "Innovation pipeline growth (%)": "New ICT initiatives / Total pipeline"
            }
        },
    },

    "Customer Perspective": {

        # ---------------- GENERIC CUSTOMER PERSPECTIVE ----------------
        **GENERIC_CUSTOMER_PERSPECTIVE['Customer Perspective'],
        # =========================================================
        # 1. Digital Citizen Service Access / Digital Service Access
        # =========================================================
        "Digital Citizen Service Access": {
            "Ensure high availability of e-services": {
                "Service uptime (%)": "(Available hours / Total hours) * 100",
                "Downtime incidents per month": "Number of downtime events",
                "Average downtime duration (minutes)": "Sum(downtime) / Number of incidents",
                "SLA compliance (%)": "(Services meeting SLA / Total services) * 100",
            },
            "Expand access to remote and underserved populations": {
                "Coverage of public digital services (%)": "(Population with access / Total population) * 100",
                "Rural user access rate (%)": "(Rural users accessing services / Total rural population) * 100",
                "Digital access points per 10,000 population": "Total digital kiosks / Population * 10,000",
                "Public Wi-Fi coverage (%)": "(Covered areas / Total areas) * 100",
            },
            "Enable multi-channel access": {
                "Web access rate (%)": "(Users accessing via web / Total users) * 100",
                "Mobile access rate (%)": "(Users accessing via mobile / Total users) * 100",
                "Offline service utilization (%)": "(Offline service users / Total users) * 100",
                "Cross-platform satisfaction score (1–5)": "Average rating",
            },
            "Increase service inclusivity": {
                "Accessibility compliance (%)": "(Accessible services / Total services) * 100",
                "Users with disabilities served (%)": "(Served users / Total users with disabilities) * 100",
                "Low-bandwidth user satisfaction (%)": "(Satisfied low-bandwidth users / Total) * 100",
                "Language coverage (%)": "(Supported languages / Total required languages) * 100",
            },
            # Added: older Digital Service Access objectives
            "Ensure high system availability": {
                "Service availability (%)": "(Available hours / Total hours) * 100",
                "System uptime (%)": "(Uptime minutes / Total minutes) * 100",
                "Downtime incidents per month": "Number of downtime events",
                "Average downtime duration (minutes)": "Sum(downtime) / Number of incidents",
            },
            "Improve login and authentication experience": {
                "Successful login rate (%)": "(Successful logins / Total login attempts) * 100",
                "Failed login attempts (%)": "(Failed logins / Total login attempts) * 100",
                "Multi-factor authentication adoption (%)": "(Users using MFA / Total users) * 100",
                "Average login time (seconds)": "Total login time / Total login attempts",
            },
            "Enhance cross-platform accessibility": {
                "Mobile access rate (%)": "(Mobile logins / Total logins) * 100",
                "Web access rate (%)": "(Web logins / Total logins) * 100",
                "App crash rate (%)": "(Crashes / Total app sessions) * 100",
                "Browser compatibility satisfaction (%)": "Average user rating",
            },
            "Expand service coverage for all users": {
                "Population coverage (%)": "(Users with access / Total target users) * 100",
                "Geographical coverage (%)": "(Regions covered / Total regions) * 100",
                "Peak load handling (%)": "(Peak requests handled / Total peak requests) * 100",
                "Service reach improvement (%)": "((Current reach - Previous reach)/Previous reach)*100",
            },
            "Increase 24/7 service availability": {
                "Nighttime uptime (%)": "(Available hours at night / Total night hours) * 100",
                "Weekend uptime (%)": "(Available hours on weekend / Total weekend hours) * 100",
                "Off-hour support response time (minutes)": "Average response time",
                "Critical service SLA compliance (%)": "(SLAs met / Total SLAs) * 100",
            },
            "Enhance digital inclusivity": {
                "Access for persons with disabilities (%)": "(Accessible services / Total services) * 100",
                "Support for low-bandwidth users (%)": "(Users able to access / Total users) * 100",
                "Accessibility feedback score (1–5)": "Average rating",
                "Digital divide reduction (%)": "((Previous gap - Current gap)/Previous gap)*100",
            },
        },

        # =========================================================
        # 2. Citizen / User Support and Satisfaction
        # =========================================================
        "Citizen Support and Engagement": {
            "Enhance helpdesk responsiveness": {
                "Average response time (hours)": "Sum(response times) / Total queries",
                "SLA compliance (%)": "(Queries resolved within SLA / Total queries) * 100",
                "First-contact resolution (%)": "(Resolved on first contact / Total queries) * 100",
                "Citizen satisfaction (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Improve digital feedback systems": {
                "Feedback collected (%)": "(Feedback received / Total users) * 100",
                "Average resolution time (hours)": "Sum(time to resolve) / Total feedback",
                "Implemented citizen suggestions (%)": "(Implemented / Total suggestions) * 100",
                "User engagement score (1–5)": "Average rating",
            },
            "Support citizen education and awareness": {
                "Digital literacy program participation (%)": "(Participated / Target population) * 100",
                "Training completion rate (%)": "(Completed / Enrolled) * 100",
                "Awareness campaign reach (%)": "(Reached / Target population) * 100",
                "Post-training comprehension (%)": "((Post-pre)/Pre)*100",
            },
            "Ensure transparency in public services": {
                "Information availability (%)": "(Published info / Total required) * 100",
                "Citizen trust score (1–5)": "Average rating",
                "Response to citizen inquiries (%)": "(Responded / Total inquiries) * 100",
                "Public portal satisfaction (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Promote citizen participation": {
                "Participation in e-polls and surveys (%)": "(Participants / Total target population) * 100",
                "Number of co-created initiatives": "Count",
                "User satisfaction with participatory initiatives (%)": "(Satisfied / Total participants) * 100",
                "Suggestions adopted (%)": "(Implemented / Total suggestions) * 100",
            },
            # Added: User Support and Satisfaction objectives
            "Reduce support ticket resolution time": {
                "Average ticket resolution time (hours)": "Sum(time to resolve) / Total tickets",
                "First-contact resolution rate (%)": "(Resolved first contact / Total tickets) * 100",
                "Support backlog (%)": "(Pending tickets / Total tickets) * 100",
                "User satisfaction with support (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Improve helpdesk responsiveness": {
                "Average initial response time (minutes)": "Sum(response times) / Total tickets",
                "SLA compliance rate (%)": "(Tickets resolved within SLA / Total tickets) * 100",
                "Support agent availability (%)": "(Available agents / Total agents) * 100",
                "Escalation rate (%)": "(Escalated tickets / Total tickets) * 100",
            },
            "Enhance self-service capabilities": {
                "Knowledge base usage (%)": "(Users using KB / Total users) * 100",
                "Self-service resolution rate (%)": "(Resolved via self-service / Total issues) * 100",
                "Help article satisfaction (%)": "(Positive ratings / Total ratings) * 100",
                "Average search success rate (%)": "(Successful searches / Total searches) * 100",
            },
            "Support multi-language users": {
                "Multilingual support coverage (%)": "(Supported languages / Total required languages) * 100",
                "User satisfaction for non-native speakers (%)": "(Satisfied / Total surveyed) * 100",
                "Interpreter service utilization (%)": "(Used / Total requested) * 100",
                "Average response time for multilingual support (minutes)": "Sum(response times) / Total requests",
            },
            "Improve feedback loops": {
                "Feedback collected (%)": "(Feedback received / Total users) * 100",
                "Average response time to feedback (hours)": "Sum(response times) / Total feedback",
                "Implemented suggestions (%)": "(Implemented / Total suggestions) * 100",
                "User engagement in feedback programs (%)": "(Participants / Total users) * 100",
            },
            "Enhance personalization of support": {
                "Personalized response rate (%)": "(Personalized responses / Total responses) * 100",
                "Customer satisfaction with personalization (%)": "(Satisfied / Total surveyed) * 100",
                "Profile-based recommendations usage (%)": "(Users using recommendations / Total users) * 100",
                "Reduction in repeat tickets due to personalization (%)": "((Previous - Current)/Previous)*100",
            },
            "Increase overall user satisfaction": {
                "Overall satisfaction (%)": "(Satisfied / Total surveyed) * 100",
                "Net Promoter Score (NPS)": "Promoters - Detractors",
                "Repeat complaint rate (%)": "(Repeat complaints / Total complaints) * 100",
                "User engagement score (1–5)": "Average rating",
            },
        },

        # =========================================================
        # 3. Digital Literacy and Training / Adoption
        # =========================================================
        "Digital Literacy and Adoption": {
            "Increase citizen proficiency in digital services": {
                "Digital literacy improvement (%)": "((Post-pre)/Pre)*100",
                "Skill assessment pass rate (%)": "(Passed / Total assessed) * 100",
                "Self-reported confidence (%)": "(Confident users / Total surveyed) * 100",
                "Average competency score (1–5)": "Average rating",
            },
            "Promote onboarding of new users": {
                "New user registration (%)": "(Registered / Target population) * 100",
                "Orientation completion rate (%)": "(Completed / Total new users) * 100",
                "Time to full adoption (days)": "Average days to adopt services",
                "Dropout rate during onboarding (%)": "(Dropped / Total new users) * 100",
            },
            "Support continuous learning": {
                "Number of digital training sessions": "Count",
                "Average training satisfaction score (1–5)": "Average rating",
                "Repeat training participation (%)": "(Users repeating / Total users) * 100",
                "Skills gap reduction (%)": "((Previous gap - Current gap)/Previous gap)*100",
            },
            "Encourage innovation adoption": {
                "New service adoption (%)": "(Users using new service / Total users) * 100",
                "Retention rate of new service users (%)": "(Retained / Total new users) * 100",
                "User satisfaction with new services (%)": "(Satisfied / Total surveyed) * 100",
                "Pilot participation (%)": "(Users participating in pilot / Total target users) * 100",
            },
            # Added: Digital Literacy and Training objectives
            "Enhance user training completion": {
                "Training completion rate (%)": "(Completed / Enrolled) * 100",
                "Average training score": "Sum(scores)/Total participants",
                "Time to complete training (hours)": "Average hours per participant",
                "Training attendance rate (%)": "(Attended / Invited) * 100",
            },
            "Increase digital proficiency": {
                "Digital proficiency improvement (%)": "((Post-pre)/Pre)*100",
                "User confidence score (1–5)": "Average rating",
                "Skill assessment pass rate (%)": "(Passed / Total assessed) * 100",
                "Self-reported competency (%)": "(Users confident / Total surveyed) * 100",
            },
            "Promote awareness of digital tools": {
                "User adoption of tools (%)": "(Active users / Total target users) * 100",
                "Engagement rate (%)": "(Users interacting with tools / Total active users) * 100",
                "Training feedback score (1–5)": "Average rating",
                "Usage frequency per month": "Average number of logins per user",
            },
            "Support onboarding of new users": {
                "New user orientation completion (%)": "(Completed / Total new users) * 100",
                "Average onboarding satisfaction (1–5)": "Average rating",
                "Time to full productivity (days)": "Average days for users to reach proficiency",
                "Dropout rate during onboarding (%)": "(Dropped / Total new users) * 100",
            },
            "Monitor digital skill gaps": {
                "Skill gap assessment coverage (%)": "(Assessed / Total users) * 100",
                "Improvement in gap score (%)": "((Previous gap - Current gap)/Previous gap)*100",
                "Targeted training participation (%)": "(Trained / Total identified) * 100",
                "Reduction in support tickets due to skill gaps (%)": "((Previous tickets - Current tickets)/Previous tickets)*100",
            },
        },

        # =========================================================
        # 4. Innovation and New Service Adoption / Service Quality
        # =========================================================
        "Customer Digital Service Innovation & Quality": {
            "Improve e-service quality": {
                "System response time (seconds)": "Average response",
                "Error rate (%)": "(Errors / Total transactions) * 100",
                "User satisfaction score (1–5)": "Average rating",
                "Service level compliance (%)": "(Compliant services / Total services) * 100",
            },
            "Support continuous improvement": {
                "Number of process improvements implemented": "Count",
                "Citizen engagement in improvements (%)": "(Participating citizens / Total target) * 100",
                "Average feedback implementation (%)": "(Implemented suggestions / Total feedback) * 100",
                "Satisfaction with improvements (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Encourage co-creation and participation": {
                "Participatory initiatives (%)": "(Users involved / Total target) * 100",
                "Number of citizen-driven innovations": "Count",
                "Adoption of citizen suggestions (%)": "(Implemented / Total suggestions) * 100",
                "User satisfaction with co-created services (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Promote sustainability and inclusivity": {
                "Repeat usage rate (%)": "(Active users / Total users) * 100",
                "Reduction in abandoned services (%)": "((Previous abandoned - Current)/Previous)*100",
                "Accessibility satisfaction (%)": "(Satisfied / Total surveyed) * 100",
                "Service coverage growth (%)": "((Current - Previous)/Previous)*100",
            },
            # Added: Innovation and New Service Adoption objectives
            "Increase adoption of new digital services": {
                "New service adoption rate (%)": "(Users using new service / Total users) * 100",
                "User engagement with new service (%)": "(Active users / Total users) * 100",
                "Retention rate of new service users (%)": "(Users retained / Total new users) * 100",
                "Feedback score for new services (1–5)": "Average rating",
            },
            "Encourage early adopters participation": {
                "Early adopter engagement (%)": "(Active early adopters / Total target) * 100",
                "Number of pilot participants": "Count of users in pilot programs",
                "Feedback implemented (%)": "(Implemented suggestions / Total feedback) * 100",
                "Satisfaction of pilot users (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Promote co-creation with users": {
                "User-driven feature requests (%)": "(Implemented requests / Total requests) * 100",
                "User involvement in design (%)": "(Users involved / Total projects) * 100",
                "Number of co-created solutions": "Count",
                "User satisfaction with co-created solutions (%)": "(Satisfied / Total users) * 100",
            },
            "Enhance awareness of digital innovations": {
                "Digital innovation awareness (%)": "(Users aware / Total users) * 100",
                "Participation in innovation webinars (%)": "(Participants / Total invited) * 100",
                "Knowledge improvement from sessions (%)": "((Post-pre)/Pre)*100",
                "User feedback score (1–5)": "Average rating",
            },
            "Promote sustainable digital adoption": {
                "User retention rate (%)": "(Retained users / Total users) * 100",
                "Repeat usage rate (%)": "(Users repeatedly using / Total users) * 100",
                "Satisfaction with sustainability initiatives (%)": "(Satisfied / Total surveyed) * 100",
                "Reduction in abandoned services (%)": "((Previous abandoned - Current)/Previous)*100",
            },
        },

        # =========================================================
        # 5. Security and Privacy / Security, Privacy, and Trust
        # =========================================================
        "Security, Privacy, and Trust": {
            "Enhance data protection": {
                "Data breach incidents": "Count",
                "Compliance with privacy regulations (%)": "(Compliant processes / Total) * 100",
                "Encryption adoption rate (%)": "(Encrypted data / Total sensitive data) * 100",
                "User-reported privacy concerns (%)": "(Concerns / Total users) * 100",
            },
            "Improve account and authentication security": {
                "Multi-factor authentication adoption (%)": "(Users using MFA / Total users) * 100",
                "Strong password compliance (%)": "(Strong passwords / Total accounts) * 100",
                "Account compromise incidents": "Count",
                "User satisfaction with security (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Ensure secure communication": {
                "Secure portal messaging adoption (%)": "(Encrypted messages / Total messages) * 100",
                "Data transfer encryption (%)": "(Encrypted transfers / Total transfers) * 100",
                "Unauthorized access incidents": "Count",
                "Citizen confidence score (1–5)": "Average rating",
            },
            "Build transparency and trust": {
                "Privacy policy awareness (%)": "(Aware / Total users) * 100",
                "Response time to security incidents (hours)": "Average time",
                "Compliance audits per year": "Count",
                "Trust score improvement (%)": "((Current - Previous)/Previous)*100",
            },
            # Added: Security and Privacy objectives
            "Enhance user data protection": {
                "Data breach incidents": "Count of breaches",
                "Compliance with data protection standards (%)": "(Compliant processes / Total processes) * 100",
                "User-reported privacy concerns (%)": "(Concerns / Total users) * 100",
                "Encryption adoption rate (%)": "(Encrypted data / Total sensitive data) * 100",
            },
            "Improve account security": {
                "Password strength compliance (%)": "(Strong passwords / Total accounts) * 100",
                "Two-factor authentication adoption (%)": "(2FA enabled / Total users) * 100",
                "Account compromise incidents": "Count",
                "Security training completion (%)": "(Trained staff / Total staff) * 100",
            },
            "Enhance secure communication": {
                "Secure messaging adoption (%)": "(Secure messages / Total messages) * 100",
                "Data transfer encryption (%)": "(Encrypted transfers / Total transfers) * 100",
                "Unauthorized access incidents": "Count",
                "User satisfaction with security (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Increase transparency and trust": {
                "Privacy policy awareness (%)": "(Users aware / Total users) * 100",
                "User trust score (1–5)": "Average rating",
                "Incident reporting response time (hours)": "Average time to respond",
                "Compliance audit frequency": "Number of audits per year",
            },
        },
    },
}
