from management_project.services.strategy_hierarchy.finance_perspective import GENERIC_FINANCE_PERSPECTIVE

ICT_PERSPECTIVE = {
    "Financial Perspective": {
        **GENERIC_FINANCE_PERSPECTIVE['Financial Perspective'],

# ==================== 1. ICT Economic Development ====================
        "ICT Economic Development": {
            "Promote Digital Inclusion": {
                "Expand broadband and mobile coverage": {
                    "Broadband access expansion ($)": "Investment in broadband networks and infrastructure",
                    "Mobile network coverage (%)": "Population covered by mobile networks",
                    "Rural connectivity revenue ($)": "Revenue from rural connectivity initiatives",
                    "Internet penetration rate (%)": "Internet users / Total population * 100"
                },
                "Improve digital literacy": {
                    "Digital literacy program funding ($)": "Funding allocated to digital literacy programs",
                    "ICT literacy training completion (%)": "Participants completing ICT literacy programs",
                    "Public digital training sessions (#)": "Number of training sessions conducted",
                    "Gender digital inclusion ratio (%)": "Female ICT users / Total users * 100"
                },
                "Increase access to affordable devices": {
                    "Affordable device program funding ($)": "Funding for low-cost devices distribution",
                    "Number of devices distributed (#)": "Total devices distributed to users",
                    "Device adoption rate (%)": "Users actively using distributed devices",
                    "Device functionality uptime (%)": "Average functionality of distributed devices"
                },
                "Enhance public digital services adoption": {
                    "Digital service adoption (%)": "Users actively using online government/e-services",
                    "Mobile app downloads (#)": "Number of downloads of official ICT apps",
                    "Online payment adoption (%)": "Users paying online / Total population * 100",
                    "Citizen service feedback score": "Average rating of digital services"
                }
            },
            "Foster Innovation & Entrepreneurship": {
                "Support ICT startups and new ventures": {
                    "Startup funding support ($)": "Funding and grants for ICT startups",
                    "Number of active startups (#)": "Operational ICT startups",
                    "Jobs created by startups (#)": "Employment generated by startups",
                    "Spin-off company creation (#)": "New companies spun from research"
                },
                "Promote innovation commercialization": {
                    "Innovation commercialization revenue ($)": "Revenue from commercialized innovations",
                    "New technology patent registrations (#)": "Number of patents filed",
                    "Product prototype development (#)": "Number of prototypes developed",
                    "Startup mentorship participation (#)": "Number of startups in mentoring programs"
                },
                "Encourage venture capital and investments": {
                    "Venture capital investment ($)": "Capital invested in ICT ventures",
                    "Incubator/accelerator program revenue ($)": "Revenue from support programs",
                    "Number of investment rounds (#)": "Funding rounds completed by startups",
                    "Investor participation rate (%)": "Active investors / Total potential investors * 100"
                },
                "Strengthen entrepreneurial ecosystem": {
                    "Hackathon/innovation challenge participation (#)": "Participants in events",
                    "Regional tech cluster growth (#)": "Number of ICT clusters established",
                    "Innovation awards won (#)": "Awards for innovative solutions",
                    "Partnership agreements (#)": "Public-private partnerships signed"
                }
            },
            "Enhance ICT Workforce Development": {
                "Upskill ICT professionals": {
                    "ICT training investment ($)": "Funds allocated to training and upskilling",
                    "Certification completion rate (%)": "Certifications completed / Enrolled * 100",
                    "Skilled workforce growth (%)": "Increase in qualified ICT staff",
                    "ICT leadership training (#)": "Executives trained in ICT management"
                },
                "Promote employment opportunities in ICT": {
                    "Employment in ICT sector (#)": "New ICT jobs created",
                    "ICT internship programs (#)": "Number of internships offered",
                    "ICT graduate hiring rate (%)": "ICT graduates employed in sector",
                    "Remote work enablement (%)": "Employees with remote ICT capabilities"
                },
                "Support continuous learning & mentorship": {
                    "Upskilling program completion (%)": "Employees completing advanced ICT training",
                    "ICT mentorship programs (#)": "Number of mentoring initiatives",
                    "Employee retention rate (%)": "Retention of trained ICT employees",
                    "Knowledge sharing sessions (#)": "Internal sessions conducted"
                },
                "Strengthen digital skills in underserved areas": {
                    "ICT literacy outreach programs (#)": "Number of outreach programs",
                    "Rural ICT adoption (%)": "Users adopting ICT in rural areas",
                    "Training effectiveness score": "Feedback from participants",
                    "Community digital hubs established (#)": "Number of digital learning hubs"
                }
            },
            "Support National & Regional Economic Impact": {
                "Boost ICT sector contribution to GDP": {
                    "ICT sector contribution to GDP ($)": "Revenue and economic value added by ICT industry",
                    "Digital economy value ($)": "Total value from digital services",
                    "Cross-sector digital integration (%)": "ICT adoption in other sectors",
                    "ICT-driven employment rate (%)": "Jobs created in ICT sector / Total employment"
                },
                "Increase exports and international market reach": {
                    "Export revenue from ICT products/services ($)": "Revenue from international sales",
                    "International partnerships (#)": "Collaborations with foreign companies",
                    "Global market share (%)": "ICT exports / Total market share",
                    "Participation in trade fairs (#)": "Number of trade events attended"
                },
                "Promote entrepreneurship funding & support": {
                    "Entrepreneurship funding allocated ($)": "Investment in ICT entrepreneurship programs",
                    "Number of startups funded (#)": "Startups receiving funding",
                    "Job creation by funded startups (#)": "Employment from funded startups",
                    "Startup survival rate (%)": "Funded startups still operating after 2 years"
                },
                "Enhance innovation ecosystem": {
                    "Innovation ecosystem growth index": "Score of regional ICT innovation and infrastructure",
                    "Tech hubs established (#)": "Number of new tech hubs",
                    "Incubator participation (#)": "Number of startups in incubators",
                    "Research commercialization rate (%)": "Projects successfully commercialized"
                }
            }
        },

        # ==================== 2. ICT Infrastructure & Asset Finance ====================
        "ICT Infrastructure & Asset Finance": {
            "Modernize Data Centers": {
                "Data center modernization investment ($)": "Capital spent on upgrading facilities",
                "Server upgrade ratio (%)": "Upgraded servers / Total servers * 100",
                "Cooling system efficiency (%)": "Energy efficiency of data center cooling",
                "Power usage effectiveness (PUE)": "Total facility energy / IT equipment energy"
            },
            "Upgrade Network Infrastructure": {
                "Network infrastructure investment ($)": "Spending on network devices and cabling",
                "Bandwidth expansion (%)": "Increase in network capacity / Previous capacity * 100",
                "Latency reduction (%)": "Improvement in network response time",
                "Network coverage expansion (%)": "New areas connected / Planned expansion * 100"
            },
            "Enhance Cloud & Virtual Platforms": {
                "Cloud platform upgrade investment ($)": "Capital for cloud systems modernization",
                "Cloud service utilization rate (%)": "Used cloud resources / Total provisioned resources * 100",
                "Cloud migration completion (%)": "Percentage of systems migrated to cloud",
                "Cloud cost efficiency ($/unit)": "Cost per cloud resource unit used"
            },
            "Modernize ICT Equipment & Endpoints": {
                "Workstation and device upgrade ratio (%)": "Upgraded devices / Total devices * 100",
                "IT peripheral replacement investment ($)": "Capital spent on peripherals (printers, monitors, etc.)",
                "Endpoint security compliance (%)": "Devices compliant with security standards",
                "Device lifecycle adherence (%)": "Devices replaced within recommended lifecycle"
            },
            "Optimize ICT Asset Utilization": {
                "Server utilization rate (%)": "Hours used / Available hours * 100",
                "Network equipment uptime (%)": "Operational time / Total time * 100",
                "Cloud resource optimization (%)": "Used vs allocated cloud resources",
                "IT asset ROI ($)": "Revenue or cost savings per IT asset"
            },
            "Enhance ICT Technology Adoption": {
                "Enterprise software ROI (%)": "Benefits from software adoption / Cost * 100",
                "Cybersecurity investment ($)": "Spending on IT security infrastructure",
                "Digital platform adoption (%)": "Users utilizing digital platforms / Total users * 100",
                "Automation implementation rate (%)": "Automated processes / Total processes * 100"
            },
            "Preventive Maintenance & Lifecycle Management": {
                "IT maintenance compliance (%)": "Maintained devices / Total devices * 100",
                "Hardware replacement cycle (years)": "Average lifespan of ICT hardware",
                "Software update compliance (%)": "Systems updated / Total systems * 100",
                "Maintenance cost per asset ($)": "Total maintenance spend / Number of assets"
            },
            "Improve ICT Operational Efficiency": {
                "Cost per IT service ($)": "Total IT costs / Number of services provided",
                "IT support resolution time (hrs)": "Average time to resolve support tickets",
                "Process automation efficiency (%)": "Tasks automated / Total tasks * 100",
                "Service downtime reduction (%)": "Decrease in downtime vs previous period"
            },
            "Manage ICT Risk & Compliance": {
                "Data privacy compliance (%)": "Systems compliant with regulations",
                "IT security incident rate": "Number of incidents / Total systems",
                "Business continuity readiness (%)": "Preparedness for operational disruptions",
                "Regulatory audit success (%)": "Passed audits / Total audits * 100"
            },
            "Long-term ICT Sustainability & Investment": {
                "ICT strategic investment ROI (%)": "Return on long-term ICT investments",
                "Emerging technology adoption (%)": "New technologies implemented / Planned",
                "ICT operational sustainability ($)": "Cost savings from sustainable IT practices",
                "Innovation pipeline growth (%)": "New ICT initiatives / Total pipeline"
            }
        }
    }
}
