from management_project.services.strategy_hierarchy.finance_perspective import GENERIC_FINANCE_PERSPECTIVE
from management_project.services.strategy_hierarchy.customer_perspective import GENERIC_CUSTOMER_PERSPECTIVE
from management_project.services.strategy_hierarchy.internal_process_perspective import (
    GENERIC_INTERNAL_PROCESS_PERSPECTIVE,
)
from management_project.services.strategy_hierarchy.learning_and_growth_perspective import (
    GENERIC_LEARNING_AND_GROWTH_PERSPECTIVE,
)

ICT_PERSPECTIVE = {
    "Financial Perspective": {

        **GENERIC_FINANCE_PERSPECTIVE["Financial Perspective"],

        # ==================== 1. Startup & Entrepreneurship Support ====================
        "Startup & Entrepreneurship Support": {

            "Support ICT startups and new ventures": {
                "Startup funding support ($)": "Funding and grants allocated to ICT startups",
                "Number of active startups (#)": "Operational ICT startups",
                "Jobs created by startups (#)": "Employment generated by startups",
                "Spin-off company creation (#)": "New companies spun from research"
            },
            "Strengthen entrepreneurial ecosystem": {
                "Hackathon/innovation challenge participation (#)": "Participants in ICT events",
                "Regional tech cluster growth (#)": "Number of ICT clusters established",
                "Innovation awards won (#)": "Awards for innovative solutions",
                "Partnership agreements (#)": "Public-private partnerships signed"
            },
            "Support digital entrepreneurship education": {
                "ICT entrepreneurship courses offered (#)": "Number of courses provided",
                "Enrollment in entrepreneurship programs (#)": "Participants enrolled",
                "Completion rate of entrepreneurship programs (%)": "(Completed / Enrolled) * 100",
                "Entrepreneurship skill assessment improvement (%)": "((Post-pre)/Pre)*100"
            },
            "Promote startup incubators and accelerators": {
                "Incubator programs (#)": "Number of incubator programs established",
                "Accelerator programs (#)": "Number of accelerator programs running",
                "Startups supported (#)": "Startups receiving support",
                "Startup graduation rate (%)": "(Graduated / Total startups) * 100"
            },
            "Enhance mentorship and advisory services": {
                "Mentorship programs (#)": "Number of mentorship initiatives",
                "Startups with mentors (#)": "Startups assigned mentors",
                "Mentorship satisfaction score (1–5)": "Average rating",
                "Advisor engagement rate (%)": "(Active advisors / Total mentors) * 100"
            },
            "Foster networking and knowledge sharing": {
                "Networking events (#)": "ICT networking events conducted",
                "Participants in networking events (#)": "Total participants",
                "Collaborative projects initiated (#)": "Projects started via networking",
                "Knowledge exchange satisfaction (1–5)": "Average participant rating"
            },
            "Support regulatory and policy guidance": {
                "Policy workshops conducted (#)": "Number of workshops for startups",
                "Startups compliant with regulations (%)": "Compliant startups / Total startups * 100",
                "Regulatory guidance materials (#)": "Guides, toolkits, manuals provided",
                "Policy feedback adoption rate (%)": "(Implemented feedback / Total feedback) * 100"
            },
            "Promote gender and social inclusion in startups": {
                "Women-led startups (#)": "Number of women-led startups",
                "Startups supporting underrepresented groups (#)": "Number of inclusive startups",
                "Inclusive training sessions (#)": "Number of targeted training sessions",
                "Inclusion participation rate (%)": "(Participants from underrepresented groups / Total participants) * 100"
            },
        },

        # ==================== 2. ICT Economy Growth ====================
        "ICT Economy Growth": {

            "Promote innovation commercialization": {
                "Innovation commercialization revenue ($)": "Revenue from commercialized innovations",
                "New technology patent registrations (#)": "Number of patents filed",
                "Product prototype development (#)": "Number of prototypes developed",
                "Startup mentorship participation (#)": "Number of startups in mentoring programs"
            },
            "Encourage venture capital and investments": {
                "Venture capital investment ($)": "Capital invested in ICT ventures",
                "Incubator/accelerator program revenue ($)": "Revenue from support programs",
                "Number of investment rounds (#)": "Funding rounds completed by startups",
                "Investor participation rate (%)": "(Active investors / Total potential investors) * 100"
            },
            "Foster R&D for startups": {
                "R&D projects initiated (#)": "Number of ICT R&D projects",
                "R&D funding support ($)": "Funds allocated to R&D initiatives",
                "Patents filed from R&D (#)": "Number of patents generated from R&D",
                "Prototype commercialization rate (%)": "(Prototypes commercialized / Total prototypes) * 100"
            },
            "Promote collaborative innovation": {
                "Public-private co-innovation projects (#)": "Number of joint innovation projects",
                "Industry-academia partnerships (#)": "Number of collaboration agreements",
                "Open innovation platform usage (#)": "Number of users submitting ideas",
                "Co-created solutions deployed (#)": "Number of solutions implemented"
            },
            "Scale successful startups": {
                "Revenue growth (%)": "((Current - Previous)/Previous) * 100",
                "Jobs created by scaling startups (#)": "Employment from scaled startups",
                "Market expansion initiatives (#)": "New markets entered by startups",
                "Export revenue ($)": "Revenue from international markets"
            },
            "Promote digital product adoption": {
                "New user acquisition (#)": "Users adopting new digital solutions",
                "Usage frequency per user": "Average logins per user",
                "Retention rate (%)": "(Users retained / Total new users) * 100",
                "Customer satisfaction with products (%)": "Average rating"
            },
            "Support ICT service commercialization": {
                "ICT service revenue ($)": "Revenue from ICT services",
                "Number of service clients (#)": "Clients using commercial services",
                "Contract renewal rate (%)": "(Renewed contracts / Total contracts) * 100",
                "Service quality score (1–5)": "Average rating"
            },
            "Encourage ICT entrepreneurship exports": {
                "Export revenue ($)": "Revenue from exported ICT products/services",
                "Export-oriented startups (#)": "Startups targeting international markets",
                "International partnerships (#)": "Cross-border partnerships signed",
                "Market penetration (%)": "(Users acquired internationally / Target users) * 100"
            },
        },

        # ==================== 3. ICT Economic Development ====================
        "ICT Economic Development": {

            "Measure and scale startup impact": {
                "Revenue growth of startups (%)": "((Current revenue - Previous revenue)/Previous revenue) * 100",
                "Jobs created by scaled startups (#)": "Total employment from scaling startups",
                "Export revenue from ICT startups ($)": "Revenue generated from international markets",
                "Market expansion initiatives (#)": "New markets entered by startups"
            },
            "Promote Digital Inclusion": {
                "Broadband access expansion ($)": "Investment in broadband networks and infrastructure",
                "Mobile network coverage (%)": "Population covered by mobile networks",
                "Rural connectivity revenue ($)": "Revenue from rural connectivity initiatives",
                "Internet penetration rate (%)": "(Internet users / Total population) * 100"
            },
            "Improve digital literacy": {
                "Digital literacy program funding ($)": "Funding allocated to digital literacy programs",
                "ICT literacy training completion (%)": "Participants completing ICT literacy programs",
                "Public digital training sessions (#)": "Number of training sessions conducted",
                "Gender digital inclusion ratio (%)": "(Female ICT users / Total users) * 100"
            },
            "Increase access to affordable devices": {
                "Affordable device program funding ($)": "Funding for low-cost devices distribution",
                "Number of devices distributed (#)": "Total devices distributed to users",
                "Device adoption rate (%)": "Users actively using distributed devices",
                "Device functionality uptime (%)": "Average functionality of distributed devices"
            },
            "Foster ICT employment and GDP growth": {
                "ICT sector employment (#)": "Number of jobs in ICT sector",
                "ICT contribution to GDP (%)": "ICT sector value / Total GDP * 100",
                "Startup-driven GDP contribution (%)": "Revenue contribution from startups / Total GDP * 100",
                "Job creation rate (%)": "((Current jobs - Previous jobs)/Previous jobs) * 100"
            },
            "Encourage regional ICT hubs": {
                "Number of ICT hubs (#)": "Regional technology hubs established",
                "Startup density per hub (#)": "Startups located per hub",
                "Hub revenue ($)": "Revenue generated by regional hubs",
                "Hub job creation (#)": "Jobs generated in ICT hubs"
            },
            "Promote ICT exports and trade": {
                "Export revenue ($)": "Revenue from exported ICT products/services",
                "Number of exporting startups (#)": "Startups selling internationally",
                "Market penetration (%)": "International users / Total target users * 100",
                "Trade partnerships (#)": "Number of international agreements signed"
            },
            "Support sustainable ICT investment": {
                "Total ICT investment ($)": "Capital invested in ICT infrastructure and startups",
                "Private sector ICT investment ($)": "Private contributions to ICT",
                "Public ICT investment ($)": "Government spending on ICT development",
                "ROI of ICT investments (%)": "(Benefits / Costs) * 100"
            },
        },

        # ==================== 2. ICT Infrastructure & Asset Finance ====================
        "ICT Infrastructure & Asset Finance": {
            "Modernize Data Centers": {
                "Data center modernization investment ($)": "Capital spent on upgrading facilities",
                "Server upgrade ratio (%)": "Upgraded servers / Total servers * 100",
                "Cooling system efficiency (%)": "Energy efficiency of data center cooling",
                "Power usage effectiveness (PUE)": "Total facility energy / IT equipment energy"
            },
            "Upgrade Network Infrastructure": {
                "Network infrastructure investment ($)": "Spending on network devices and cabling",
                "Bandwidth expansion (%)": "Increase in network capacity / Previous capacity * 100",
                "Latency reduction (%)": "Improvement in network response time",
                "Network coverage expansion (%)": "New areas connected / Planned expansion * 100"
            },
            "Enhance Cloud & Virtual Platforms": {
                "Cloud platform upgrade investment ($)": "Capital for cloud systems modernization",
                "Cloud service utilization rate (%)": "Used cloud resources / Total provisioned resources * 100",
                "Cloud migration completion (%)": "Percentage of systems migrated to cloud",
                "Cloud cost efficiency ($/unit)": "Cost per cloud resource unit used"
            },
            "Modernize ICT Equipment & Endpoints": {
                "Workstation and device upgrade ratio (%)": "Upgraded devices / Total devices * 100",
                "IT peripheral replacement investment ($)": "Capital spent on peripherals (printers, monitors, etc.)",
                "Endpoint security compliance (%)": "Devices compliant with security standards",
                "Device lifecycle adherence (%)": "Devices replaced within recommended lifecycle"
            },
            "Optimize ICT Asset Utilization": {
                "Server utilization rate (%)": "Hours used / Available hours * 100",
                "Network equipment uptime (%)": "Operational time / Total time * 100",
                "Cloud resource optimization (%)": "Used vs allocated cloud resources",
                "IT asset ROI ($)": "Revenue or cost savings per IT asset"
            },
            "Enhance ICT Technology Adoption": {
                "Enterprise software ROI (%)": "Benefits from software adoption / Cost * 100",
                "Cybersecurity investment ($)": "Spending on IT security infrastructure",
                "Digital platform adoption (%)": "Users utilizing digital platforms / Total users * 100",
                "Automation implementation rate (%)": "Automated processes / Total processes * 100"
            },
            "Preventive Maintenance & Lifecycle Management": {
                "IT maintenance compliance (%)": "Maintained devices / Total devices * 100",
                "Hardware replacement cycle (years)": "Average lifespan of ICT hardware",
                "Software update compliance (%)": "Systems updated / Total systems * 100",
                "Maintenance cost per asset ($)": "Total maintenance spend / Number of assets"
            },
            "Improve ICT Operational Efficiency": {
                "Cost per IT service ($)": "Total IT costs / Number of services provided",
                "IT support resolution time (hrs)": "Average time to resolve support tickets",
                "Process automation efficiency (%)": "Tasks automated / Total tasks * 100",
                "Service downtime reduction (%)": "Decrease in downtime vs previous period"
            },
            "Manage ICT Risk & Compliance": {
                "Data privacy compliance (%)": "Systems compliant with regulations",
                "IT security incident rate": "Number of incidents / Total systems",
                "Business continuity readiness (%)": "Preparedness for operational disruptions",
                "Regulatory audit success (%)": "Passed audits / Total audits * 100"
            },
            "Long-term ICT Sustainability & Investment": {
                "ICT strategic investment ROI (%)": "Return on long-term ICT investments",
                "Emerging technology adoption (%)": "New technologies implemented / Planned",
                "ICT operational sustainability ($)": "Cost savings from sustainable IT practices",
                "Innovation pipeline growth (%)": "New ICT initiatives / Total pipeline"
            }
        },
    },

    "Customer Perspective": {

        # ---------------- GENERIC CUSTOMER PERSPECTIVE ----------------
        **GENERIC_CUSTOMER_PERSPECTIVE["Customer Perspective"],
        # =========================================================
        # 1. Digital Citizen Service Access / Digital Service Access
        # =========================================================
        "Digital Citizen Service Access": {
            "Ensure high availability of e-services": {
                "Service uptime (%)": "(Available hours / Total hours) * 100",
                "Downtime incidents per month": "Number of downtime events",
                "Average downtime duration (minutes)": "Sum(downtime) / Number of incidents",
                "SLA compliance (%)": "(Services meeting SLA / Total services) * 100",
            },
            "Expand access to remote and underserved populations": {
                "Coverage of public digital services (%)": "(Population with access / Total population) * 100",
                "Rural user access rate (%)": "(Rural users accessing services / Total rural population) * 100",
                "Digital access points per 10,000 population": "Total digital kiosks / Population * 10,000",
                "Public Wi-Fi coverage (%)": "(Covered areas / Total areas) * 100",
            },
            "Enable multi-channel access": {
                "Web access rate (%)": "(Users accessing via web / Total users) * 100",
                "Mobile access rate (%)": "(Users accessing via mobile / Total users) * 100",
                "Offline service utilization (%)": "(Offline service users / Total users) * 100",
                "Cross-platform satisfaction score (1–5)": "Average rating",
            },
            "Increase service inclusivity": {
                "Accessibility compliance (%)": "(Accessible services / Total services) * 100",
                "Users with disabilities served (%)": "(Served users / Total users with disabilities) * 100",
                "Low-bandwidth user satisfaction (%)": "(Satisfied low-bandwidth users / Total) * 100",
                "Language coverage (%)": "(Supported languages / Total required languages) * 100",
            },
            # Added: older Digital Service Access objectives
            "Ensure high system availability": {
                "Service availability (%)": "(Available hours / Total hours) * 100",
                "System uptime (%)": "(Uptime minutes / Total minutes) * 100",
                "Downtime incidents per month": "Number of downtime events",
                "Average downtime duration (minutes)": "Sum(downtime) / Number of incidents",
            },
            "Improve login and authentication experience": {
                "Successful login rate (%)": "(Successful logins / Total login attempts) * 100",
                "Failed login attempts (%)": "(Failed logins / Total login attempts) * 100",
                "Multi-factor authentication adoption (%)": "(Users using MFA / Total users) * 100",
                "Average login time (seconds)": "Total login time / Total login attempts",
            },
            "Enhance cross-platform accessibility": {
                "Mobile access rate (%)": "(Mobile logins / Total logins) * 100",
                "Web access rate (%)": "(Web logins / Total logins) * 100",
                "App crash rate (%)": "(Crashes / Total app sessions) * 100",
                "Browser compatibility satisfaction (%)": "Average user rating",
            },
            "Expand service coverage for all users": {
                "Population coverage (%)": "(Users with access / Total target users) * 100",
                "Geographical coverage (%)": "(Regions covered / Total regions) * 100",
                "Peak load handling (%)": "(Peak requests handled / Total peak requests) * 100",
                "Service reach improvement (%)": "((Current reach - Previous reach)/Previous reach)*100",
            },
            "Increase 24/7 service availability": {
                "Nighttime uptime (%)": "(Available hours at night / Total night hours) * 100",
                "Weekend uptime (%)": "(Available hours on weekend / Total weekend hours) * 100",
                "Off-hour support response time (minutes)": "Average response time",
                "Critical service SLA compliance (%)": "(SLAs met / Total SLAs) * 100",
            },
            "Enhance digital inclusivity": {
                "Access for persons with disabilities (%)": "(Accessible services / Total services) * 100",
                "Support for low-bandwidth users (%)": "(Users able to access / Total users) * 100",
                "Accessibility feedback score (1–5)": "Average rating",
                "Digital divide reduction (%)": "((Previous gap - Current gap)/Previous gap)*100",
            },
        },

        # =========================================================
        # 2. Citizen / User Support and Satisfaction
        # =========================================================
        "Citizen Support and Engagement": {
            "Enhance helpdesk responsiveness": {
                "Average response time (hours)": "Sum(response times) / Total queries",
                "SLA compliance (%)": "(Queries resolved within SLA / Total queries) * 100",
                "First-contact resolution (%)": "(Resolved on first contact / Total queries) * 100",
                "Citizen satisfaction (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Improve digital feedback systems": {
                "Feedback collected (%)": "(Feedback received / Total users) * 100",
                "Average resolution time (hours)": "Sum(time to resolve) / Total feedback",
                "Implemented citizen suggestions (%)": "(Implemented / Total suggestions) * 100",
                "User engagement score (1–5)": "Average rating",
            },
            "Support citizen education and awareness": {
                "Digital literacy program participation (%)": "(Participated / Target population) * 100",
                "Training completion rate (%)": "(Completed / Enrolled) * 100",
                "Awareness campaign reach (%)": "(Reached / Target population) * 100",
                "Post-training comprehension (%)": "((Post-pre)/Pre)*100",
            },
            "Ensure transparency in public services": {
                "Information availability (%)": "(Published info / Total required) * 100",
                "Citizen trust score (1–5)": "Average rating",
                "Response to citizen inquiries (%)": "(Responded / Total inquiries) * 100",
                "Public portal satisfaction (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Promote citizen participation": {
                "Participation in e-polls and surveys (%)": "(Participants / Total target population) * 100",
                "Number of co-created initiatives": "Count",
                "User satisfaction with participatory initiatives (%)": "(Satisfied / Total participants) * 100",
                "Suggestions adopted (%)": "(Implemented / Total suggestions) * 100",
            },
            # Added: User Support and Satisfaction objectives
            "Reduce support ticket resolution time": {
                "Average ticket resolution time (hours)": "Sum(time to resolve) / Total tickets",
                "First-contact resolution rate (%)": "(Resolved first contact / Total tickets) * 100",
                "Support backlog (%)": "(Pending tickets / Total tickets) * 100",
                "User satisfaction with support (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Improve helpdesk responsiveness": {
                "Average initial response time (minutes)": "Sum(response times) / Total tickets",
                "SLA compliance rate (%)": "(Tickets resolved within SLA / Total tickets) * 100",
                "Support agent availability (%)": "(Available agents / Total agents) * 100",
                "Escalation rate (%)": "(Escalated tickets / Total tickets) * 100",
            },
            "Enhance self-service capabilities": {
                "Knowledge base usage (%)": "(Users using KB / Total users) * 100",
                "Self-service resolution rate (%)": "(Resolved via self-service / Total issues) * 100",
                "Help article satisfaction (%)": "(Positive ratings / Total ratings) * 100",
                "Average search success rate (%)": "(Successful searches / Total searches) * 100",
            },
            "Support multi-language users": {
                "Multilingual support coverage (%)": "(Supported languages / Total required languages) * 100",
                "User satisfaction for non-native speakers (%)": "(Satisfied / Total surveyed) * 100",
                "Interpreter service utilization (%)": "(Used / Total requested) * 100",
                "Average response time for multilingual support (minutes)": "Sum(response times) / Total requests",
            },
            "Improve feedback loops": {
                "Feedback collected (%)": "(Feedback received / Total users) * 100",
                "Average response time to feedback (hours)": "Sum(response times) / Total feedback",
                "Implemented suggestions (%)": "(Implemented / Total suggestions) * 100",
                "User engagement in feedback programs (%)": "(Participants / Total users) * 100",
            },
            "Enhance personalization of support": {
                "Personalized response rate (%)": "(Personalized responses / Total responses) * 100",
                "Customer satisfaction with personalization (%)": "(Satisfied / Total surveyed) * 100",
                "Profile-based recommendations usage (%)": "(Users using recommendations / Total users) * 100",
                "Reduction in repeat tickets due to personalization (%)": "((Previous - Current)/Previous)*100",
            },
            "Increase overall user satisfaction": {
                "Overall satisfaction (%)": "(Satisfied / Total surveyed) * 100",
                "Net Promoter Score (NPS)": "Promoters - Detractors",
                "Repeat complaint rate (%)": "(Repeat complaints / Total complaints) * 100",
                "User engagement score (1–5)": "Average rating",
            },
        },

        # =========================================================
        # 3. Digital Literacy and Training / Adoption
        # =========================================================
        "Digital Literacy and Adoption": {
            "Increase citizen proficiency in digital services": {
                "Digital literacy improvement (%)": "((Post-pre)/Pre)*100",
                "Skill assessment pass rate (%)": "(Passed / Total assessed) * 100",
                "Self-reported confidence (%)": "(Confident users / Total surveyed) * 100",
                "Average competency score (1–5)": "Average rating",
            },
            "Promote onboarding of new users": {
                "New user registration (%)": "(Registered / Target population) * 100",
                "Orientation completion rate (%)": "(Completed / Total new users) * 100",
                "Time to full adoption (days)": "Average days to adopt services",
                "Dropout rate during onboarding (%)": "(Dropped / Total new users) * 100",
            },
            "Support continuous learning": {
                "Number of digital training sessions": "Count",
                "Average training satisfaction score (1–5)": "Average rating",
                "Repeat training participation (%)": "(Users repeating / Total users) * 100",
                "Skills gap reduction (%)": "((Previous gap - Current gap)/Previous gap)*100",
            },
            "Encourage innovation adoption": {
                "New service adoption (%)": "(Users using new service / Total users) * 100",
                "Retention rate of new service users (%)": "(Retained / Total new users) * 100",
                "User satisfaction with new services (%)": "(Satisfied / Total surveyed) * 100",
                "Pilot participation (%)": "(Users participating in pilot / Total target users) * 100",
            },
            # Added: Digital Literacy and Training objectives
            "Enhance user training completion": {
                "Training completion rate (%)": "(Completed / Enrolled) * 100",
                "Average training score": "Sum(scores)/Total participants",
                "Time to complete training (hours)": "Average hours per participant",
                "Training attendance rate (%)": "(Attended / Invited) * 100",
            },
            "Increase digital proficiency": {
                "Digital proficiency improvement (%)": "((Post-pre)/Pre)*100",
                "User confidence score (1–5)": "Average rating",
                "Skill assessment pass rate (%)": "(Passed / Total assessed) * 100",
                "Self-reported competency (%)": "(Users confident / Total surveyed) * 100",
            },
            "Promote awareness of digital tools": {
                "User adoption of tools (%)": "(Active users / Total target users) * 100",
                "Engagement rate (%)": "(Users interacting with tools / Total active users) * 100",
                "Training feedback score (1–5)": "Average rating",
                "Usage frequency per month": "Average number of logins per user",
            },
            "Support onboarding of new users": {
                "New user orientation completion (%)": "(Completed / Total new users) * 100",
                "Average onboarding satisfaction (1–5)": "Average rating",
                "Time to full productivity (days)": "Average days for users to reach proficiency",
                "Dropout rate during onboarding (%)": "(Dropped / Total new users) * 100",
            },
            "Monitor digital skill gaps": {
                "Skill gap assessment coverage (%)": "(Assessed / Total users) * 100",
                "Improvement in gap score (%)": "((Previous gap - Current gap)/Previous gap)*100",
                "Targeted training participation (%)": "(Trained / Total identified) * 100",
                "Reduction in support tickets due to skill gaps (%)": "((Previous tickets - Current tickets)/Previous tickets)*100",
            },
        },

        # =========================================================
        # 4. Innovation and New Service Adoption / Service Quality
        # =========================================================
        "Customer Digital Service Innovation & Quality": {
            "Improve e-service quality": {
                "System response time (seconds)": "Average response",
                "Error rate (%)": "(Errors / Total transactions) * 100",
                "User satisfaction score (1–5)": "Average rating",
                "Service level compliance (%)": "(Compliant services / Total services) * 100",
            },
            "Support continuous improvement": {
                "Number of process improvements implemented": "Count",
                "Citizen engagement in improvements (%)": "(Participating citizens / Total target) * 100",
                "Average feedback implementation (%)": "(Implemented suggestions / Total feedback) * 100",
                "Satisfaction with improvements (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Encourage co-creation and participation": {
                "Participatory initiatives (%)": "(Users involved / Total target) * 100",
                "Number of citizen-driven innovations": "Count",
                "Adoption of citizen suggestions (%)": "(Implemented / Total suggestions) * 100",
                "User satisfaction with co-created services (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Promote sustainability and inclusivity": {
                "Repeat usage rate (%)": "(Active users / Total users) * 100",
                "Reduction in abandoned services (%)": "((Previous abandoned - Current)/Previous)*100",
                "Accessibility satisfaction (%)": "(Satisfied / Total surveyed) * 100",
                "Service coverage growth (%)": "((Current - Previous)/Previous)*100",
            },
            # Added: Innovation and New Service Adoption objectives
            "Increase adoption of new digital services": {
                "New service adoption rate (%)": "(Users using new service / Total users) * 100",
                "User engagement with new service (%)": "(Active users / Total users) * 100",
                "Retention rate of new service users (%)": "(Users retained / Total new users) * 100",
                "Feedback score for new services (1–5)": "Average rating",
            },
            "Encourage early adopters participation": {
                "Early adopter engagement (%)": "(Active early adopters / Total target) * 100",
                "Number of pilot participants": "Count of users in pilot programs",
                "Feedback implemented (%)": "(Implemented suggestions / Total feedback) * 100",
                "Satisfaction of pilot users (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Promote co-creation with users": {
                "User-driven feature requests (%)": "(Implemented requests / Total requests) * 100",
                "User involvement in design (%)": "(Users involved / Total projects) * 100",
                "Number of co-created solutions": "Count",
                "User satisfaction with co-created solutions (%)": "(Satisfied / Total users) * 100",
            },
            "Enhance awareness of digital innovations": {
                "Digital innovation awareness (%)": "(Users aware / Total users) * 100",
                "Participation in innovation webinars (%)": "(Participants / Total invited) * 100",
                "Knowledge improvement from sessions (%)": "((Post-pre)/Pre)*100",
                "User feedback score (1–5)": "Average rating",
            },
            "Promote sustainable digital adoption": {
                "User retention rate (%)": "(Retained users / Total users) * 100",
                "Repeat usage rate (%)": "(Users repeatedly using / Total users) * 100",
                "Satisfaction with sustainability initiatives (%)": "(Satisfied / Total surveyed) * 100",
                "Reduction in abandoned services (%)": "((Previous abandoned - Current)/Previous)*100",
            },
        },

        # =========================================================
        # Security and Privacy / Security, Privacy, and Trust
        # =========================================================
        "Security, Privacy, and Trust": {
            "Enhance data protection": {
                "Data breach incidents": "Count",
                "Compliance with privacy regulations (%)": "(Compliant processes / Total) * 100",
                "Encryption adoption rate (%)": "(Encrypted data / Total sensitive data) * 100",
                "User-reported privacy concerns (%)": "(Concerns / Total users) * 100",
            },
            "Improve account and authentication security": {
                "Multi-factor authentication adoption (%)": "(Users using MFA / Total users) * 100",
                "Strong password compliance (%)": "(Strong passwords / Total accounts) * 100",
                "Account compromise incidents": "Count",
                "User satisfaction with security (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Ensure secure communication": {
                "Secure portal messaging adoption (%)": "(Encrypted messages / Total messages) * 100",
                "Data transfer encryption (%)": "(Encrypted transfers / Total transfers) * 100",
                "Unauthorized access incidents": "Count",
                "Citizen confidence score (1–5)": "Average rating",
            },
            "Build transparency and trust": {
                "Privacy policy awareness (%)": "(Aware / Total users) * 100",
                "Response time to security incidents (hours)": "Average time",
                "Compliance audits per year": "Count",
                "Trust score improvement (%)": "((Current - Previous)/Previous)*100",
            },
            # Added: Security and Privacy objectives
            "Enhance user data protection": {
                "Data breach incidents": "Count of breaches",
                "Compliance with data protection standards (%)": "(Compliant processes / Total processes) * 100",
                "User-reported privacy concerns (%)": "(Concerns / Total users) * 100",
                "Encryption adoption rate (%)": "(Encrypted data / Total sensitive data) * 100",
            },
            "Improve account security": {
                "Password strength compliance (%)": "(Strong passwords / Total accounts) * 100",
                "Two-factor authentication adoption (%)": "(2FA enabled / Total users) * 100",
                "Account compromise incidents": "Count",
                "Security training completion (%)": "(Trained staff / Total staff) * 100",
            },
            "Enhance secure communication": {
                "Secure messaging adoption (%)": "(Secure messages / Total messages) * 100",
                "Data transfer encryption (%)": "(Encrypted transfers / Total transfers) * 100",
                "Unauthorized access incidents": "Count",
                "User satisfaction with security (%)": "(Satisfied / Total surveyed) * 100",
            },
            "Increase transparency and trust": {
                "Privacy policy awareness (%)": "(Users aware / Total users) * 100",
                "User trust score (1–5)": "Average rating",
                "Incident reporting response time (hours)": "Average time to respond",
                "Compliance audit frequency": "Number of audits per year",
            },
        },

        # -------------------- Telecom-specific Customer Focus --------------------
        "Telecom Service & Network Access": {
            "Increase Network Coverage": {
                "Network coverage area (%)": "Covered geographic area / Total target area * 100",
                "Population coverage (%)": "Population with network access / Total population * 100",
                "New tower deployment (#)": "Number of new towers or base stations installed",
                "Network accessibility complaints (#)": "Number of complaints about access issues"
            },
            "Enhance Service Quality & Reliability": {
                "Call drop rate (%)": "Dropped calls / Total calls * 100",
                "Network uptime (%)": "Time network is operational / Total time * 100",
                "Average data speed (Mbps)": "Measured throughput for customers",
                "Service issue resolution time (hrs)": "Average hours to resolve service issues"
            },
            "Promote Digital Services Adoption": {
                "Digital app users (#)": "Number of active users on telecom app",
                "Online self-service transactions (#)": "Transactions performed via app or portal",
                "Digital service satisfaction (%)": "Survey score of digital users",
                "Growth in mobile data usage (%)": "(Current - Previous period) / Previous * 100"
            },
            "Ensure Accessibility for All Customer Segments": {
                "Coverage in rural areas (%)": "Rural population with access / Total rural population * 100",
                "Affordable service plan adoption (%)": "Subscribers using low-cost plans / Total subscribers * 100",
                "Customer inclusion programs (#)": "Programs targeting underserved communities",
                "Customer complaints resolved (%)": "Resolved complaints / Total complaints * 100"
            }
        },
    },

    "Internal Process Perspective": {

        **GENERIC_INTERNAL_PROCESS_PERSPECTIVE["Internal Process Perspective"],

        # -------------------- Software Development & Deployment --------------------
        "Software Development & Deployment": {

            "Enhance Agile Delivery Performance": {
                "Sprint completion rate (%)": "(Completed sprints / Planned sprints) * 100",
                "Feature delivery accuracy (%)": "(Delivered features / Planned features) * 100",
                "Average bug resolution time (hours)": "Total time to resolve / Number of bugs",
                "Code review compliance (%)": "(Reviewed commits / Total commits) * 100"
            },

            "Strengthen Release & Deployment Management": {
                "Successful release rate (%)": "(Successful releases / Total releases) * 100",
                "Rollback frequency (#)": "Number of rollbacks within release cycles",
                "Release readiness checklist completion (%)": "(Completed checklists / Total releases) * 100",
                "Deployment automation coverage (%)": "(Automated deployments / Total deployments) * 100"
            },

            "Improve Software Quality Assurance": {
                "Test coverage (%)": "(Executed test cases / Total planned test cases) * 100",
                "Defect detection efficiency (%)": "(Defects found pre-release / Total defects) * 100",
                "Regression testing completion rate (%)": "(Completed regression tests / Planned) * 100",
                "Open defect backlog (#)": "Number of unresolved defects at sprint end"
            },

            "Optimize Flow Efficiency & Throughput": {
                "Lead Time (days)": "Average time from business requirement to production delivery",
                "Cycle Time (days)": "Average time from first commit to production deployment",
                "Deployment Frequency (#/week)": "Number of production deployments per week",
                "Feature Throughput (#/sprint)": "Features delivered meeting definition of done"
            },

            "Maximize Business Value Delivery": {
                "Feature Adoption Rate (%)": "(Active feature users / Total active users) * 100",
                "Business Objective Achievement (%)": "(Delivered features achieving business KPIs / Total features) * 100",
                "Time-to-Value (days)": "Average time from project start to first measurable benefit",
                "Digital Revenue Contribution (%)": "(Revenue from digital products / Total revenue) * 100"
            },

            "Strengthen Predictability & Planning": {
                "Forecast Accuracy (%)": "(Actual velocity / Forecasted velocity) * 100",
                "Commitment Reliability (%)": "(Delivered scope / Committed scope) * 100",
                "Unplanned Work Ratio (%)": "(Time spent on unplanned work / Total capacity) * 100",
                "Scope Change Impact (%)": "(Scope added or removed / Original scope) * 100"
            },

            "Improve Code Health & Maintainability": {
                "Technical Debt Ratio (%)": "(Remediation cost / System cost) * 100",
                "Code Health Index (0-100)": "Composite of maintainability, complexity, and coverage",
                "Static Analysis Pass Rate (%)": "(Builds passing quality gates / Total builds) * 100",
                "Architecture Compliance (%)": "(Components following standards / Total components) * 100"
            },

            "Enhance Production Stability & Performance": {
                "System Availability (%)": "(Actual uptime / Planned uptime) * 100",
                "Escaped Defect Rate (%)": "(Critical bugs in production / Total critical bugs) * 100",
                "Incident Frequency (#/month)": "Number of production incidents requiring response",
                "Performance SLO Compliance (%)": "(Met SLOs / Total defined SLOs) * 100"
            },

            "Boost Developer Productivity & Team Efficiency": {
                "Developer Velocity Index": "Story points completed per developer normalized per sprint",
                "Flow Efficiency (%)": "(Active coding time / Total cycle time) * 100",
                "Code Review Turnaround (hours)": "Average time from PR submission to merge",
                "Merge Frequency (#/day)": "Average number of merges to main branch per day"
            },

            "Enhance Process & Toolchain Efficiency": {
                "Build Success Rate (%)": "(Successful builds / Total builds) * 100",
                "CI Feedback Time (minutes)": "Average time from commit to CI result feedback",
                "Environment Availability (%)": "(Available dev/test environments / Total required) * 100",
                "Dependency Resolution Time (hours)": "Average time to resolve cross-team dependencies"
            },

            "Strengthen Security & Compliance": {
                "Mean Time to Patch (days)": "Average time to remediate critical vulnerabilities",
                "Vulnerability Density (#/kLOC)": "Security issues per thousand lines of code",
                "Dependency Risk Score": "Composite risk score from third-party libraries",
                "Security Test Coverage (%)": "(Security tests executed / Total required security tests) * 100"
            },

            "Strengthen Team Health & Learning": {
                "Team Health Score (1-10)": "Composite of morale, collaboration, and motivation",
                "Cross-functional Collaboration (%)": "(Team members contributing across domains / Total) * 100",
                "Knowledge Sharing Sessions (#/quarter)": "Number of internal learning or mentoring events",
                "Onboarding Efficiency (days)": "Average days for a new developer to make first production commit"
            },

        },

        # -------------------- IT Infrastructure Management --------------------
        "IT Infrastructure Management": {
            "Optimize Compute & Server Operations": {
                "Server availability (%)": "(Uptime / Total monitored time) * 100",
                "Virtualization efficiency ratio": "VM-to-host consolidation ratio",
                "Workload performance score": "Application response time and throughput",
                "Automated provisioning rate (%)": "(Automated deployments / Total deployments) * 100"
            },

            "Enhance Network Performance & Reliability": {
                "Network uptime (%)": "(Available time / Total time) * 100",
                "Bandwidth utilization efficiency (%)": "(Used capacity / Total capacity) * 100",
                "Latency compliance rate (%)": "(Within thresholds / Total measurements) * 100",
                "Network incident resolution time (minutes)": "Mean time to repair network issues"
            },

            "Strengthen Data Center & Facilities Management": {
                "Power usage effectiveness (PUE)": "Total facility power / IT equipment power",
                "Infrastructure capacity headroom (%)": "(Available capacity / Total capacity) * 100",
                "Preventive maintenance compliance (%)": "(Completed maintenance / Scheduled) * 100",
                "Energy efficiency improvement (%)": "Year-over-year power consumption reduction"
            },

            "Advance Storage & Data Management": {
                "Storage utilization rate (%)": "(Used storage / Provisioned storage) * 100",
                "Data protection coverage (%)": "(Protected data / Total critical data) * 100",
                "Storage performance score": "IOPS and throughput against benchmarks",
                "Data tiering efficiency (%)": "(Optimally tiered data / Total data) * 100"
            },

            "Improve Cloud & Hybrid Infrastructure": {
                "Cloud resource optimization (%)": "(Right-sized resources / Total resources) * 100",
                "Multi-cloud management efficiency": "Cross-platform operational consistency",
                "Cloud cost per workload ($)": "Total cloud spend / Number of workloads",
                "Hybrid connectivity reliability (%)": "(Available connections / Total connections) * 100"
            },

            "Strengthen Backup & Disaster Recovery": {
                "Backup success rate (%)": "(Successful backups / Total backups) * 100",
                "Recovery time objective achievement (%)": "(Met RTO / Total recovery tests) * 100",
                "Recovery point objective compliance (%)": "(Met RPO / Total backup cycles) * 100",
                "Disaster recovery test success rate (%)": "(Successful tests / Total tests) * 100"
            },

            "Optimize Capacity Planning & Scalability": {
                "Capacity forecast accuracy (%)": "(Actual usage / Forecasted usage) * 100",
                "Resource provisioning time (hours)": "Average time from request to availability",
                "Scalability readiness score": "Ability to handle 50% workload increase",
                "Infrastructure elasticity efficiency": "Dynamic scaling response and cost"
            },

            "Enhance Infrastructure Security & Compliance": {
                "Security patch compliance rate (%)": "(Patched systems / Total systems) * 100",
                "Configuration management adherence (%)": "(Compliant configurations / Total) * 100",
                "Access control effectiveness (%)": "(Properly controlled access / Total access points) * 100",
                "Compliance audit success rate (%)": "(Passed audits / Total audits) * 100"
            },

            "Improve Automation & Orchestration": {
                "Infrastructure as code adoption (%)": "(Managed as code / Total infrastructure) * 100",
                "Orchestration workflow success rate (%)": "(Successful workflows / Total executed) * 100",
                "Manual intervention rate (%)": "(Manual tasks / Total operations) * 100",
                "Self-service provisioning usage (%)": "(Self-service requests / Total requests) * 100"
            },

            "Ensure Monitoring & Performance Management": {
                "Monitoring coverage (%)": "(Monitored components / Total infrastructure) * 100",
                "Performance SLA compliance (%)": "(Met performance targets / Total SLAs) * 100",
                "Alert accuracy rate (%)": "(Valid alerts / Total alerts) * 100",
                "Infrastructure health index": "Composite score of all system health metrics"
            },
        },
        # -------------------- Cybersecurity & Risk Management --------------------
        "Cybersecurity & Risk Management": {
            "Enhance Threat Detection & Intelligence": {
                "Mean time to detect (MTTD)": "Average time from threat emergence to detection",
                "Threat detection accuracy (%)": "(True positives / Total alerts) * 100",
                "Security monitoring coverage (%)": "(Monitored assets / Total critical assets) * 100",
                "Threat intelligence utilization": "Integration and action on external threat feeds"
            },

            "Strengthen Vulnerability Management": {
                "Vulnerability remediation rate (%)": "(Remediated vulnerabilities / Total identified) * 100",
                "Patch compliance rate (%)": "(Patched systems / Total systems) * 100",
                "Critical vulnerability exposure time (days)": "Average time critical vulns remain unpatched",
                "Vulnerability assessment coverage (%)": "(Assessed systems / Total inventory) * 100"
            },

            "Optimize Identity & Access Management": {
                "Privileged access compliance (%)": "(Compliant privileged accounts / Total) * 100",
                "Access review completion rate (%)": "(Reviewed access rights / Total required) * 100",
                "Multi-factor authentication coverage (%)": "(MFA-protected systems / Total systems) * 100",
                "Orphaned account rate (%)": "(Orphaned accounts / Total accounts) * 100"
            },

            "Improve Incident Response & Recovery": {
                "Mean time to respond (MTTR)": "Average time from detection to containment",
                "Incident containment effectiveness (%)": "(Contained incidents / Total incidents) * 100",
                "Recovery time objective achievement (%)": "(Met RTO / Total incidents) * 100",
                "Post-incident improvement implementation (%)": "(Implemented improvements / Total recommendations) * 100"
            },

            "Advance Security Governance & Compliance": {
                "Policy compliance rate (%)": "(Compliant controls / Total controls) * 100",
                "Security framework adoption (%)": "(Implemented controls / Total framework) * 100",
                "Audit finding remediation rate (%)": "(Remediated findings / Total findings) * 100",
                "Regulatory requirement coverage (%)": "(Addressed requirements / Total applicable) * 100"
            },

            "Strengthen Data Protection & Privacy": {
                "Data classification coverage (%)": "(Classified data / Total sensitive data) * 100",
                "Encryption compliance rate (%)": "(Encrypted data / Total sensitive data) * 100",
                "Data breach prevention effectiveness": "Reduction in data exposure incidents",
                "Privacy regulation adherence (%)": "(Compliant processes / Total processes) * 100"
            },

            "Enhance Security Architecture & Controls": {
                "Security control effectiveness (%)": "(Effective controls / Total implemented) * 100",
                "Zero trust implementation progress (%)": "(Implemented components / Total architecture) * 100",
                "Network segmentation compliance (%)": "(Segmented networks / Total required) * 100",
                "Security technology utilization (%)": "(Utilized capabilities / Total available) * 100"
            },

            "Improve Third-Party Risk Management": {
                "Vendor security assessment rate (%)": "(Assessed vendors / Total critical vendors) * 100",
                "Third-party risk mitigation (%)": "(Mitigated risks / Total identified) * 100",
                "Supply chain security compliance (%)": "(Compliant partners / Total partners) * 100",
                "Contract security adherence (%)": "(Compliant contracts / Total contracts) * 100"
            },

            "Advance Security Awareness & Culture": {
                "Security training completion rate (%)": "(Trained employees / Total employees) * 100",
                "Phishing simulation success rate (%)": "(Reported phishing tests / Total tests) * 100",
                "Security policy awareness (%)": "(Aware employees / Total employees) * 100",
                "Security incident reporting rate": "Employee-reported security concerns per month"
            },

            "Optimize Cyber Risk quantification & Reporting": {
                "Risk assessment coverage (%)": "(Assessed risks / Total risk landscape) * 100",
                "Risk treatment effectiveness (%)": "(Treated risks / Total accepted risks) * 100",
                "Cyber risk quantification accuracy": "Financial impact estimation vs actual",
                "Stakeholder risk awareness score": "Executive and board understanding level"
            },
        },

        # -------------------- IT Service Management --------------------
        "IT Service Management": {
            "Optimize Service Desk & Incident Management": {
                "First contact resolution rate (%)": "(Resolved first contact / Total incidents) * 100",
                "Mean time to resolve (MTTR)": "Total resolution time / Number of incidents",
                "SLA compliance rate (%)": "(Incidents within SLA / Total incidents) * 100",
                "Customer satisfaction score (CSAT)": "Post-resolution survey ratings (1-5 scale)"
            },

            "Enhance Change & Release Management": {
                "Change success rate (%)": "(Successful changes / Total changes) * 100",
                "Emergency change rate (%)": "(Emergency changes / Total changes) * 100",
                "Change implementation time (hours)": "Average approval to implementation time",
                "Release rollback rate (%)": "(Rolled back releases / Total releases) * 100"
            },

            "Strengthen Problem & Root Cause Management": {
                "Problem resolution rate (%)": "(Resolved problems / Total identified) * 100",
                "Recurring incident reduction (%)": "((Previous - Current recurring incidents) / Previous) * 100",
                "Mean time to problem resolution": "Total resolution time / Number of problems",
                "Known error database utilization (%)": "(Used KEDB entries / Total entries) * 100"
            },

            "Improve Service Request Fulfillment": {
                "Request fulfillment rate (%)": "(Fulfilled requests / Total requests) * 100",
                "Average fulfillment time (hours)": "Total fulfillment time / Number of requests",
                "Standard service catalog usage (%)": "(Catalog requests / Total requests) * 100",
                "Automated fulfillment rate (%)": "(Automated requests / Total automatable) * 100"
            },

            "Advance Service Level Management": {
                "SLA achievement rate (%)": "(Met SLAs / Total SLAs) * 100",
                "Service availability (%)": "(Available time / Total monitored time) * 100",
                "Service quality index": "Composite performance across multiple metrics",
                "OLA underpinning contract compliance (%)": "(Compliant OLAs / Total OLAs) * 100"
            },

            "Optimize Configuration Management": {
                "CMDB accuracy rate (%)": "(Accurate CIs / Total CIs) * 100",
                "Configuration item completeness (%)": "(Documented CIs / Total infrastructure) * 100",
                "Change impact assessment accuracy (%)": "(Accurate assessments / Total assessments) * 100",
                "CMDB update latency (hours)": "Average time from change to CMDB update"
            },

            "Enhance Knowledge Management": {
                "Knowledge base usage rate (%)": "(KB searches / Total support interactions) * 100",
                "Self-service resolution rate (%)": "(KB-resolved issues / Total KB attempts) * 100",
                "Article quality score": "User ratings and effectiveness metrics",
                "Knowledge sharing adoption (%)": "(Contributing staff / Total support staff) * 100"
            },

            "Strengthen Continual Service Improvement": {
                "Process improvement initiatives (#)": "Number of CSI initiatives implemented",
                "Service improvement success rate (%)": "(Successful improvements / Total initiatives) * 100",
                "Cost per ticket reduction (%)": "((Previous - Current cost) / Previous) * 100",
                "Customer experience improvement": "Year-over-year satisfaction score increase"
            },

            "Manage Service Catalog & Portfolio": {
                "Service catalog currency (%)": "(Updated services / Total services) * 100",
                "Service utilization rate (%)": "(Used services / Available services) * 100",
                "New service adoption rate (%)": "(Adopted services / Total launched) * 100",
                "Service retirement compliance (%)": "(Properly retired / Total scheduled) * 100"
            },

            "Ensure Financial Management for IT Services": {
                "IT cost transparency (%)": "(Tracked costs / Total IT spend) * 100",
                "Cost per service unit ($)": "Total service cost / Service units delivered",
                "Budget variance rate (%)": "((Actual - Budget) / Budget) * 100",
                "Value for money index": "Business value delivered per IT dollar spent"
            },
        },

        # -------------------- Data & Analytics Operations --------------------
        "Data & Analytics Operations": {
            "Optimize data collection and accuracy": {
                "Data entry accuracy (%)": "(Accurate entries / Total entries) * 100",
                "Data completeness (%)": "(Completed fields / Total required fields) * 100",
                "Validation check pass rate (%)": "(Passed checks / Total checks) * 100",
                "Data entry efficiency (records/hour)": "Average records processed per hour"
            },
            "Strengthen data processing and ETL pipelines": {
                "ETL job success rate (%)": "(Successful jobs / Total jobs) * 100",
                "Data transformation accuracy (%)": "(Correctly transformed records / Total records) * 100",
                "ETL runtime efficiency (hours)": "Average runtime per job",
                "Error resolution time (hours)": "Average time to resolve ETL errors"
            },
            "Enhance analytics model development": {
                "Model validation completion (%)": "(Completed validations / Planned validations) * 100",
                "Model accuracy (%)": "(Correct predictions / Total test cases) * 100",
                "Version control adherence (%)": "(Updates properly tracked / Total updates) * 100",
                "Review cycle completion (%)": "(Completed / Planned) * 100"
            },
            "Improve report generation and quality": {
                "Report accuracy (%)": "(Accurate reports / Total reports) * 100",
                "Report timeliness (%)": "(On-time reports / Total reports) * 100",
                "Approval process adherence (%)": "(Followed / Total reports) * 100",
                "Distribution compliance (%)": "(Distributed correctly / Planned distribution) * 100"
            },
            "Enhance data governance and compliance": {
                "Policy compliance (%)": "(Compliant checks / Total checks) * 100",
                "Metadata management completion (%)": "(Completed / Planned) * 100",
                "Audit trail completeness (%)": "(Complete actions / Total actions) * 100",
                "Access review adherence (%)": "(Followed / Planned reviews) * 100"
            },
            "Ensure data security and protection": {
                "Access violation incidents (#)": "Number of unauthorized access attempts",
                "Encryption compliance (%)": "(Encrypted datasets / Total datasets) * 100",
                "Backup validation rate (%)": "(Validated backups / Total backups) * 100",
                "Breach detection and response time (hours)": "Average time to detect and respond"
            },
        },

        # -------------------- Network & Connectivity Management --------------------
        "Network & Connectivity Management": {
            "Enhance network uptime and reliability": {
                "Network availability (%)": "(Available time / Total time) * 100",
                "Mean time to repair (hours)": "Average time to resolve network outages",
                "Network incident frequency (#)": "Logged network incidents internally",
                "SLA compliance (%)": "(Met SLAs / Total agreements) * 100"
            },
            "Optimize bandwidth utilization": {
                "Bandwidth usage efficiency (%)": "(Used bandwidth / Total allocated) * 100",
                "Peak utilization alert frequency (#)": "Number of threshold breaches",
                "Network congestion incidents (#)": "Logged internally",
                "Capacity forecast accuracy (%)": "(Actual usage / Forecasted usage) * 100"
            },
            "Strengthen network security and resilience": {
                "Firewall compliance (%)": "(Compliant rules / Total rules) * 100",
                "Intrusion detection effectiveness (%)": "(Detected threats / Total simulated threats) * 100",
                "Vulnerability remediation rate (%)": "(Remediated / Identified vulnerabilities) * 100",
                "Network patch application adherence (%)": "(Applied / Required patches) * 100"
            },
            "Improve network monitoring and analytics": {
                "KPI tracking adherence (%)": "(Tracked / Planned KPIs) * 100",
                "Incident detection time (minutes)": "Average time to detect network issues",
                "Network performance index": "Composite internal performance score",
                "Trend and anomaly analysis completion (%)": "(Completed / Planned analyses) * 100"
            },
            "Enhance network troubleshooting and problem resolution": {
                "Average resolution time (hours)": "Average time per network incident",
                "Escalation handling efficiency (%)": "(Handled / Total escalations) * 100",
                "Recurring issue detection rate (%)": "(Recurring issues / Total incidents) * 100",
                "Root cause analysis completion (%)": "(Completed / Planned analyses) * 100"
            },
            "Ensure network compliance, documentation, and governance": {
                "Audit completion (%)": "(Completed / Planned internal audits) * 100",
                "Regulatory compliance (%)": "(Compliant / Total applicable regulations) * 100",
                "Documentation completeness (%)": "(Complete / Total required documentation) * 100",
                "Corrective action closure rate (%)": "(Closed / Total identified issues) * 100"
            },
        },

        # -------------------- 10. System Administration & Operations --------------------
        "System Administration & Operations": {
            "Improve system availability & uptime": {
                "Server uptime (%)": "(Available / Total time) * 100",
                "Mean time to repair (hours)": "Average resolution",
                "System downtime incidents (#)": "Logged internally",
                "Internal SLA compliance (%)": "(Met / Total agreements) * 100"
            },
            "Optimize system performance": {
                "CPU utilization (%)": "(Used / Total capacity) * 100",
                "Memory usage efficiency (%)": "(Used / Total capacity) * 100",
                "Disk I/O efficiency (%)": "(Optimized / Total operations) * 100",
                "System response time (ms)": "Average measured internally"
            },
            "Enhance patch management & updates": {
                "Patch deployment success rate (%)": "(Applied / Total patches) * 100",
                "Patch compliance (%)": "(Compliant / Total systems) * 100",
                "Patch vulnerability remediation time (hours)": "Average internal",
                "Rollback incident rate (#)": "Logged internally"
            },
            "Strengthen user & access management": {
                "User access review completion (%)": "(Reviewed / Total users) * 100",
                "Unauthorized access attempts (#)": "Logged internally",
                "Role assignment accuracy (%)": "(Correct / Total roles) * 100",
                "Policy compliance (%)": "(Compliant / Total checks) * 100"
            },
            "Improve incident & problem management": {
                "Incident resolution time (hours)": "Average internal",
                "Recurring issue rate (%)": "(Recurrent / Total issues) * 100",
                "Problem resolution time (hours)": "Average internal",
                "Root cause analysis adherence (%)": "(Followed / Total incidents) * 100"
            },
            "Ensure compliance & documentation readiness": {
                "Internal audit completion (%)": "(Completed / Planned) * 100",
                "Policy adherence (%)": "(Compliant / Total checks) * 100",
                "Corrective action closure (%)": "(Closed / Total issues) * 100",
                "Documentation completeness (%)": "(Complete / Total required) * 100"
            }
        },

        # -------------------- 11. E-Government Services & Operations --------------------
        "E-Government Services & Operations": {
            "Enhance citizen service delivery": {
                "Service uptime (%)": "(Available / Total time) * 100",
                "Request resolution time (hours)": "Average internal",
                "Service SLA compliance (%)": "(Met / Total requests) * 100",
                "Citizen satisfaction score": "Internal survey or rating"
            },
            "Optimize digital service platforms": {
                "Platform response time (ms)": "Average internal",
                "Platform availability (%)": "(Available / Total time) * 100",
                "Error rate (%)": "(Detected errors / Total transactions) * 100",
                "Transaction processing accuracy (%)": "(Correct / Total)"
            },
            "Strengthen data privacy & security": {
                "Data breach incidents (#)": "Logged internally",
                "Encryption compliance (%)": "(Compliant / Total datasets) * 100",
                "Access audit completion (%)": "(Completed / Planned) * 100",
                "Incident resolution time (hours)": "Average internal"
            },
            "Improve internal process automation": {
                "Process automation coverage (%)": "(Automated / Total processes) * 100",
                "Automation success rate (%)": "(Successful / Total attempts) * 100",
                "Manual intervention rate (%)": "(Manual / Total processes) * 100",
                "Process cycle time reduction (%)": "(Baseline - Current) / Baseline * 100"
            },
            "Enhance internal monitoring & analytics": {
                "KPI tracking compliance (%)": "(Tracked / Planned) * 100",
                "Reporting timeliness (%)": "(On-time / Total reports) * 100",
                "Deviation detection rate (%)": "(Detected / Total incidents) * 100",
                "Internal audit completion (%)": "(Completed / Planned) * 100"
            },
            "Ensure regulatory & compliance adherence": {
                "Legal & regulatory compliance (%)": "(Compliant / Total requirements) * 100",
                "Policy review completion (%)": "(Reviewed / Planned) * 100",
                "Corrective action closure (%)": "(Closed / Total issues) * 100",
                "Documentation completeness (%)": "(Complete / Total required) * 100"
            }
        },

        # -------------------- 12. Digital Infrastructure & Cloud Management --------------------
        "Digital Infrastructure & Cloud Management": {
            "Optimize cloud resource utilization": {
                "Cloud resource usage (%)": "(Used / Allocated) * 100",
                "Idle resource rate (%)": "(Idle / Total allocated) * 100",
                "Cost efficiency (%)": "(Budgeted vs Actual) * 100",
                "Provisioning time (hours)": "Average internal"
            },
            "Enhance cloud service availability": {
                "Service uptime (%)": "(Available / Total time) * 100",
                "Incident resolution time (hours)": "Average internal",
                "SLA compliance (%)": "(Met / Total agreements) * 100",
                "Cloud downtime incidents (#)": "Logged internally"
            },
            "Strengthen cloud security & compliance": {
                "Vulnerability remediation (%)": "(Fixed / Identified) * 100",
                "Access control compliance (%)": "(Compliant / Total accounts) * 100",
                "Data encryption adherence (%)": "(Compliant / Total datasets) * 100",
                "Audit completion (%)": "(Completed / Planned) * 100"
            },
            "Improve cloud monitoring & analytics": {
                "KPI tracking completion (%)": "(Tracked / Planned) * 100",
                "Performance monitoring compliance (%)": "(Monitored / Total metrics) * 100",
                "Alert response time (hours)": "Average internal",
                "Trend analysis completion (%)": "(Completed / Planned) * 100"
            },
            "Optimize backup & disaster recovery": {
                "Backup completion rate (%)": "(Completed / Planned) * 100",
                "Recovery time objective (RTO) compliance (%)": "(Met / Total tests) * 100",
                "Recovery point objective (RPO) compliance (%)": "(Met / Total tests) * 100",
                "Restore accuracy (%)": "(Accurate / Total attempts) * 100"
            },
            "Ensure documentation & audit readiness": {
                "Internal audit completion (%)": "(Completed / Planned) * 100",
                "Regulatory adherence (%)": "(Compliant / Total checks) * 100",
                "Corrective action closure (%)": "(Closed / Total issues) * 100",
                "Documentation completeness (%)": "(Complete / Total required) * 100"
            }
        },

        # -------------------- 13. Digital Platforms & Services --------------------
        "Digital Platforms & Services": {
            "Enhance platform operations": {
                "Uptime (%)": "(Available / Total time) * 100",
                "Incident resolution time (hours)": "Average internal",
                "User request handling (%)": "(Handled / Total requests) * 100",
                "SLA compliance (%)": "(Met / Total agreements) * 100"
            },
            "Improve platform development": {
                "Feature implementation accuracy (%)": "(Implemented / Planned) * 100",
                "Code review compliance (%)": "(Reviewed / Total commits) * 100",
                "Sprint adherence (%)": "(Completed / Planned) * 100",
                "Backlog reduction rate (%)": "(Reduced / Planned) * 100"
            },
            "Strengthen platform security": {
                "Vulnerability patching rate (%)": "(Applied / Identified) * 100",
                "Access control audit completion (%)": "(Completed / Planned) * 100",
                "Security incident resolution time (hours)": "Average internal",
                "Internal security standard compliance (%)": "(Compliant / Total checks) * 100"
            },
            "Optimize content & data management": {
                "Data accuracy (%)": "(Accurate / Total entries) * 100",
                "Data completeness (%)": "(Completed / Total required) * 100",
                "ETL success rate (%)": "(Successful / Total jobs) * 100",
                "Report accuracy (%)": "(Accurate / Total reports) * 100"
            },
            "Enhance monitoring & analytics": {
                "KPI tracking compliance (%)": "(Tracked / Planned) * 100",
                "Report timeliness (%)": "(On-time / Total reports) * 100",
                "Deviation detection (%)": "(Detected / Total deviations) * 100",
                "Corrective action implementation (%)": "(Implemented / Planned) * 100"
            },
            "Ensure audit & compliance readiness": {
                "Audit completion (%)": "(Completed / Planned) * 100",
                "Policy adherence (%)": "(Compliant / Total checks) * 100",
                "Corrective action closure (%)": "(Closed / Total issues) * 100",
                "Documentation completeness (%)": "(Complete / Total required) * 100"
            }
        },

        # -------------------- 14. Emerging Technologies --------------------
        "Emerging Technologies": {
            "Enhance R&D workflow": {
                "Project proposal completion (%)": "(Completed / Planned) * 100",
                "Idea review adherence (%)": "(Followed / Total ideas) * 100",
                "Prototyping completion (%)": "(Completed / Planned) * 100",
                "Resource allocation accuracy (%)": "(Allocated / Planned) * 100"
            },
            "Optimize technology evaluation": {
                "POC success rate (%)": "(Successful / Total POCs) * 100",
                "Tech assessment completion (%)": "(Completed / Planned) * 100",
                "Adoption readiness (%)": "(Assessed / Planned) * 100",
                "Evaluation report accuracy (%)": "(Accurate / Total reports) * 100"
            },
            "Strengthen innovation governance": {
                "IP documentation completeness (%)": "(Complete / Total required) * 100",
                "Patent filing compliance (%)": "(Filed / Planned) * 100",
                "Audit adherence (%)": "(Compliant / Total audits) * 100",
                "Protection incident rate (#)": "Logged internally"
            },
            "Manage pilot testing": {
                "Test completion (%)": "(Completed / Planned) * 100",
                "Defect detection rate (%)": "(Detected / Planned) * 100",
                "Iteration adherence (%)": "(Followed / Planned) * 100",
                "Corrective action implementation (%)": "(Implemented / Planned) * 100"
            },
            "Improve tech adoption": {
                "Stakeholder readiness (%)": "(Completed / Planned) * 100",
                "Integration success (%)": "(Successful / Planned) * 100",
                "User acceptance testing completion (%)": "(Completed / Planned) * 100",
                "Feedback integration (%)": "(Implemented / Planned) * 100"
            },
            "Ensure compliance & security": {
                "Regulatory adherence (%)": "(Compliant / Total checks) * 100",
                "Cybersecurity compliance (%)": "(Compliant / Total assessments) * 100",
                "Documentation completeness (%)": "(Complete / Total required) * 100",
                "Audit closure (%)": "(Closed / Planned) * 100"
            }
        },

        # -------------------- 15. Telecommunications --------------------
        "Telecommunications": {
            "Enhance network service quality": {
                "Network availability (%)": "(Available / Total time) * 100",
                "Incident resolution time (hours)": "Average internal",
                "Customer SLA compliance (%)": "(Met / Total agreements) * 100",
                "Downtime incidents (#)": "Logged internally"
            },
            "Optimize telecom infrastructure": {
                "Bandwidth utilization (%)": "(Used / Total allocated) * 100",
                "Equipment uptime (%)": "(Operational / Total equipment) * 100",
                "Maintenance adherence (%)": "(On-time / Planned) * 100",
                "Capacity forecast accuracy (%)": "(Actual vs planned usage)"
            },
            "Strengthen security & compliance": {
                "Vulnerability remediation (%)": "(Fixed / Identified) * 100",
                "Access control compliance (%)": "(Compliant / Total accounts) * 100",
                "Regulatory adherence (%)": "(Compliant / Total checks) * 100",
                "Audit completion (%)": "(Completed / Planned) * 100"
            },
            "Improve service monitoring & analytics": {
                "KPI tracking compliance (%)": "(Tracked / Planned) * 100",
                "Alert response time (hours)": "Average internal",
                "Trend analysis completion (%)": "(Completed / Planned) * 100",
                "Deviation detection (%)": "(Detected / Total deviations) * 100"
            },
            "Enhance customer support operations": {
                "Ticket resolution time (hours)": "Average internal",
                "SLA compliance (%)": "(Met / Total requests) * 100",
                "Backlog reduction (%)": "(Reduced / Planned) * 100",
                "Satisfaction score": "Internal survey"
            },
            "Ensure documentation & process compliance": {
                "Internal documentation completeness (%)": "(Complete / Total required) * 100",
                "Process adherence (%)": "(Followed / Total planned) * 100",
                "Corrective action closure (%)": "(Closed / Total issues) * 100",
                "Audit readiness (%)": "(Completed / Planned) * 100"
            }
        },

        # -------------------- 16. Cybersecurity --------------------
        "Cybersecurity": {
            "Enhance threat detection & response": {
                "Incident detection rate (%)": "(Detected / Total simulated threats) * 100",
                "Average response time (minutes)": "Internal measurement",
                "Alert triage compliance (%)": "(Followed / Total alerts) * 100",
                "Threat classification accuracy (%)": "(Correct / Total threats) * 100"
            },
            "Strengthen vulnerability management": {
                "Vulnerability remediation (%)": "(Fixed / Identified) * 100",
                "Patch deployment adherence (%)": "(Applied / Planned) * 100",
                "Critical issue closure time (hours)": "Average internal",
                "Risk assessment completion (%)": "(Completed / Planned) * 100"
            },
            "Optimize access control & identity management": {
                "User access review (%)": "(Reviewed / Total users) * 100",
                "Unauthorized access attempts (#)": "Logged internally",
                "Role assignment accuracy (%)": "(Correct / Total roles) * 100",
                "Policy compliance (%)": "(Compliant / Total checks) * 100"
            },
            "Improve incident response & recovery": {
                "Incident resolution time (hours)": "Average internal",
                "Post-incident review completion (%)": "(Completed / Planned) * 100",
                "Root cause analysis adherence (%)": "(Followed / Total incidents) * 100",
                "Mitigation implementation (%)": "(Implemented / Planned) * 100"
            },
            "Enhance risk monitoring & analytics": {
                "Risk review completion (%)": "(Completed / Planned) * 100",
                "Risk mitigation follow-up (%)": "(Followed / Planned) * 100",
                "Risk register update frequency": "Times per month",
                "Key risk indicator compliance (%)": "(Monitored / Total indicators) * 100"
            },
            "Ensure cybersecurity awareness & training": {
                "Training completion (%)": "(Completed / Required) * 100",
                "Phishing drill pass rate (%)": "(Passed / Total staff) * 100",
                "Policy acknowledgment (%)": "(Acknowledged / Total staff) * 100",
                "Behavior audit compliance (%)": "(Compliant / Audited activities) * 100"
            }
        },
    },

    "Learning & Growth Perspective": {
        **GENERIC_LEARNING_AND_GROWTH_PERSPECTIVE["Learning & Growth Perspective"],
    },
}
