from management_project.services.strategy_hierarchy.finance_perspective import GENERIC_FINANCE_PERSPECTIVE
from management_project.services.strategy_hierarchy.customer_perspective import GENERIC_CUSTOMER_PERSPECTIVE

RETAIL_PERSPECTIVE = {
    # -------------------- Financial Perspective --------------------
    "Financial Perspective": {
        **GENERIC_FINANCE_PERSPECTIVE["Financial Perspective"],

        # Retail-focused financial development
        "Retail Economic Development": {
            "Support Local Entrepreneurship": {
                "New retail startups funded": "Number of local startups financially supported",
                "Revenue from supported startups ($)": "Revenue generated by funded startups",
                "Startup survival rate (%)": "Startups still operational after 1 year / Total funded * 100",
                "Jobs created by startups": "Number of new jobs generated by supported startups"
            },
            "Create Employment Opportunities": {
                "Retail jobs created": "Number of direct retail jobs created",
                "Youth employment (%)": "Number of youth employed / Total new hires * 100",
                "Employee retention rate (%)": "Employees retained / Total hired * 100",
                "Training programs for workforce (#)": "Number of training programs conducted"
            },
            "Support Rural & Regional Retail Development": {
                "Revenue from rural outlets ($)": "Revenue generated in rural areas",
                "Rural jobs created": "Number of jobs created in rural outlets",
                "Rural outlet growth (%)": "(Current outlets - Previous) / Previous * 100",
                "Rural citizen satisfaction (%)": "Average satisfaction score from rural citizens"
            },
            "Enhance SME & Local Supplier Participation": {
                "SME suppliers engaged": "Number of SMEs supplying products/services",
                "Procurement from SMEs ($)": "Total purchases from SMEs",
                "SME revenue growth (%)": "(Current SME revenue - Previous) / Previous * 100",
                "SME satisfaction rate (%)": "Average satisfaction score from SME surveys"
            }
        },



        # Trade & Export Development
        "International Trade & Export Development": {
            "Increase export revenue": {
                "Export sales ($)": "Revenue from exports",
                "Export growth rate (%)": "(Current - Previous) / Previous * 100",
                "New international markets entered (#)": "Count of countries entered",
                "Export customer satisfaction (%)": "Survey score of international clients"
            },
            "Enhance product competitiveness": {
                "Compliance with international standards (%)": "Products meeting global standards / Total products * 100",
                "Product certifications obtained (#)": "Number of certifications",
                "Export quality defect rate (%)": "Defective exports / Total exports * 100",
                "International client retention (%)": "Returning international buyers / Total buyers * 100"
            },
            "Develop trade partnerships": {
                "Trade agreements signed (#)": "Number of MOUs or agreements",
                "Revenue from partner channels ($)": "Revenue through partners",
                "Joint marketing initiatives (#)": "Number of campaigns with partners",
                "Partner satisfaction (%)": "Survey score of trade partners"
            },
            "Strengthen international compliance": {
                "Customs clearance efficiency (%)": "On-time customs clearance / Total shipments * 100",
                "Export documentation accuracy (%)": "Accurate documents / Total documents * 100",
                "Tariff compliance rate (%)": "Compliant shipments / Total shipments * 100",
                "Reduction in export penalties ($)": "Previous penalties - Current penalties"
            }
        },

        # Trade & Market Infrastructure
        "Trade & Market Infrastructure": {
            "Improve retail logistics & distribution": {
                "Distribution network coverage (%)": "Stores or outlets covered / Total planned * 100",
                "Delivery lead time (days)": "Average days to deliver products",
                "Logistics cost reduction (%)": "(Previous - Current) / Previous * 100",
                "On-time delivery rate (%)": "Deliveries on schedule / Total deliveries * 100"
            },
            "Enhance market access & storage facilities": {
                "New retail infrastructure established (#)": "Number of new stores, warehouses, or market hubs",
                "Storage capacity utilization (%)": "Used capacity / Total capacity * 100",
                "Citizen access improvement (%)": "(Current citizens served - Previous) / Previous * 100",
                "Maintenance efficiency (%)": "Properly maintained infrastructure / Total * 100"
            },
            "Government program participation": {
                "Gov-supported retail initiatives (#)": "Number of programs supported",
                "Revenue from gov-supported initiatives ($)": "Revenue generated",
                "Compliance with gov standards (%)": "Initiatives meeting regulations / Total * 100",
                "Impact on local employment (#)": "Jobs created via gov programs"
            },
            "Strengthen transport & market connectivity": {
                "Retail hubs connected (#)": "Number of markets connected via infrastructure",
                "Average delivery time (days)": "Days for goods to reach retail hub",
                "Transport cost reduction (%)": "(Previous - Current) / Previous * 100",
                "Distribution reliability (%)": "Deliveries completed without disruption / Total deliveries * 100"
            }
        },

        # Retail Economy Development
        "Retail Economy Development": {
            "Increase Retail Sector Contribution to GDP": {
                "Retail GDP contribution ($)": "Value added by retail sector to national GDP",
                "Retail growth rate (%)": "(Current retail GDP - Previous) / Previous * 100",
                "Sector share of total GDP (%)": "Retail GDP / Total GDP * 100",
                "Retail tax revenue contribution ($)": "Taxes collected from retail activities"
            },
            "Promote Employment through Retail Expansion": {
                "Jobs created in retail (#)": "Number of new jobs in retail sector",
                "Youth employment (%)": "Number of youth employed / Total new hires * 100",
                "Female workforce participation (%)": "Number of women employed / Total new hires * 100",
                "Employee retention rate (%)": "Employees retained / Total hired * 100"
            },
            "Support SME Participation & Growth": {
                "SMEs engaged in retail (#)": "Number of SMEs participating in retail",
                "Revenue generated by SMEs ($)": "Income generated by SMEs in retail",
                "SME survival rate (%)": "SMEs still operational after 1 year / Total engaged * 100",
                "SME access to finance (%)": "SMEs receiving loans / Total SMEs * 100"
            },
            "Enhance Regional & Rural Retail Economy": {
                "Retail outlets in underserved regions (#)": "Number of stores opened in rural or underserved areas",
                "Revenue from regional retail ($)": "Income generated from regional outlets",
                "Regional employment (#)": "Jobs created in rural and regional areas",
                "Citizen access to retail goods (%)": "Population served / Total population * 100"
            },
            "Promote Inclusive Retail Participation": {
                "Revenue from low-income communities ($)": "Income generated from underserved areas",
                "Number of inclusive retail initiatives (#)": "Programs targeting inclusion in retail",
                "Citizen satisfaction (%)": "Survey score from underserved communities",
                "Increase in retail customer base (%)": "(Current - Previous) / Previous * 100"
            }
        },
    },

    # -------------------- Customer Perspective --------------------
    "Customer Perspective": {
        **GENERIC_CUSTOMER_PERSPECTIVE['Customer Perspective'],
# Consumer Protection & Product Standards
        "Consumer Protection & Product Standards": {
            "Ensure product safety & compliance": {
                "Products meeting safety standards (%)": "Compliant products / Total products * 100",
                "Safety incidents reported (#)": "Count of product-related incidents",
                "Corrective actions implemented (#)": "Number of actions taken",
                "Audit success rate (%)": "Passed audits / Total audits * 100"
            },
            "Promote sustainable & certified products": {
                "Sustainable product ratio (%)": "Eco-friendly products / Total products * 100",
                "Certified products (#)": "Number of certified products",
                "Citizen satisfaction with product quality (%)": "Survey score",
                "Reduction in defective products (%)": "(Previous - Current) / Previous * 100"
            },
            "Enhance food & essential goods quality": {
                "Inspected products (%)": "Products inspected / Total products * 100",
                "Food safety compliance (%)": "Compliant food products / Total food products * 100",
                "Recall incidents (#)": "Number of product recalls",
                "Consumer complaint resolution (%)": "Resolved complaints / Total complaints * 100"
            },
            "Promote standardized packaging & labeling": {
                "Products with compliant labeling (%)": "Labeled products / Total products * 100",
                "Packaging waste reduction (%)": "(Previous waste - Current) / Previous * 100",
                "Consumer satisfaction with labeling (%)": "Survey score",
                "Incidents due to mislabeling (#)": "Count of reported mislabeling"
            }
        },

        # Price & Affordability Management
        "Price & Affordability Management": {
            "Ensure Affordable Consumer Prices": {
                "Price compliance rate (%)": "Products sold within regulated price limits / Total products * 100",
                "Average price deviation ($)": "Average difference from official price",
                "Price monitoring coverage (%)": "Products monitored / Total products * 100",
                "Consumer complaints on pricing (#)": "Number of pricing complaints received"
            },
            "Regulate Essential Goods Pricing": {
                "Essential goods compliance (%)": "Essential products within set price range / Total essential products * 100",
                "Price fluctuation reduction (%)": "(Previous price variance - Current variance) / Previous variance * 100",
                "Consumer affordability index": "Average household affordability score",
                "Enforcement actions taken (#)": "Number of regulatory actions for price violations"
            },
            "Promote Transparent Pricing": {
                "Products with visible pricing (%)": "Labeled products with clear prices / Total products * 100",
                "Online price accuracy (%)": "Digital platform prices matching official prices / Total products * 100",
                "Price dispute resolution time (days)": "Average days to resolve price complaints",
                "Consumer trust index": "Survey score on perceived fair pricing"
            },
            "Encourage Competitive Pricing & Market Fairness": {
                "Market competition index": "Number of suppliers per product category",
                "Anti-monopoly investigations (#)": "Investigations conducted",
                "Competitive pricing compliance (%)": "Products priced competitively / Total products * 100",
                "Price-related legal cases (#)": "Number of legal cases filed for unfair pricing"
            }
        },

        # Digital Government Retail Platforms
        "Digital Government Retail Platforms": {
            "E-service adoption": {
                "Digital platform usage (%)": "Users on e-platform / Total citizens * 100",
                "Online payment transactions (#)": "Number of transactions through platform",
                "Digital citizen satisfaction (%)": "Survey score",
                "Portal uptime (%)": "System availability / Total time * 100"
            },
            "Government data & reporting": {
                "Timely reports submitted (%)": "Reports delivered on schedule / Total reports * 100",
                "Data accuracy (%)": "Verified reports / Total reports * 100",
                "Digital monitoring coverage (%)": "Retail outlets monitored digitally / Total outlets * 100",
                "Issue resolution via platform (#)": "Citizen complaints resolved digitally"
            },
            "Digital training & awareness": {
                "Citizens trained (#)": "Number of citizens trained on e-services",
                "Training completion rate (%)": "Completed trainings / Total enrolled * 100",
                "Digital literacy improvement (%)": "Post-training survey improvement",
                "Feedback implementation rate (%)": "Suggestions implemented / Total feedback * 100"
            },
            "Promote e-commerce adoption for SMEs": {
                "SMEs on e-platform (#)": "Number of SMEs using digital platform",
                "Revenue from digital sales ($)": "Sales revenue generated online",
                "Digital SME satisfaction (%)": "Survey score",
                "Growth in online transactions (%)": "(Current - Previous) / Previous * 100"
            }
        },
    }
}
