from management_project.services.strategy_hierarchy.finance_perspective import GENERIC_FINANCE_PERSPECTIVE

RETAIL_PERSPECTIVE = {
    "Financial Perspective": {
        # import the generic financial perspective
        **GENERIC_FINANCE_PERSPECTIVE["Financial Perspective"],

        # -------------------- Retail Economic Development --------------------
        "Retail Economic Development": {
            "Support Local Entrepreneurship": {
                "New retail startups funded": "Number of local startups financially supported",
                "Revenue from supported startups ($)": "Revenue generated by funded startups",
                "Startup survival rate (%)": "Startups still operational after 1 year / Total funded * 100",
                "Jobs created by startups": "Number of new jobs generated by supported startups"
            },
            "Enhance Supply Chain & SME Participation": {
                "SME suppliers engaged": "Number of SMEs supplying products/services",
                "Procurement from SMEs ($)": "Total purchases from SMEs",
                "SME revenue growth (%)": "(Current SME revenue - Previous) / Previous * 100",
                "SME satisfaction rate (%)": "Average satisfaction score from SME surveys"
            },
            "Create Employment Opportunities": {
                "Retail jobs created": "Number of direct retail jobs created",
                "Part-time employment growth (%)": "(Current - Previous) / Previous * 100",
                "Youth employment (%)": "Number of youth employed / Total new hires * 100",
                "Employee retention rate (%)": "Employees retained / Total hired * 100"
            },
            "Promote Skills & Workforce Development": {
                "Training programs conducted": "Number of skill development programs",
                "Employees trained": "Total number of employees trained",
                "Training completion rate (%)": "Completed trainings / Total enrolled * 100",
                "Workforce productivity improvement (%)": "Revenue per employee growth %"
            },
            "Encourage Economic Inclusion": {
                "Revenue from underserved communities ($)": "Revenue generated from low-income areas",
                "Underserved customer growth (%)": "New underserved customers / Previous total * 100",
                "Inclusive retail outlets (#)": "Number of stores in underserved regions",
                "Community engagement initiatives (#)": "Number of programs promoting inclusion"
            },
            "Promote Innovation & Digital Transformation": {
                "Investment in retail tech ($)": "Amount invested in retail technology",
                "New digital solutions deployed": "Number of digital tools implemented",
                "Online retail revenue growth (%)": "(Current - Previous) / Previous * 100",
                "Customer adoption of digital solutions (%)": "Digital users / Total customers * 100"
            },
            "Support Rural & Regional Development": {
                "Revenue from rural outlets ($)": "Revenue generated in rural areas",
                "Rural jobs created": "Number of jobs created in rural outlets",
                "Rural outlet growth (%)": "(Current outlets - Previous) / Previous * 100",
                "Rural customer satisfaction (%)": "Average satisfaction score from rural customers"
            },
            "Promote Local Product Sourcing": {
                "Local products purchased ($)": "Value of products sourced locally",
                "Local supplier count": "Number of local suppliers engaged",
                "Local sourcing ratio (%)": "Local purchases / Total purchases * 100",
                "Contribution to local economy ($)": "Estimated economic impact of local sourcing"
            },
            "Facilitate Retail Entrepreneurship Training": {
                "Entrepreneurship programs (#)": "Number of training programs conducted",
                "Participants trained": "Total number of participants",
                "Participants starting businesses (#)": "Number of participants who launched retail businesses",
                "Training satisfaction (%)": "Average satisfaction score from participants"
            },
            "Promote Sustainable Economic Growth": {
                "Revenue growth in strategic regions (%)": "(Current - Previous) / Previous * 100",
                "Job creation in strategic regions": "Number of jobs created",
                "Investment in community projects ($)": "Total funding allocated to local development",
                "Small business revenue growth (%)": "(Current - Previous) / Previous * 100"
            }
        }
    }
}
