from management_project.services.strategy_hierarchy.finance_perspective import GENERIC_FINANCE_PERSPECTIVE

TELECOMMUNICATION_PERSPECTIVE = {
    "Financial Perspective": {
        # import the generic financial perspective
        **GENERIC_FINANCE_PERSPECTIVE["Financial Perspective"],

        # -------------------- Telecom Economic Development (Best Practice Context) --------------------
        "Telecom Economic Development": {
            "Expand Network & Connectivity": {
                "Network towers deployed": "Number of 4G/5G towers built or upgraded",
                "Broadband coverage (%)": "Population covered by network / Total population * 100",
                "Rural network expansion (%)": "New rural coverage / Previous rural coverage * 100",
                "Revenue from newly connected areas ($)": "Revenue generated from new network regions"
            },
            "Promote Digital Inclusion": {
                "Underserved population subscribers (#)": "New subscribers in low-income or remote areas",
                "Digital literacy programs (#)": "Number of digital training programs conducted",
                "Mobile internet adoption rate (%)": "Mobile internet users / Total population * 100",
                "Revenue from underserved areas ($)": "Revenue generated from low-income or rural users"
            },
            "Support Telecom Startups & Entrepreneurship": {
                "Startups funded (#)": "Number of local tech or telecom startups supported financially",
                "Revenue from supported startups ($)": "Revenue generated by funded startups",
                "Startup survival rate (%)": "Startups still operational after 12 months / Total funded * 100",
                "Jobs created by startups": "Number of direct jobs generated by supported startups"
            },
            "Enhance Workforce Skills & Training": {
                "Training programs conducted (#)": "Number of technical and soft skills programs",
                "Employees trained": "Total number of employees trained",
                "Training completion rate (%)": "Completed trainings / Total enrolled * 100",
                "Employee productivity improvement (%)": "Revenue per employee growth %"
            },
            "Create Employment Opportunities": {
                "Telecom jobs created": "Number of direct jobs created in operations and support",
                "Youth employment (%)": "Youth employed / Total new hires * 100",
                "Part-time employment growth (%)": "(Current part-time jobs - Previous) / Previous * 100",
                "Employee retention rate (%)": "Employees retained / Total hired * 100"
            },
            "Support SME & Vendor Participation": {
                "SME vendors engaged": "Number of SMEs supplying telecom equipment or services",
                "Procurement from SMEs ($)": "Total procurement spend with SMEs",
                "SME revenue growth (%)": "(Current SME revenue - Previous) / Previous * 100",
                "SME satisfaction score": "Average vendor satisfaction rating"
            },
            "Encourage Innovation & Digital Transformation": {
                "Investment in telecom technology ($)": "Capital allocated to new digital and network technologies",
                "Digital solutions deployed (#)": "Number of new digital services or platforms launched",
                "Revenue from digital services ($)": "Revenue from OTT, apps, IoT, and digital services",
                "Customer digital adoption rate (%)": "Active users of digital solutions / Total customer base * 100"
            },
            "Support Rural & Regional Development": {
                "Revenue from rural regions ($)": "Revenue from rural network and services",
                "Rural jobs created": "Number of jobs created in rural regions",
                "Rural coverage expansion (%)": "New rural coverage / Previous rural coverage * 100",
                "Customer satisfaction in rural areas (%)": "Average satisfaction score from rural users"
            },
            "Promote Local Content & Services": {
                "Local content partnerships (#)": "Number of local content providers partnered",
                "Revenue from local services ($)": "Revenue generated from local content offerings",
                "Local service adoption (%)": "Users of local content / Total users * 100",
                "Contribution to local economy ($)": "Estimated economic impact of local content and partnerships"
            },
            "Encourage Sustainable Economic Growth": {
                "Revenue growth in strategic regions (%)": "(Current - Previous) / Previous * 100",
                "Job creation in strategic regions": "Number of new jobs created in target areas",
                "Investment in community development ($)": "Funding allocated to community programs",
                "Small business revenue growth (%)": "(Current - Previous) / Previous * 100"
            }
        }
    }
}
