
from management_project.services.strategy_hierarchy.finance_perspective import GENERIC_FINANCE_PERSPECTIVE
from management_project.services.strategy_hierarchy.customer_perspective import GENERIC_CUSTOMER_PERSPECTIVE

TRANSPORT_AND_LOGISTICS_PERSPECTIVE = {
    "Financial Perspective": {
        # -------------------- Generic Finance --------------------
        **GENERIC_FINANCE_PERSPECTIVE["Financial Perspective"],

        # -------------------- Route Revenue & Profitability Management --------------------
        "Route Revenue & Profitability Management": {
            "Maximize Route Revenue": {
                "Total route revenue ($)": "Sum of revenues generated by all routes",
                "Average revenue per route ($)": "Total route revenue / Number of active routes",
                "Revenue per km of route ($)": "Total revenue / Total route kilometers",
                "New profitable routes added (#)": "Count of newly launched profitable routes"
            },
            "Optimize Route Profit": {
                "Profit per route ($)": "Total revenue per route - Total cost per route",
                "Route profitability ratio (%)": "(Profitable routes / Total routes) * 100",
                "Top 10 route revenue contribution (%)": "(Revenue from top 10 routes / Total revenue) * 100",
                "Unprofitable routes reduced (%)": "(Previous - Current unprofitable routes) / Previous * 100"
            },
            "Enhance Route Efficiency": {
                "Cost per route km ($)": "Total operating cost / Total route kilometers",
                "Revenue per trip ($)": "Total route revenue / Total trips",
                "Load factor per route (%)": "(Occupied capacity / Available capacity) * 100",
                "Route utilization rate (%)": "(Active operating days / Total available days) * 100"
            },
            "Route Network Optimization": {
                "Route expansion efficiency (%)": "Revenue growth from new routes / Investment in expansion * 100",
                "Average distance per profitable route (km)": "Total distance of profitable routes / Count",
                "Route overlap reduction (%)": "(Previous overlapping routes - Current) / Previous * 100",
                "Route contribution to total profit (%)": "(Route profit / Total company profit) * 100"
            }
        },

        # -------------------- Passenger Revenue & Profitability Management --------------------
        "Passenger Revenue & Profitability Management": {
            "Maximize Passenger Revenue": {
                "Passenger fare revenue growth (%)": "((Current passenger revenue - Previous) / Previous) * 100",
                "Revenue per passenger/km": "Total passenger revenue / Total passenger kilometers",
                "Average revenue per passenger trip": "Total passenger trip revenue / Number of trips",
                "Load factor revenue contribution (%)": "(Revenue from full occupancy / Total passenger revenue) * 100"
            },
            "Maximize Passenger Profit": {
                "Passenger profit margin (%)": "(Passenger revenue - Passenger total costs) / Passenger revenue * 100",
                "Net profit per passenger trip": "Total passenger profit / Number of trips",
                "Profit per passenger/km": "Passenger profit / Total passenger kilometers",
                "High-margin route contribution (%)": "(Revenue from high-margin routes / Total passenger revenue) * 100"
            },
            "Enhance Passenger Revenue Diversification": {
                "Revenue from value-added passenger services (%)": "(Revenue from auxiliary services / Total passenger revenue) * 100",
                "Contract vs spot passenger revenue ratio": "(Contract passenger revenue / Spot passenger revenue) * 100",
                "Seasonal passenger revenue optimization index": "Revenue stability across peak and off-peak periods",
                "Multi-modal passenger revenue contribution (%)": "(Revenue from intermodal passenger services / Total passenger revenue) * 100"
            },
            "Optimize Passenger Pricing": {
                "Dynamic passenger pricing effectiveness": "Revenue improvement from dynamic passenger pricing",
                "Passenger contract rate compliance (%)": "(Contracts with agreed rates / Total passenger contracts) * 100",
                "Passenger fuel surcharge recovery rate (%)": "Percentage of fuel cost increases recovered through surcharges",
                "Passenger price premium achievement (%)": "(Actual fare - Market average fare) / Market average fare * 100"
            }
        },

        # -------------------- Freight Revenue & Profitability Management --------------------
        "Freight Revenue & Profitability Management": {
            "Maximize Freight Revenue": {
                "Freight revenue growth (%)": "((Current freight revenue - Previous) / Previous) * 100",
                "Revenue per ton/km": "Total freight revenue / Total ton kilometers",
                "Average revenue per freight trip": "Total freight trip revenue / Number of trips",
                "On-time delivery revenue contribution (%)": "(Revenue from on-time deliveries / Total freight revenue) * 100"
            },
            "Maximize Freight Profit": {
                "Freight profit margin (%)": "(Freight revenue - Freight total costs) / Freight revenue * 100",
                "Net profit per freight trip": "Total freight profit / Number of trips",
                "Profit per ton/km": "Freight profit / Total ton kilometers",
                "High-margin freight route contribution (%)": "(Revenue from high-margin freight routes / Total freight revenue) * 100"
            },
            "Enhance Freight Revenue Diversification": {
                "Revenue from value-added freight services (%)": "(Revenue from logistics services / Total freight revenue) * 100",
                "Contract vs spot freight revenue ratio": "(Contract freight revenue / Spot freight revenue) * 100",
                "Seasonal freight revenue optimization index": "Revenue stability across high/low demand seasons",
                "Multi-modal freight revenue contribution (%)": "(Revenue from intermodal freight services / Total freight revenue) * 100"
            },
            "Optimize Freight Pricing": {
                "Dynamic freight pricing effectiveness": "Revenue improvement from dynamic pricing",
                "Freight contract rate compliance (%)": "(Contracts with agreed rates / Total freight contracts) * 100",
                "Freight fuel surcharge recovery rate (%)": "Percentage of fuel cost increases recovered",
                "Freight price premium achievement (%)": "(Actual freight rate - Market average) / Market average * 100"
            }
        },

        # -------------------- Transport Economic Growth --------------------
        "Transport Economic Growth": {
            "Increase Transport GDP Contribution": {
                "Transport GDP share (%)": "Transport sector GDP / Total national GDP * 100",
                "Annual transport GDP growth (%)": "(Current - Previous) / Previous * 100",
                "Transport value-added ($)": "Value added by transport and logistics sector",
                "GDP elasticity to transport investment": "Change in GDP / Change in transport investment"
            },
            "Boost Export-Import Logistics Efficiency": {
                "Logistics cost as % of trade value": "(Logistics cost / Total trade value) * 100",
                "Average export delivery time (days)": "Mean time to deliver exports to destination",
                "Port & border clearance efficiency (%)": "(Actual clearance / Planned clearance) * 100",
                "Trade facilitation impact index": "Efficiency score based on international trade ease metrics"
            },
            "Enhance Transport Infrastructure Productivity": {
                "Infrastructure ROI (%)": "(Revenue or benefit - Cost) / Cost * 100",
                "Transport investment utilization rate (%)": "(Funds used / Funds allocated) * 100",
                "Road/rail network capacity utilization (%)": "Actual transport volume / Design capacity * 100",
                "Public-private partnership leverage ratio": "Private investment / Total transport investment * 100"
            },
            "Promote Regional Economic Linkages": {
                "Regional connectivity index": "Weighted index of inter-regional connectivity",
                "Inter-regional trade volume growth (%)": "(Current trade - Previous) / Previous * 100",
                "Transport-driven regional GDP growth (%)": "Regional GDP increase due to transport development",
                "Revenue from regional logistics hubs ($)": "Earnings generated by regional transport centers"
            }
        },

        # -------------------- Transport Economic Development --------------------
        "Transport Economic Development": {
            "Support Local Entrepreneurship & SMEs": {
                "SME participation in logistics (%)": "SMEs in transport value chain / Total firms * 100",
                "SME revenue growth (%)": "(Current SME revenue - Previous) / Previous * 100",
                "Local supplier spending ratio (%)": "Spending on local suppliers / Total procurement * 100",
                "SME job creation (#)": "New jobs generated by SME logistics providers"
            },
            "Create Employment Opportunities": {
                "Total jobs created (#)": "Direct + indirect jobs created by transport projects",
                "Youth employment share (%)": "Youth jobs / Total jobs * 100",
                "Female employment ratio (%)": "Women employed / Total workforce * 100",
                "Employee retention rate (%)": "Retained staff / Total staff * 100"
            },
            "Promote Green Transport Growth": {
                "Green fleet share (%)": "Electric or hybrid vehicles / Total fleet * 100",
                "Carbon emission reduction (%)": "(Previous - Current emissions) / Previous * 100",
                "Revenue from sustainable services ($)": "Revenue from eco-friendly logistics",
                "Green investment ratio (%)": "Green investments / Total capital investment * 100"
            },
            "Enhance Innovation & Digitalization": {
                "Investment in transport ICT ($)": "Amount invested in digital systems",
                "Digital adoption rate (%)": "Digital transactions / Total transactions * 100",
                "Smart logistics ROI (%)": "(Savings from digitalization / Cost of tech) * 100",
                "AI or IoT-enabled assets (%)": "Number of smart-enabled vehicles or hubs / Total assets * 100"
            }
        },
    },

"Customer Perspective": {
        **GENERIC_CUSTOMER_PERSPECTIVE["Customer Perspective"],

        # -------------------- 1. Accessibility & Connectivity --------------------
        "Accessibility & Connectivity": {
            "Expand Transport Network Coverage": {
                "Population within 5 km of access point (%)": "(Population near routes / Total population) * 100",
                "Public transport network coverage (km)": "Total operational route length",
                "Rural accessibility index": "Access in rural / Access in urban * 100",
                "Connectivity score": "Index combining route availability, frequency, and access time"
            },
            "Enhance Last-Mile Connectivity": {
                "Average last-mile travel time (minutes)": "Average passenger time to reach main station",
                "Feeder route availability (%)": "Feeder routes operating / Total required * 100",
                "Passenger satisfaction with last-mile (%)": "Survey score on convenience of last-mile",
                "Coverage of integrated feeder systems (%)": "Feeder routes linked to main routes / Total * 100"
            },
            "Increase Regional & Cross-Border Access": {
                "Regional route integration index": "Percentage of connected regional transport routes",
                "Cross-border transport agreements (#)": "Active cooperation agreements signed",
                "Freight network accessibility (%)": "Regions covered by logistics corridors / Total * 100",
                "Passenger intercity access time (hours)": "Average intercity travel time"
            },
            "Promote Inclusive Accessibility": {
                "Accessibility for persons with disabilities (%)": "Accessible stops / Total stops * 100",
                "Elderly-friendly services coverage (%)": "Routes with elderly assistance features / Total * 100",
                "Low-income affordability access (%)": "Affordable routes / Total * 100",
                "Inclusive infrastructure compliance (%)": "Accessible stations / Total * 100"
            }
        },

        # -------------------- 2. Service Quality --------------------
        "Service Quality": {
            "Enhance Reliability & Consistency": {
                "On-time performance (%)": "(On-time services / Total services) * 100",
                "Service cancellations (%)": "(Cancelled / Scheduled) * 100",
                "Average delay duration (minutes)": "Mean delay per trip",
                "Consistency index": "Variation in performance across routes"
            },
            "Improve Comfort & Convenience": {
                "Passenger comfort satisfaction (%)": "Survey-based comfort score",
                "Seating availability (%)": "Passengers with seats / Total passengers * 100",
                "Cleanliness score": "Average station & vehicle cleanliness rating",
                "Trip convenience rating": "Survey score on trip ease and accessibility"
            },
            "Strengthen Punctuality & Frequency": {
                "Service frequency per route (trips/day)": "Average trips per route daily",
                "Peak hour reliability (%)": "(On-time trips during peak / Total peak trips) * 100",
                "Customer satisfaction with schedule (%)": "Survey rating on schedule reliability",
                "Average waiting time (minutes)": "Mean passenger wait time"
            },
            "Improve Maintenance & Asset Availability": {
                "Vehicle availability rate (%)": "(Operational vehicles / Total fleet) * 100",
                "Maintenance downtime (hours)": "Average downtime per vehicle",
                "Asset reliability index": "Mean time between failures",
                "Maintenance completion compliance (%)": "(On-time maintenance / Total scheduled) * 100"
            }
        },

        # -------------------- 3. Safety & Security --------------------
        "Safety & Security": {
            "Enhance Passenger Safety": {
                "Accidents per 100,000 trips": "(Accidents / Trips) * 100,000",
                "Passenger safety satisfaction (%)": "Survey rating on perceived safety",
                "Emergency response time (minutes)": "Average time to respond to incidents",
                "Safety audits completed (%)": "(Audited units / Total units) * 100"
            },
            "Improve Infrastructure Safety": {
                "Infrastructure inspection compliance (%)": "(Completed inspections / Planned) * 100",
                "Defect resolution rate (%)": "(Issues resolved / Reported) * 100",
                "Safety investment ratio (%)": "Safety-related spend / Total budget * 100",
                "Road or rail hazard index": "Weighted score of critical risk points"
            },
            "Reduce Accident & Incident Frequency": {
                "Accident reduction (%)": "(Previous - Current) / Previous * 100",
                "Fatality rate per million passengers": "Total fatalities / Passengers * 1,000,000",
                "Workplace safety incidents (#)": "Accidents involving staff or operators",
                "Safety compliance training completion (%)": "Trained staff / Total staff * 100"
            },
            "Strengthen Security & Crime Prevention": {
                "Security incidents per 1,000 trips": "Reported incidents / Total trips * 1,000",
                "CCTV and surveillance coverage (%)": "Areas under CCTV / Total facilities * 100",
                "Passenger confidence in security (%)": "Survey rating on security presence",
                "Law enforcement cooperation programs (#)": "Joint patrol or safety programs established"
            }
        },

        # -------------------- 4. Affordability & Value --------------------
        "Affordability & Value": {
            "Maintain Affordable Pricing": {
                "Fare affordability index": "Average fare / Median income * 100",
                "Fare increase rate (%)": "(Current fare - Previous) / Previous * 100",
                "Subsidized passengers (%)": "Subsidized tickets / Total tickets * 100",
                "Public satisfaction with pricing (%)": "Survey rating on fare fairness"
            },
            "Promote Transparent Pricing": {
                "Price visibility compliance (%)": "(Displayed fares / Total) * 100",
                "Billing error rate (%)": "(Incorrect charges / Total charges) * 100",
                "Complaint rate on fares (%)": "(Fare complaints / Total complaints) * 100",
                "Online fare publication rate (%)": "(Updated online fares / Total required) * 100"
            },
            "Encourage Competitive Pricing": {
                "Fare competitiveness index": "Average fare / Market benchmark fare * 100",
                "Demand elasticity to fare": "Change in demand / Change in price * 100",
                "Revenue from dynamic pricing ($)": "Revenue through flexible pricing systems",
                "Public satisfaction with fare options (%)": "Survey score on pricing diversity"
            },
            "Improve Value for Money": {
                "Customer value perception (%)": "Survey-based value rating",
                "Service quality-to-price ratio": "Service score / Fare index",
                "Repeat ridership rate (%)": "Returning passengers / Total passengers * 100",
                "Loyalty program membership (%)": "Registered loyalty users / Total passengers * 100"
            }
        },

        # -------------------- 5. Customer Experience & Engagement --------------------
        "Customer Experience & Engagement": {
            "Enhance Passenger Satisfaction": {
                "Overall satisfaction score": "Weighted average of satisfaction indicators",
                "Complaint rate per 1,000 passengers": "(Complaints / Passengers) * 1,000",
                "Service recovery satisfaction (%)": "Satisfied customers after complaint resolution",
                "Net Promoter Score (NPS)": "Promoters - Detractors (%)"
            },
            "Improve Customer Communication": {
                "Response time to inquiries (hours)": "Average response time to customer requests",
                "Information accuracy (%)": "(Correct updates / Total updates) * 100",
                "Digital communication uptime (%)": "(Operational time / Total time) * 100",
                "Social engagement index": "Interactions per post / Followers * 100"
            },
            "Promote Inclusive Service Design": {
                "Inclusive feedback rate (%)": "Feedback from underserved users / Total feedback * 100",
                "Community participation programs (#)": "Customer or citizen co-design workshops held",
                "Implementation rate of user suggestions (%)": "Implemented suggestions / Total suggestions * 100",
                "Satisfaction of vulnerable groups (%)": "Survey score among elderly, disabled, or rural users"
            },
            "Enhance Brand Trust & Public Perception": {
                "Public trust index": "Citizen trust score from surveys",
                "Media sentiment score": "Positive media mentions / Total mentions * 100",
                "Crisis communication effectiveness (%)": "Resolved reputation issues / Total reported * 100",
                "Stakeholder confidence rating": "Aggregate trust score from key stakeholders"
            }
        },

        # -------------------- 6. Digital Access & Smart Mobility --------------------
        "Digital Access & Smart Mobility": {
            "Promote E-Services Adoption": {
                "E-ticket usage rate (%)": "Digital tickets / Total tickets * 100",
                "Mobile app active users (%)": "Active app users / Total customers * 100",
                "Online booking ratio (%)": "Bookings made online / Total bookings * 100",
                "Digital service satisfaction (%)": "Survey score on ease of digital use"
            },
            "Enhance Real-Time Information Access": {
                "Real-time tracking availability (%)": "Routes with live tracking / Total routes * 100",
                "System uptime (%)": "(Operational hours / Total hours) * 100",
                "Information accuracy rate (%)": "(Accurate live updates / Total updates) * 100",
                "User engagement with real-time services (%)": "Users using live features / Total users * 100"
            },
            "Expand Smart Transport Systems": {
                "Smart devices installed (#)": "IoT sensors, cameras, smart meters deployed",
                "Automated system coverage (%)": "Automated functions / Total eligible functions * 100",
                "Digital efficiency gain (%)": "(Time saved / Manual process time) * 100",
                "Revenue from digital channels ($)": "Revenue generated through e-platforms"
            },
            "Encourage Digital Literacy & Access": {
                "Digital awareness training participants (#)": "Citizens trained in digital use",
                "Customer digital literacy rate (%)": "(Digitally capable users / Total users) * 100",
                "Online support resolution rate (%)": "Issues resolved digitally / Total issues * 100",
                "Feedback through digital channels (%)": "Digital feedback / Total feedback * 100"
            }
        },

        # -------------------- 7. Environmental & Social Responsibility --------------------
        "Environmental & Social Responsibility": {
            "Promote Green Travel Behavior": {
                "Green transport adoption rate (%)": "Users choosing eco-modes / Total users * 100",
                "Emission reduction per passenger (kg CO₂)": "CO₂ saved per passenger trip",
                "Eco-friendly service availability (%)": "Green routes / Total routes * 100",
                "Citizen awareness of green options (%)": "Survey score on green transport awareness"
            },
            "Encourage Sustainable Operations": {
                "Waste recycling rate (%)": "(Recycled waste / Total waste) * 100",
                "Energy-efficient vehicle ratio (%)": "Low-emission vehicles / Total fleet * 100",
                "Water conservation compliance (%)": "Facilities meeting water use targets / Total * 100",
                "Customer satisfaction with sustainability (%)": "Survey on eco initiatives"
            },
            "Enhance Community Engagement": {
                "Community satisfaction index": "Survey rating from local communities",
                "CSR projects completed (#)": "Community transport or logistics projects done",
                "Local employment share (%)": "Local hires / Total employees * 100",
                "Stakeholder collaboration initiatives (#)": "Joint projects with civic groups"
            },
            "Promote Inclusive and Equitable Access": {
                "Women ridership share (%)": "Female passengers / Total passengers * 100",
                "Low-income accessibility index": "Affordable routes coverage for low-income groups",
                "Community inclusion programs (#)": "Programs targeting inclusive mobility",
                "Satisfaction among marginalized users (%)": "Survey-based equity score"
            }
        },
    }

}
