from management_project.models import Mission, OrganizationalProfile
from typing import List, Tuple, Optional
import random


class MissionService:
    """
    A comprehensive mission statement service providing tailored missions
    based on sector and organization classification (profitable/non-profitable).
    """

    SECTOR_MISSION_MAP = {
        'agriculture': {
            'profitable': [
                "To maximize agricultural productivity and profitability through innovative farming technologies",
                "To deliver high-quality agricultural products to global markets efficiently",
                "To optimize supply chain operations from farm to consumer",
                "To implement precision agriculture techniques for enhanced crop yields",
                "To develop sustainable farming practices that balance productivity and environmental stewardship",
                "To leverage data analytics for informed decision-making in agricultural operations",
                "To build strong partnerships with distributors, retailers, and food processors",
                "To invest in research and development for improved crop varieties and farming methods",
                "To ensure food safety and quality standards across all operations",
                "To expand market presence through strategic acquisitions and partnerships",
                "To adopt climate-resilient farming practices for long-term sustainability",
                "To optimize resource utilization including water, energy, and fertilizers",
                "To develop value-added agricultural products for diversified revenue streams",
                "To implement digital farming solutions for real-time monitoring and management",
                "To build brand recognition for premium agricultural products",
                "To ensure regulatory compliance and maintain industry certifications",
                "To foster innovation in agricultural technology and practices",
                "To create shareholder value through disciplined financial management",
                "To develop talent and expertise within the agricultural workforce",
                "To establish industry leadership in sustainable agricultural practices"
            ],
            'non_profitable': [
                "To promote food security and sustainable agriculture in vulnerable communities",
                "To empower smallholder farmers with knowledge, resources, and market access",
                "To advocate for policies supporting sustainable agricultural development",
                "To preserve traditional farming knowledge and indigenous crop varieties",
                "To combat hunger and malnutrition through community-based food systems",
                "To promote climate-resilient farming practices among rural communities",
                "To ensure fair trade and equitable returns for small-scale producers",
                "To protect agricultural biodiversity and ecosystem services",
                "To strengthen local food systems and reduce food miles",
                "To provide training and education in sustainable farming methods",
                "To support women and youth engagement in agriculture",
                "To promote organic and agroecological farming practices",
                "To facilitate access to land, water, and productive resources for marginalized farmers",
                "To reduce post-harvest losses through improved storage and processing",
                "To foster community-led agricultural innovation and knowledge sharing",
                "To advocate for farmers' rights and access to justice",
                "To promote soil conservation and land restoration practices",
                "To ensure water security and efficient irrigation management",
                "To build resilient local economies based on sustainable agriculture",
                "To monitor and address the impacts of climate change on food systems"
            ]
        },

        'mining': {
            'profitable': [
                "To extract mineral resources efficiently while maximizing shareholder returns",
                "To implement industry-leading safety standards across all mining operations",
                "To optimize mining processes through technological innovation and automation",
                "To develop sustainable mining practices that minimize environmental impact",
                "To build strong relationships with host communities and stakeholders",
                "To ensure regulatory compliance and maintain social license to operate",
                "To invest in exploration and development of new mineral resources",
                "To optimize resource recovery and processing efficiency",
                "To implement comprehensive environmental management systems",
                "To develop talent and expertise in mining engineering and operations",
                "To leverage data analytics for improved decision-making and productivity",
                "To establish strategic partnerships across the mining value chain",
                "To implement responsible tailings management and mine closure plans",
                "To adopt renewable energy solutions for mining operations",
                "To ensure transparent reporting and corporate governance",
                "To optimize capital allocation and investment decisions",
                "To develop innovative solutions for mining challenges",
                "To maintain competitive advantage through operational excellence",
                "To foster a culture of safety, innovation, and continuous improvement",
                "To create long-term value for all stakeholders through responsible mining"
            ],
            'non_profitable': [
                "To advocate for responsible mining practices that protect communities and environments",
                "To ensure mining revenues benefit local communities fairly and transparently",
                "To monitor and address the environmental impacts of mining operations",
                "To promote community participation in mining decision-making processes",
                "To protect the rights of indigenous peoples and local communities affected by mining",
                "To advocate for stronger regulations and enforcement in the mining sector",
                "To support artisanal and small-scale miners with safer working conditions",
                "To promote mine site rehabilitation and environmental restoration",
                "To ensure transparency in mining contracts and revenue management",
                "To combat corruption and illicit financial flows in the mining sector",
                "To promote alternative livelihoods in mining-dependent communities",
                "To protect water resources from mining contamination and overuse",
                "To advocate for climate-responsible mining practices",
                "To ensure gender equality and women's rights in mining areas",
                "To promote circular economy principles in mineral use and recycling",
                "To support community-led environmental monitoring of mining operations",
                "To advocate for fair compensation and benefit sharing mechanisms",
                "To promote responsible sourcing and supply chain due diligence",
                "To ensure human rights protection throughout mining operations",
                "To build community capacity for sustainable development beyond mining"
            ]
        },

        'manufacturing': {
            'profitable': [
                "To manufacture high-quality products that meet customer expectations and industry standards",
                "To optimize production processes for maximum efficiency and cost-effectiveness",
                "To implement lean manufacturing principles and continuous improvement practices",
                "To invest in advanced manufacturing technologies and automation",
                "To ensure product quality and safety through rigorous testing and quality control",
                "To develop innovative products that address market needs and trends",
                "To build strong supply chain relationships and ensure reliable material sourcing",
                "To implement sustainable manufacturing practices that reduce environmental impact",
                "To foster a culture of safety, quality, and operational excellence",
                "To develop talent and technical expertise within the manufacturing workforce",
                "To leverage data analytics for predictive maintenance and process optimization",
                "To ensure regulatory compliance and maintain industry certifications",
                "To implement energy-efficient manufacturing processes and technologies",
                "To develop customized solutions for specific customer requirements",
                "To optimize inventory management and production planning",
                "To establish strategic partnerships for technology development and market expansion",
                "To implement digital manufacturing and Industry 4.0 technologies",
                "To maintain competitive advantage through innovation and efficiency",
                "To ensure timely delivery and excellent customer service",
                "To create value for shareholders through profitable growth and operational excellence"
            ],
            'non_profitable': [
                "To promote ethical manufacturing practices and workers' rights globally",
                "To advocate for safe and healthy working conditions in manufacturing facilities",
                "To support local manufacturing that creates quality employment opportunities",
                "To promote sustainable production and consumption patterns",
                "To ensure transparency and accountability in manufacturing supply chains",
                "To combat forced labor, child labor, and modern slavery in manufacturing",
                "To promote circular economy principles in production and waste management",
                "To support small and medium-sized manufacturers with technical assistance",
                "To advocate for green manufacturing practices and clean production technologies",
                "To ensure product safety and quality for consumer protection",
                "To promote local content and domestic manufacturing capabilities",
                "To support vocational training and skills development in manufacturing",
                "To advocate for fair trade and ethical sourcing practices",
                "To promote energy efficiency and renewable energy in manufacturing",
                "To ensure environmental protection and pollution prevention in manufacturing",
                "To support innovation in sustainable product design and manufacturing",
                "To promote gender equality and women's empowerment in manufacturing",
                "To ensure responsible waste management and recycling practices",
                "To advocate for policies supporting sustainable industrial development",
                "To build community resilience through local manufacturing initiatives"
            ]
        },

        'construction': {
            'profitable': [
                "To deliver construction projects on time, within budget, and to the highest quality standards",
                "To implement innovative construction methods and technologies for improved efficiency",
                "To ensure workplace safety and health across all construction sites",
                "To build strong client relationships through reliable service and excellent communication",
                "To optimize project management processes and resource allocation",
                "To invest in skilled workforce development and technical training",
                "To implement sustainable construction practices and green building standards",
                "To leverage building information modeling (BIM) for project planning and execution",
                "To ensure regulatory compliance and obtain necessary permits and approvals",
                "To develop specialized expertise in specific construction sectors and project types",
                "To implement quality assurance and control systems throughout project lifecycles",
                "To optimize supply chain management and material procurement",
                "To adopt prefabrication and modular construction techniques where appropriate",
                "To implement risk management and contingency planning for complex projects",
                "To foster innovation in construction materials and methods",
                "To ensure accurate cost estimation and financial management",
                "To build strategic partnerships with subcontractors and suppliers",
                "To implement digital tools for project monitoring and reporting",
                "To maintain competitive bidding and business development processes",
                "To create value for stakeholders through successful project delivery and business growth"
            ],
            'non_profitable': [
                "To promote adequate, safe, and affordable housing for all communities",
                "To advocate for construction workers' rights and fair labor practices",
                "To support community-led construction and self-build housing initiatives",
                "To promote sustainable and environmentally friendly building practices",
                "To ensure building safety and disaster resilience in construction projects",
                "To support vocational training and skills development in the construction sector",
                "To advocate for universal accessibility in building design and construction",
                "To promote the use of local materials and traditional construction techniques",
                "To ensure community participation in construction planning and development",
                "To support disaster-resistant construction and post-disaster rebuilding",
                "To promote energy-efficient and climate-responsive building design",
                "To advocate for stronger building codes and construction standards",
                "To support affordable housing initiatives and homeless shelter construction",
                "To promote green building certification and sustainable construction practices",
                "To ensure fair wages and working conditions for construction workers",
                "To support community infrastructure development and public facilities",
                "To promote construction waste reduction and recycling initiatives",
                "To advocate for transparent and ethical construction practices",
                "To support women's participation in the construction industry",
                "To build community capacity for sustainable construction and maintenance"
            ]
        },

        'energy': {
            'profitable': [
                "To generate and distribute reliable, affordable energy to customers and markets",
                "To optimize energy production efficiency and operational performance",
                "To invest in renewable energy sources and clean energy technologies",
                "To implement smart grid technologies for improved energy management",
                "To ensure operational safety and environmental compliance across all facilities",
                "To develop innovative energy solutions that meet evolving customer needs",
                "To build strategic partnerships across the energy value chain",
                "To implement energy storage solutions for grid stability and reliability",
                "To optimize asset management and maintenance programs",
                "To leverage data analytics for predictive maintenance and operational optimization",
                "To ensure regulatory compliance and maintain operating licenses",
                "To develop talent and technical expertise in energy engineering and operations",
                "To implement cybersecurity measures for critical energy infrastructure",
                "To optimize energy trading and portfolio management",
                "To invest in research and development for next-generation energy technologies",
                "To implement energy efficiency programs for commercial and industrial customers",
                "To ensure transparent reporting and stakeholder communication",
                "To maintain competitive advantage through technological innovation",
                "To foster a culture of safety, reliability, and continuous improvement",
                "To create sustainable value for shareholders through strategic growth and operational excellence"
            ],
            'non_profitable': [
                "To advocate for universal access to affordable, reliable, and clean energy",
                "To promote renewable energy adoption and climate action initiatives",
                "To ensure energy projects benefit local communities fairly and equitably",
                "To combat energy poverty and support vulnerable households",
                "To promote community-owned and managed renewable energy projects",
                "To advocate for progressive energy policies and regulations",
                "To support energy efficiency programs for low-income communities",
                "To ensure environmental protection in energy development and operations",
                "To promote energy democracy and community control over energy resources",
                "To support research and innovation in sustainable energy solutions",
                "To advocate for just transition from fossil fuels to renewable energy",
                "To ensure transparent and accountable energy governance",
                "To promote energy conservation and demand-side management",
                "To support local capacity building in renewable energy technologies",
                "To ensure gender equality in energy access and benefits",
                "To advocate for climate justice in energy policy and planning",
                "To promote decentralized and distributed energy systems",
                "To ensure community participation in energy decision-making",
                "To support energy education and public awareness campaigns",
                "To build community energy resilience and security"
            ]
        },

        'transport': {
            'profitable': [
                "To provide reliable, efficient, and safe transportation services to customers",
                "To optimize transport operations and logistics for maximum efficiency",
                "To implement advanced fleet management and maintenance systems",
                "To ensure customer satisfaction through excellent service delivery",
                "To invest in modern transport equipment and technologies",
                "To develop innovative transport solutions for evolving market needs",
                "To build strategic partnerships across the transport and logistics ecosystem",
                "To implement safety management systems and risk mitigation measures",
                "To optimize route planning and load management for cost efficiency",
                "To leverage technology for real-time tracking and operational visibility",
                "To ensure regulatory compliance and maintain operating permits",
                "To develop talent and expertise in transport management and operations",
                "To implement sustainable transport practices and emission reduction measures",
                "To optimize fuel efficiency and environmental performance",
                "To ensure reliable scheduling and on-time performance",
                "To implement customer relationship management and service improvement programs",
                "To maintain competitive pricing and service offerings",
                "To foster a culture of safety, service excellence, and continuous improvement",
                "To implement digital transformation in transport operations and customer service",
                "To create value for shareholders through operational excellence and market growth"
            ],
            'non_profitable': [
                "To promote accessible and affordable transport for all community members",
                "To advocate for sustainable and environmentally friendly transport systems",
                "To ensure transport services meet the needs of marginalized communities",
                "To combat transport-related pollution and environmental degradation",
                "To support community-based transport initiatives and social enterprises",
                "To advocate for transport safety and user protection measures",
                "To promote public transport and shared mobility solutions",
                "To ensure fair and equitable access to transport infrastructure",
                "To support non-motorized transport and active mobility options",
                "To ensure environmental consideration in transport planning and development",
                "To promote transport justice and equitable mobility access",
                "To advocate for inclusive transport policies and planning processes",
                "To support transport education and safety awareness programs",
                "To ensure accessible transport for people with disabilities and elderly",
                "To promote community participation in transport decision-making",
                "To advocate for climate-resilient transport infrastructure",
                "To support local employment in transport services and operations",
                "To ensure transparent and accountable transport governance",
                "To promote green transport technologies and clean fuels",
                "To build community mobility resilience and connectivity"
            ]
        },

        'trade': {
            'profitable': [
                "To facilitate efficient and profitable trade between markets and regions",
                "To optimize supply chain operations and logistics management",
                "To build strong relationships with suppliers, distributors, and customers",
                "To ensure product quality, safety, and regulatory compliance",
                "To implement innovative trading platforms and digital solutions",
                "To develop market intelligence and strategic trading insights",
                "To optimize inventory management and working capital efficiency",
                "To implement risk management strategies for price volatility and market changes",
                "To ensure reliable and timely delivery of goods and services",
                "To leverage technology for trade finance and transaction processing",
                "To develop specialized expertise in specific product categories and markets",
                "To implement sustainable and ethical sourcing practices",
                "To ensure transparent pricing and contract management",
                "To optimize trade documentation and compliance procedures",
                "To develop talent and expertise in international trade and commerce",
                "To implement customer relationship management and service excellence",
                "To maintain competitive advantage through market knowledge and relationships",
                "To foster innovation in trade processes and business models",
                "To ensure financial discipline and profitable growth",
                "To create value for stakeholders through efficient and responsible trading"
            ],
            'non_profitable': [
                "To promote fair and equitable trade practices globally",
                "To advocate for trade justice and producer rights protection",
                "To ensure trade benefits reach marginalized producers and communities",
                "To combat exploitative trade practices and market inequalities",
                "To support transparent and accountable trade systems",
                "To promote local and regional trade development initiatives",
                "To advocate for sustainable and ethical trade standards",
                "To ensure community participation in trade decision-making",
                "To support traditional products and artisan trade preservation",
                "To ensure environmental sustainability in trade and commerce",
                "To promote trade education and capacity building for small producers",
                "To advocate for progressive trade policies and fair agreements",
                "To support community-based trade enterprises and cooperatives",
                "To promote fair trade certification and market access",
                "To ensure gender equality in trade opportunities and benefits",
                "To support sustainable supply chain development and management",
                "To advocate for responsible consumption and production patterns",
                "To promote green trade practices and circular economy principles",
                "To ensure trade worker rights and fair treatment",
                "To build community trade resilience and economic diversity"
            ]
        },

        'finance': {
            'profitable': [
                "To provide comprehensive financial services that meet customer needs and expectations",
                "To ensure financial stability and prudent risk management practices",
                "To implement innovative banking products and digital financial solutions",
                "To optimize operational efficiency and cost management",
                "To build strong customer relationships through excellent service delivery",
                "To ensure regulatory compliance and maintain financial integrity",
                "To develop talent and expertise in financial services and risk management",
                "To implement advanced cybersecurity measures for customer protection",
                "To leverage data analytics for customer insights and product development",
                "To ensure transparent reporting and corporate governance",
                "To implement sustainable finance practices and ESG integration",
                "To optimize capital allocation and investment decisions",
                "To develop specialized financial products for different customer segments",
                "To ensure reliable and efficient transaction processing",
                "To implement customer education and financial literacy programs",
                "To maintain competitive pricing and service offerings",
                "To foster innovation in financial technology and service delivery",
                "To ensure business continuity and disaster recovery capabilities",
                "To implement robust anti-money laundering and compliance systems",
                "To create sustainable value for shareholders through profitable growth and risk management"
            ],
            'non_profitable': [
                "To promote financial inclusion and access for underserved communities",
                "To advocate for transparent and ethical financial systems",
                "To ensure financial services benefit low-income and marginalized groups",
                "To combat predatory lending and financial exploitation",
                "To support community banking and microfinance initiatives",
                "To advocate for financial literacy and consumer protection",
                "To ensure responsible and sustainable financial practices",
                "To promote local financial institutions and cooperative models",
                "To support financial education and capability building programs",
                "To ensure environmental consideration in financial decision-making",
                "To promote financial justice and equitable access to capital",
                "To advocate for progressive financial policies and regulations",
                "To support community-based financial initiatives and credit unions",
                "To promote ethical investment and socially responsible finance",
                "To ensure accessible financial services for vulnerable populations",
                "To support financial cooperatives and community development finance",
                "To advocate for transparent financial operations and reporting",
                "To promote green finance and sustainable investment practices",
                "To ensure financial worker rights and fair treatment",
                "To build community financial resilience and economic security"
            ]
        },

        'tourism': {
            'profitable': [
                "To provide exceptional travel experiences that exceed customer expectations",
                "To optimize tourism operations for efficiency and customer satisfaction",
                "To implement sustainable tourism practices that protect destinations",
                "To build strong partnerships across the tourism value chain",
                "To ensure customer safety and service quality across all operations",
                "To develop innovative tourism products and experiences",
                "To leverage technology for enhanced customer service and operational efficiency",
                "To implement comprehensive marketing and destination promotion strategies",
                "To ensure regulatory compliance and maintain industry certifications",
                "To develop talent and expertise in hospitality and tourism management",
                "To optimize revenue management and pricing strategies",
                "To implement customer relationship management and loyalty programs",
                "To ensure reliable and efficient booking and reservation systems",
                "To develop specialized tourism products for different market segments",
                "To implement quality assurance and service standards",
                "To maintain competitive advantage through unique experiences and service excellence",
                "To foster innovation in tourism services and customer experiences",
                "To ensure business continuity and risk management in tourism operations",
                "To implement sustainable destination management practices",
                "To create value for shareholders through profitable growth and brand reputation"
            ],
            'non_profitable': [
                "To promote responsible and sustainable tourism practices globally",
                "To advocate for tourism that benefits local communities and environments",
                "To ensure tourism preserves cultural heritage and traditional knowledge",
                "To combat exploitative and damaging tourism practices",
                "To support community-based tourism initiatives and social enterprises",
                "To advocate for tourist rights and responsible travel behavior",
                "To ensure sustainable tourism development and management",
                "To promote local employment and enterprise in tourism",
                "To support cultural exchange and understanding through tourism",
                "To ensure environmental protection in tourism development",
                "To promote tourism education and awareness among travelers",
                "To advocate for progressive tourism policies and planning",
                "To support community participation in tourism development",
                "To promote eco-tourism and nature-based tourism initiatives",
                "To ensure accessible tourism opportunities for all people",
                "To support traditional crafts and cultural expressions through tourism",
                "To advocate for transparent tourism operations and benefit sharing",
                "To promote green tourism practices and certification",
                "To ensure tourism worker rights and fair treatment",
                "To build community benefits from tourism development"
            ]
        },

        'hotels': {
            'profitable': [
                "To provide exceptional hospitality experiences that create lasting memories",
                "To optimize hotel operations for efficiency and guest satisfaction",
                "To implement comprehensive guest service and experience management",
                "To ensure consistent quality standards across all hotel properties",
                "To develop innovative hospitality services and amenities",
                "To build strong brand recognition and customer loyalty",
                "To leverage technology for enhanced guest experiences and operational efficiency",
                "To implement effective revenue management and pricing strategies",
                "To ensure regulatory compliance and maintain safety standards",
                "To develop talent and expertise in hotel management and operations",
                "To optimize food and beverage operations and restaurant management",
                "To implement sustainability practices in hotel operations",
                "To ensure reliable and efficient reservation and booking systems",
                "To develop specialized services for different guest segments",
                "To implement quality assurance and guest feedback systems",
                "To maintain competitive advantage through service excellence and unique offerings",
                "To foster innovation in hospitality services and guest experiences",
                "To ensure business continuity and risk management in hotel operations",
                "To implement comprehensive marketing and brand promotion strategies",
                "To create value for shareholders through profitable operations and brand growth"
            ],
            'non_profitable': [
                "To promote ethical and fair employment practices in the hotel industry",
                "To advocate for hotels that benefit local communities and environments",
                "To ensure hotels respect cultural values and heritage preservation",
                "To combat exploitative labor practices in the hospitality sector",
                "To support community-involved hotel initiatives and social enterprises",
                "To advocate for guest rights and responsible hospitality practices",
                "To ensure sustainable hotel development and operations",
                "To promote local employment and enterprise development in hospitality",
                "To support cultural sensitivity and community engagement in hotel services",
                "To ensure environmental protection in hotel operations and development",
                "To promote hospitality education and vocational training programs",
                "To advocate for progressive hotel policies and industry standards",
                "To support community participation in hotel planning and development",
                "To promote accessible hotel facilities for people with disabilities",
                "To ensure fair distribution of tourism benefits to local communities",
                "To support local sourcing and supply chain development",
                "To advocate for transparent hotel operations and impact reporting",
                "To promote green hotel practices and environmental certification",
                "To ensure hotel worker rights and fair treatment",
                "To build community benefits from hotel development and operations"
            ]
        },

        'food': {
            'profitable': [
                "To produce and distribute high-quality food products that meet consumer preferences",
                "To optimize food processing and manufacturing operations for efficiency",
                "To implement comprehensive food safety and quality assurance systems",
                "To ensure reliable supply chain management and distribution",
                "To develop innovative food products that address market trends",
                "To build strong brand recognition and customer loyalty",
                "To leverage technology for production optimization and quality control",
                "To implement sustainable sourcing and production practices",
                "To ensure regulatory compliance and maintain food safety certifications",
                "To develop talent and expertise in food science and operations",
                "To optimize inventory management and shelf-life optimization",
                "To implement effective marketing and product promotion strategies",
                "To ensure efficient logistics and distribution networks",
                "To develop specialized products for different market segments",
                "To implement continuous improvement in production processes",
                "To maintain competitive advantage through product quality and innovation",
                "To foster innovation in food technology and product development",
                "To ensure business continuity and supply chain resilience",
                "To implement comprehensive quality control and testing procedures",
                "To create value for shareholders through profitable growth and market leadership"
            ],
            'non_profitable': [
                "To promote food as a fundamental human right for all people",
                "To advocate for sustainable and equitable food systems globally",
                "To ensure food production benefits small-scale producers and communities",
                "To combat food waste and promote efficient distribution systems",
                "To support local and traditional food systems and knowledge",
                "To advocate for food sovereignty and security for all communities",
                "To ensure sustainable food production and consumption patterns",
                "To promote small-scale food producers and processors",
                "To support food education and nutrition awareness programs",
                "To ensure environmental protection in food systems",
                "To promote food diversity and cultural heritage preservation",
                "To advocate for progressive food policies and regulations",
                "To support community-based food initiatives and urban agriculture",
                "To promote organic and agroecological food production",
                "To ensure accessible and affordable food for vulnerable populations",
                "To support food cooperatives and community-supported agriculture",
                "To advocate for transparent food labeling and consumer information",
                "To promote sustainable packaging and waste reduction in food systems",
                "To ensure food worker rights and fair treatment",
                "To build community food resilience and security"
            ]
        },

        'professional_services': {
            'profitable': [
                "To deliver exceptional professional services that meet client needs and expectations",
                "To optimize service delivery processes for efficiency and quality",
                "To implement comprehensive quality assurance and client satisfaction systems",
                "To ensure deep expertise and knowledge in specialized service areas",
                "To develop innovative solutions for complex client challenges",
                "To build strong, long-term client relationships and trust",
                "To leverage technology for enhanced service delivery and efficiency",
                "To implement effective project management and delivery methodologies",
                "To ensure regulatory compliance and maintain professional standards",
                "To develop talent and expertise within the professional workforce",
                "To optimize resource allocation and project profitability",
                "To implement knowledge management and best practice sharing",
                "To ensure reliable and timely service delivery",
                "To develop specialized services for different industry sectors",
                "To implement continuous learning and professional development",
                "To maintain competitive advantage through expertise and service quality",
                "To foster innovation in service methodologies and solutions",
                "To ensure business continuity and risk management in service delivery",
                "To implement comprehensive business development and client acquisition strategies",
                "To create value for shareholders through profitable growth and reputation excellence"
            ],
            'non_profitable': [
                "To promote access to professional services for underserved communities",
                "To advocate for ethical and responsible professional practice standards",
                "To ensure professional services benefit marginalized and vulnerable groups",
                "To combat exploitation and unprofessional practices in service sectors",
                "To support pro bono services and community engagement initiatives",
                "To advocate for professional standards and accountability mechanisms",
                "To ensure sustainable and responsible professional practice development",
                "To promote local professional capacity building and development",
                "To support professional education and training programs",
                "To ensure social responsibility in professional service delivery",
                "To promote diversity and inclusion in professional representation",
                "To advocate for progressive professional regulations and governance",
                "To support community-based professional service initiatives",
                "To promote ethical business practices and corporate responsibility",
                "To ensure accessible professional services for all community members",
                "To support professional cooperatives and social enterprises",
                "To advocate for transparent professional operations and conduct",
                "To promote green professional practices and sustainability advisory",
                "To ensure professional worker rights and fair treatment",
                "To build community professional capacity and service access"
            ]
        },

        'ict': {
            'profitable': [
                "To deliver innovative ICT solutions that drive business transformation and growth",
                "To optimize technology infrastructure and service delivery processes",
                "To implement comprehensive cybersecurity and data protection measures",
                "To ensure reliable and high-performance technology systems",
                "To develop cutting-edge software and digital solutions",
                "To build strong client partnerships and technology adoption",
                "To leverage emerging technologies for competitive advantage",
                "To implement agile development and project management methodologies",
                "To ensure regulatory compliance and data privacy standards",
                "To develop talent and expertise in technology and digital innovation",
                "To optimize IT service management and support processes",
                "To implement digital transformation strategies for clients",
                "To ensure scalable and flexible technology architectures",
                "To develop specialized solutions for different industry sectors",
                "To implement continuous improvement in technology services",
                "To maintain competitive advantage through innovation and expertise",
                "To foster innovation in technology development and applications",
                "To ensure business continuity and disaster recovery capabilities",
                "To implement comprehensive quality assurance and testing processes",
                "To create value for shareholders through technology leadership and profitable growth"
            ],
            'non_profitable': [
                "To promote digital inclusion and technology access for all communities",
                "To advocate for open and accessible technology solutions globally",
                "To ensure ICT benefits reach underserved and marginalized populations",
                "To combat digital divide and technology inequality",
                "To support community technology centers and digital literacy programs",
                "To advocate for digital rights and privacy protection",
                "To ensure sustainable and responsible technology use and development",
                "To promote local ICT capacity building and skills development",
                "To support open-source software and collaborative technology development",
                "To ensure environmental consideration in technology operations",
                "To promote digital justice and equitable technology access",
                "To advocate for progressive technology policies and regulations",
                "To support community-based technology initiatives and social enterprises",
                "To promote affordable technology access for low-income communities",
                "To ensure accessible technology for people with disabilities",
                "To support digital preservation and cultural heritage technology",
                "To advocate for transparent technology operations and data practices",
                "To promote green computing and sustainable technology practices",
                "To ensure technology worker rights and fair treatment",
                "To build community digital resilience and capacity"
            ]
        },

        'telecommunications': {
            'profitable': [
                "To provide reliable, high-speed telecommunications services to customers",
                "To optimize network infrastructure and performance management",
                "To implement comprehensive network security and reliability measures",
                "To ensure excellent customer service and support experiences",
                "To develop innovative communication products and services",
                "To build strong network coverage and capacity planning",
                "To leverage technology for network optimization and efficiency",
                "To implement effective customer relationship management systems",
                "To ensure regulatory compliance and spectrum management",
                "To develop talent and expertise in telecommunications engineering",
                "To optimize network operations and maintenance processes",
                "To implement new technology adoption and network upgrades",
                "To ensure scalable and future-proof network architectures",
                "To develop specialized services for different customer segments",
                "To implement quality of service and performance monitoring",
                "To maintain competitive advantage through network quality and innovation",
                "To foster innovation in telecommunications services and technologies",
                "To ensure business continuity and network resilience",
                "To implement comprehensive marketing and customer acquisition strategies",
                "To create value for shareholders through network excellence and market growth"
            ],
            'non_profitable': [
                "To promote universal telecommunications access for all communities",
                "To advocate for affordable and reliable communication services globally",
                "To ensure telecommunications benefits reach remote and underserved areas",
                "To combat communication inequality and digital exclusion",
                "To support community telecommunications initiatives and cooperatives",
                "To advocate for communication rights and universal service obligations",
                "To ensure sustainable telecommunications development and operations",
                "To promote local telecommunications capacity and infrastructure development",
                "To support digital literacy and technology adoption programs",
                "To ensure environmental protection in telecommunications operations",
                "To promote communication access for people with disabilities",
                "To advocate for progressive telecommunications policies and regulations",
                "To support community-based network initiatives and mesh networks",
                "To promote affordable communication services for low-income households",
                "To ensure emergency communication capabilities and public safety",
                "To support local content development and cultural preservation",
                "To advocate for transparent telecommunications operations and pricing",
                "To promote green telecommunications practices and energy efficiency",
                "To ensure telecommunications worker rights and fair treatment",
                "To build community communication resilience and connectivity"
            ]
        },

        'research': {
            'profitable': [
                "To conduct cutting-edge research that drives innovation and commercial applications",
                "To optimize research processes and laboratory operations for efficiency",
                "To implement comprehensive research quality and validation systems",
                "To ensure scientific excellence and methodological rigor",
                "To develop innovative solutions and intellectual property",
                "To build strong research partnerships and collaborations",
                "To leverage advanced research technologies and equipment",
                "To implement effective project management and research methodology",
                "To ensure regulatory compliance and research ethics",
                "To develop talent and expertise in scientific research and innovation",
                "To optimize research funding and resource allocation",
                "To implement knowledge transfer and commercialization processes",
                "To ensure reliable and reproducible research outcomes",
                "To develop specialized research capabilities in focused areas",
                "To implement continuous improvement in research processes",
                "To maintain competitive advantage through research excellence and innovation",
                "To foster innovation in research methodologies and applications",
                "To ensure research continuity and risk management",
                "To implement comprehensive intellectual property management",
                "To create value for shareholders through research innovation and commercialization"
            ],
            'non_profitable': [
                "To promote open science and knowledge sharing for public benefit",
                "To advocate for research that addresses pressing global challenges",
                "To ensure research benefits communities and society equitably",
                "To combat research inequality and knowledge access barriers",
                "To support community-based and participatory research approaches",
                "To advocate for research ethics and integrity standards",
                "To ensure sustainable and responsible research practices",
                "To promote local research capacity building and development",
                "To support research education and public understanding of science",
                "To ensure environmental consideration in research activities",
                "To promote research diversity and inclusive participation",
                "To advocate for progressive research policies and funding mechanisms",
                "To support citizen science and public engagement in research",
                "To promote interdisciplinary research and knowledge integration",
                "To ensure accessible research findings and data sharing",
                "To support traditional knowledge preservation and validation",
                "To advocate for transparent research operations and reporting",
                "To promote green research practices and laboratory sustainability",
                "To ensure research worker rights and fair treatment",
                "To build community research capacity and engagement"
            ]
        },

        'education': {
            'profitable': [
                "To provide high-quality education that prepares students for success",
                "To optimize educational programs and institutional operations",
                "To implement comprehensive curriculum development and quality assurance",
                "To ensure excellent teaching and learning experiences",
                "To develop innovative educational methodologies and technologies",
                "To build strong educational partnerships and accreditation",
                "To leverage technology for enhanced learning and administration",
                "To implement effective student support and development systems",
                "To ensure regulatory compliance and educational standards",
                "To develop talent and expertise in educational leadership and teaching",
                "To optimize resource allocation and institutional management",
                "To implement continuous improvement in educational outcomes",
                "To ensure relevant and future-oriented curriculum design",
                "To develop specialized programs for different learner needs",
                "To implement comprehensive assessment and evaluation systems",
                "To maintain competitive advantage through educational quality and innovation",
                "To foster innovation in teaching methods and learning technologies",
                "To ensure institutional sustainability and growth",
                "To implement comprehensive marketing and student recruitment strategies",
                "To create value for stakeholders through educational excellence and student success"
            ],
            'non_profitable': [
                "To promote education as a fundamental human right for all",
                "To advocate for quality and accessible education worldwide",
                "To ensure education benefits marginalized and underserved communities",
                "To combat educational inequality and access barriers",
                "To support community-based and alternative education models",
                "To advocate for inclusive and equitable education systems",
                "To ensure sustainable and responsible educational practices",
                "To promote local educational capacity and teacher development",
                "To support lifelong learning and skills development programs",
                "To ensure environmental education and sustainability integration",
                "To promote education for sustainable development",
                "To advocate for progressive education policies and funding",
                "To support community participation in educational governance",
                "To promote multicultural education and cultural preservation",
                "To ensure accessible education for people with disabilities",
                "To support education in emergency and conflict situations",
                "To advocate for transparent educational operations and outcomes",
                "To promote green schools and sustainable campus operations",
                "To ensure education worker rights and fair treatment",
                "To build community educational capacity and lifelong learning"
            ]
        },

        'health': {
            'profitable': [
                "To provide comprehensive healthcare services that ensure patient well-being",
                "To optimize healthcare operations and clinical processes for efficiency",
                "To implement comprehensive patient safety and quality care systems",
                "To ensure excellent medical outcomes and patient experiences",
                "To develop innovative healthcare solutions and treatments",
                "To build strong healthcare partnerships and referral networks",
                "To leverage technology for enhanced patient care and operational efficiency",
                "To implement effective healthcare management and coordination systems",
                "To ensure regulatory compliance and healthcare standards",
                "To develop talent and expertise in medical and healthcare professions",
                "To optimize resource allocation and healthcare delivery",
                "To implement continuous improvement in patient care quality",
                "To ensure comprehensive and integrated healthcare services",
                "To develop specialized medical services and treatment programs",
                "To implement robust medical records and information systems",
                "To maintain competitive advantage through healthcare quality and innovation",
                "To foster innovation in medical treatments and healthcare delivery",
                "To ensure healthcare facility sustainability and growth",
                "To implement comprehensive patient engagement and community health programs",
                "To create value for stakeholders through healthcare excellence and patient outcomes"
            ],
            'non_profitable': [
                "To promote health as a fundamental human right for all people",
                "To advocate for universal access to quality healthcare services",
                "To ensure healthcare benefits reach marginalized and vulnerable populations",
                "To combat health inequality and access barriers",
                "To support community-based and primary healthcare initiatives",
                "To advocate for comprehensive public health systems and policies",
                "To ensure sustainable and responsible healthcare practices",
                "To promote local healthcare capacity and workforce development",
                "To support health education and disease prevention programs",
                "To ensure environmental health and protection considerations",
                "To promote mental health and wellness services",
                "To advocate for progressive health policies and funding mechanisms",
                "To support community participation in health planning and governance",
                "To promote traditional medicine and integrative health approaches",
                "To ensure accessible healthcare for people with disabilities",
                "To support health services in emergency and disaster situations",
                "To advocate for transparent healthcare operations and outcomes",
                "To promote green healthcare practices and facility sustainability",
                "To ensure healthcare worker rights and fair treatment",
                "To build community health resilience and well-being"
            ]
        },

        'creative': {
            'profitable': [
                "To create exceptional creative works that inspire and engage audiences",
                "To optimize creative production processes and project management",
                "To implement comprehensive quality assurance and creative standards",
                "To ensure innovative and original creative output",
                "To develop cutting-edge creative technologies and methodologies",
                "To build strong creative partnerships and client relationships",
                "To leverage technology for enhanced creative production and distribution",
                "To implement effective creative project management and delivery",
                "To ensure copyright protection and intellectual property management",
                "To develop talent and expertise in creative arts and technologies",
                "To optimize resource allocation and creative production efficiency",
                "To implement continuous improvement in creative processes",
                "To ensure market-relevant and audience-engaging creative works",
                "To develop specialized creative services and products",
                "To implement comprehensive audience engagement and marketing strategies",
                "To maintain competitive advantage through creative excellence and innovation",
                "To foster innovation in creative expression and technologies",
                "To ensure creative business sustainability and growth",
                "To implement comprehensive rights management and licensing",
                "To create value for stakeholders through creative excellence and commercial success"
            ],
            'non_profitable': [
                "To promote creative expression as essential for human development",
                "To advocate for arts and culture access for all communities",
                "To ensure creative industries benefit local communities and cultures",
                "To combat creative inequality and access barriers",
                "To support community-based and traditional arts initiatives",
                "To advocate for cultural preservation and diversity",
                "To ensure sustainable and responsible creative practices",
                "To promote local creative capacity and artist development",
                "To support arts education and creative development programs",
                "To ensure environmental consideration in creative work",
                "To promote cultural diversity and inclusive representation",
                "To advocate for progressive cultural policies and funding",
                "To support community participation in cultural life",
                "To promote traditional crafts and cultural heritage",
                "To ensure accessible creative opportunities for all people",
                "To support arts in education and community development",
                "To advocate for transparent creative operations and funding",
                "To promote green creative practices and sustainability",
                "To ensure creative worker rights and fair treatment",
                "To build community creative capacity and cultural vitality"
            ]
        },

        'environment': {
            'profitable': [
                "To develop innovative environmental solutions that create business value",
                "To optimize environmental operations and service delivery processes",
                "To implement comprehensive environmental management and compliance systems",
                "To ensure effective environmental protection and sustainability outcomes",
                "To develop cutting-edge environmental technologies and services",
                "To build strong environmental partnerships and client relationships",
                "To leverage technology for enhanced environmental monitoring and management",
                "To implement effective environmental project management and delivery",
                "To ensure regulatory compliance and environmental standards",
                "To develop talent and expertise in environmental sciences and engineering",
                "To optimize resource allocation and environmental service efficiency",
                "To implement continuous improvement in environmental performance",
                "To ensure comprehensive and integrated environmental solutions",
                "To develop specialized environmental services and technologies",
                "To implement robust environmental monitoring and reporting systems",
                "To maintain competitive advantage through environmental innovation and expertise",
                "To foster innovation in environmental protection and sustainability",
                "To ensure environmental business sustainability and growth",
                "To implement comprehensive environmental impact assessment and management",
                "To create value for stakeholders through environmental excellence and sustainable solutions"
            ],
            'non_profitable': [
                "To promote environmental protection as essential for all life",
                "To advocate for sustainable development and conservation globally",
                "To ensure environmental actions benefit communities and ecosystems equitably",
                "To combat environmental degradation and climate change impacts",
                "To support community-based environmental initiatives and stewardship",
                "To advocate for strong environmental policies and regulations",
                "To ensure sustainable and responsible environmental practices",
                "To promote local environmental capacity and knowledge development",
                "To support environmental education and public awareness programs",
                "To ensure comprehensive ecosystem protection and restoration",
                "To promote biodiversity conservation and habitat protection",
                "To advocate for progressive environmental policies and action",
                "To support community participation in environmental decision-making",
                "To promote sustainable resource management and circular economy",
                "To ensure accessible environmental benefits for all communities",
                "To support environmental justice and equitable protection",
                "To advocate for transparent environmental operations and reporting",
                "To promote green technologies and sustainable practices",
                "To ensure environmental worker rights and fair treatment",
                "To build community environmental resilience and sustainability"
            ]
        }
    }

    def __init__(self, org_obj: OrganizationalProfile):
        self.org = org_obj
        if org_obj:
            self.sector_name = org_obj.sector_name
            self.classification = org_obj.organization_classification
        else:
            self.sector_name = None
            self.classification = None

    def get_choices(self):
        """Return list of tuples for form select based on sector + classification."""
        if not self.sector_name or not self.classification:
            return []

        missions_by_sector = self.SECTOR_MISSION_MAP.get(self.sector_name, {})
        missions = missions_by_sector.get(self.classification, [])
        return [(m, m) for m in missions]

    def validate_choice(self, mission_statement):
        if not self.sector_name or not self.classification:
            raise ValueError("Organization sector or classification not set.")

        missions_by_sector = self.SECTOR_MISSION_MAP.get(self.sector_name, {})
        valid_missions = missions_by_sector.get(self.classification, [])
        if mission_statement not in valid_missions:
            raise ValueError(
                f"Invalid mission '{mission_statement}' for sector '{self.sector_name}' and classification '{self.classification}'.")

    def create_mission(self, mission_statement):
        self.validate_choice(mission_statement)
        return Mission.objects.create(
            organization_name=self.org,
            mission_statement=mission_statement
        )